### ISSUE TITLE
Exception: Could not get profile after receiving API endpoint

### ISSUE THREAD

**Issue by pawelkw** [AHAAAAAAA/PokemonGo-Map#103]
```
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/179/rpc
[-] Ooops...
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 374, in main
    raise Exception("Could not get profile")
Exception: Could not get profile

```

**Comment by Pepsai** [comment]
Getting the same, but im pretty sure it's because the servers are having issues.

**Comment by pawelkw** [comment]
Yep, you might be right. Even if that's the case then maybe some retry mechanism would be better than throwing an exception.

**Comment by marauder37** [comment]
There is already a great deal of retrying around those calls, please confirm you have the latest code?

**Comment by pawelkw** [comment]
@marauder37 I didn't have the latest code. I was at 33b41ae. Seems to be handled better now.
