### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by jnovack** [AHAAAAAAA/PokemonGo-Map#1095]
Received an `UnboundLocalError` after my 12th scan (at the beginning of the 13th scan).

```
2016-07-22 01:22:40,871 [     search] [   INFO] Completed 100.00% of scan.
2016-07-22 01:22:41,873 [     search] [   INFO] Scanning complete.   ## 12th Scan Complete
2016-07-22 01:22:42,874 [     search] [   INFO] Skipping Pokemon Go login process since already logged in for another 1463.13 seconds
2016-07-22 01:22:42,874 [     search] [   INFO] Scanning step 1 of 25.
2016-07-22 01:22:43,027 [     search] [  ERROR] Scan step failed. Response dictionary key error.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/src/app/pogom/search.py", line 99, in search_loop
    search(args)
  File "/usr/src/app/pogom/search.py", line 87, in search
    failed_consecutive += 1
UnboundLocalError: local variable 'failed_consecutive' referenced before assignment
```

Does not recover.  Does not exit.  App must be manually restarted.

Running again with `-d`, I receive the following.  This time, I can't even run my first scan.

```
2016-07-22 01:31:17,743 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-22 01:31:17,746 [   auth_ptc] [   INFO] PTC login for: **HIDDEN**
2016-07-22 01:31:17,757 [connectionpool] [   INFO] Starting new HTTPS connection (1): sso.pokemon.com
2016-07-22 01:31:17,772 [  _internal] [   INFO]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2016-07-22 01:31:17,773 [  _internal] [   INFO]  * Restarting with stat
2016-07-22 01:31:17,865 [connectionpool] [  DEBUG] "GET /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize HTTP/1.1" 200 103
2016-07-22 01:31:17,935 [connectionpool] [  DEBUG] "POST /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize HTTP/1.1" 302 0
2016-07-22 01:31:17,991 [connectionpool] [  DEBUG] "GET /sso/oauth2.0/callbackAuthorize?ticket=**HIDDEN**-sso.pokemon.com HTTP/1.1" 500 2565
2016-07-22 01:31:18,051 [connectionpool] [  DEBUG] "POST /sso/oauth2.0/accessToken HTTP/1.1" 200 104
2016-07-22 01:31:18,053 [   auth_ptc] [   INFO] PTC Login successful
2016-07-22 01:31:18,056 [connectionpool] [   INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-07-22 01:31:18,298 [  runserver] [   INFO] Parsed location is: **HIDDEN** (lat/lng/alt)
2016-07-22 01:31:18,299 [connectionpool] [  DEBUG] "POST /plfe/rpc HTTP/1.1" 200 None
2016-07-22 01:31:18,305 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-22 01:31:18,305 [     search] [   INFO] Scanning step 1 of 25.
2016-07-22 01:31:18,309 [connectionpool] [   INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-07-22 01:31:18,309 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-22 01:31:18,311 [   auth_ptc] [   INFO] PTC login for: **HIDDEN**
2016-07-22 01:31:18,312 [  _internal] [WARNING]  * Debugger is active!
2016-07-22 01:31:18,318 [connectionpool] [   INFO] Starting new HTTPS connection (1): sso.pokemon.com
2016-07-22 01:31:18,322 [  _internal] [   INFO]  * Debugger pin code: **HIDDEN**
2016-07-22 01:31:18,415 [connectionpool] [  DEBUG] "GET /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize HTTP/1.1" 200 103
2016-07-22 01:31:18,484 [connectionpool] [  DEBUG] "POST /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize HTTP/1.1" 302 0
2016-07-22 01:31:18,534 [connectionpool] [  DEBUG] "POST /plfe/208/rpc HTTP/1.1" 200 None
2016-07-22 01:31:18,537 [connectionpool] [  DEBUG] "GET /sso/oauth2.0/callbackAuthorize?ticket=**HIDDEN**-sso.pokemon.com HTTP/1.1" 500 2565
2016-07-22 01:31:18,545 [     search] [  ERROR] Scan step failed. Response dictionary key error.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/src/app/pogom/search.py", line 99, in search_loop
    search(args)
  File "/usr/src/app/pogom/search.py", line 87, in search
    failed_consecutive += 1
UnboundLocalError: local variable 'failed_consecutive' referenced before assignment

2016-07-22 01:31:18,599 [connectionpool] [  DEBUG] "POST /sso/oauth2.0/accessToken HTTP/1.1" 200 104
2016-07-22 01:31:18,600 [   auth_ptc] [   INFO] PTC Login successful
2016-07-22 01:31:18,603 [connectionpool] [   INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-07-22 01:31:18,848 [connectionpool] [  DEBUG] "POST /plfe/rpc HTTP/1.1" 200 None
2016-07-22 01:31:18,852 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-22 01:31:18,852 [     search] [   INFO] Scanning step 1 of 25.
2016-07-22 01:31:18,855 [connectionpool] [   INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-07-22 01:31:19,076 [connectionpool] [  DEBUG] "POST /plfe/208/rpc HTTP/1.1" 200 None
2016-07-22 01:31:19,086 [     search] [  ERROR] Scan step failed. Response dictionary key error.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/src/app/pogom/search.py", line 99, in search_loop
    search(args)
  File "/usr/src/app/pogom/search.py", line 87, in search
    failed_consecutive += 1
UnboundLocalError: local variable 'failed_consecutive' referenced before assignment
```

## Possible Solution

Banned already??? This is a brand new account.

www.ispokemongodownornot.com says everything was green during this time. App on phone still works.

Since typing this, and trying to run again, everything is ok again (may happen again later).  Are we scanning too fast? Need that delay?

## Context

Scanning stopped.

## Your Environment

* Version used: Commit da20e28
* Environment name and version (e.g. Python 2.7): Python 2.7, Docker
* Operating System and version (desktop or mobile): Alpine 2.7 Docker Image

**Comment by MonkeyLeeT** [comment]
#1078 Pretty once you hit error you'll never recover. PR should fix it.

Feel free to help for testing the PR.
