### ISSUE TITLE
map label unable to concatenate disappear_timestamp

### ISSUE THREAD

**Issue by stanleykylee** [AHAAAAAAA/PokemonGo-Map#111]
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 490, in main
    '<center class="label-countdown" data-disappears-at="'+disappear_timestamp+'">'+disappears_at+'</center>'
TypeError: coercing to Unicode: need string or buffer, float found

**Comment by Corfann** [comment]
You can enter to the PTC account? 
The error isn't the code

**Comment by crckdns** [comment]
same problem here after the update
`[-] looping: step 0 of 25
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 489, in main
    '<center class="label-countdown" data-disappears-at="'+disappear_timestamp+'">'+disappears_at+'</center>'
TypeError: coercing to Unicode: need string or buffer, float found
`

**Comment by ryantheleach** [comment]
disappear_timestamp needs to be wrapped in a str(disappear_timestamp)

**Comment by nborrmann** [comment]
This whole html thing should be refactored into a proper template.

**Comment by crckdns** [comment]
casting into string works as ryantheleach said~

**Comment by crckdns** [comment]
ouh... I see..  the script runs, but that's it. The map itself stays clean after that, only "Pokemon GO Map" is showing.

**Comment by sykhro** [comment]
A push was made to the wrong branch, hence the error.  Fixed with  204c215

**Comment by ryantheleach** [comment]
Thanks.
