### ISSUE TITLE
'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by YuboHu** [AHAAAAAAA/PokemonGo-Map#1127]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_except
ion
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch
_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch
_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_requ
est
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 892, in send_stati
c_file
    cache_timeout=cache_timeout)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 633, in send_from_
directory
    filename = safe_join(directory, filename)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 1: ordinal
not in range(128)

It seems have already launched, but everytime I try to connect to localhost:5000, the above lines came up. And no pokemon is showing in the map.
I am using win 10, python 2.7

**Comment by asottile** [comment]
You've got a non-ascii character in the path that you're running in.  Try another directory as a workaround?

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
