### ISSUE TITLE
auth tickets are a mess! api._auth_provider._ticket_expire is a string

### ISSUE THREAD

**Issue by kaysond** [AHAAAAAAA/PokemonGo-Map#1141]
Causes this error to occur, but not consistently. I imagine the api is sometimes setting something unexpected in the _ticket_expire variable

2016-07-22T06:22:22.627426+00:00 app[web.1]: Exception in thread search_thread:
2016-07-22T06:22:22.627456+00:00 app[web.1]: Traceback (most recent call last):
2016-07-22T06:22:22.627459+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2016-07-22T06:22:22.627479+00:00 app[web.1]:     self.run()
2016-07-22T06:22:22.627426+00:00 app[web.1]: Exception in thread search_thread:
2016-07-22T06:22:22.627456+00:00 app[web.1]: Traceback (most recent call last):
2016-07-22T06:22:22.627482+00:00 app[web.1]:     search(args)
2016-07-22T06:22:22.627483+00:00 app[web.1]:   File "/app/pogom/search.py", line 63, in search
2016-07-22T06:22:22.627488+00:00 app[web.1]: 
2016-07-22T06:22:22.627426+00:00 app[web.1]: Exception in thread search_thread:
2016-07-22T06:22:22.627482+00:00 app[web.1]:     search(args)
2016-07-22T06:22:22.627484+00:00 app[web.1]:     remaining_time = api._auth_provider._ticket_expire/1000 - time.time()
2016-07-22T06:22:22.627488+00:00 app[web.1]: 
2016-07-22T06:22:22.627484+00:00 app[web.1]: TypeError: unsupported operand type(s) for /: 'str' and 'int'

After some debugging - the first rpc POST request returns only two auth_ticket values. The first is a long alphanumeric/punctuation. The second is an integer.

The search thread then makes a POST request to /plfe/rpc instead of the given endpoint from before, which generates a third, different auth_ticket (another alphanumeric/punctuation), though this doesn't seem to overwrite the alphanumeric.

The first search starts before auth_tickets get populated, so it runs fine. On the second loop, it crashes because of this error.

**Comment by kaysond** [comment]
Looks like _ticket_expire is set to: "y3FPIf7/IHXaIDLEQJLkVg==" in my case.

**Comment by mhelmetag** [comment]
Yeah I see this as well on my heroku instance. Can't seem to get passed one search loop.

**Comment by kaysond** [comment]
Thanks @HanSolo80 I remembered seeing your issue and thinking that was the problem, but couldn't find it again when I was searching. I wonder why the parameters are coming in a different order... The protobuf has the ticket expire field in the index 1 position. I think the parser needs to be smarter and instead of passing the tuple and going by index, it needs to pick by name of the field
