### ISSUE TITLE
Server Execution Issue: AttributeError: function '__gmpz_init' not found

### ISSUE THREAD

**Issue by tcastantine** [AHAAAAAAA/PokemonGo-Map#1147]
Attempted to run the Master Branch and ran into some problems, so I decided to try the Dev Branch instead.  I'm experiencing the exact same issue.

Python Env: 2.7.12 (clean install)
OS: Windows 7 x64
Execution: python runserver.py -a ptc -u myusername -p mypassword -l "Portage Park, Chicago" -st 10

Traceback (most recent call last):
  File "runserver.py", line 12, in <module>
    from pogom.search import search_loop
  File "c:\PS\Python\POGO-D\pogom\search.py", line 7, in <module>
    from pgoapi import PGoApi
  File "c:\PS\Python\POGO-D\pogom\pgoapi\__init__.py", line 1, in <module>
    from pgoapi      import *
  File "c:\PS\Python\POGO-D\pogom\pgoapi\pgoapi.py", line 34, in <module>
    from auth_google import AuthGoogle
  File "c:\PS\Python\POGO-D\pogom\pgoapi\auth_google.py", line 29, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 83, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "C:\Python27\lib\site-packages\Cryptodome\Math\Numbers.py", line 42, in <module>
    from Cryptodome.Math._Numbers_gmp import Integer
  File "C:\Python27\lib\site-packages\Cryptodome\Math\_Numbers_gmp.py", line 155, in <module>
    _gmp.mpz_init = lib.__gmpz_init
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function '__gmpz_init' not found

**Comment by tcastantine** [comment]
Resolved in this thread.

Edit: C:\Python27\Lib\site-packages\Cryptodome\Math\_Numbers_gmp.py
(Line 99)
raise OSError

try:
    **raise OSError**
    gmp_defs = "typedef unsigned long UNIX_ULONG;" + gmp_defs_common
    lib = load_lib("gmp", gmp_defs)

(Lines 111-112 - After Inserting Previous Edit)
else:
   gmp_defs = gmp_defs_common

gmp_defs = "typedef unsigned long long UNIX_ULONG;" + gmp_defs_common
        c_ulong = c_ulonglong
    **else:
        gmp_defs = gmp_defs_common**
    # Try to load private MPIR lib first (wheel)

**Comment by maestroi** [comment]
got this problem in windows 10 and the fix did not work
