### ISSUE TITLE
Login failed / Just get requests / No scan

### ISSUE THREAD

**Issue by Quebroph** [AHAAAAAAA/PokemonGo-Map#1173]
Script is not logging in - is there a server down?

**Comment by Quebroph** [comment]
<img width="1164" alt="bildschirmfoto 2016-07-22 um 11 16 57" src="https://cloud.githubusercontent.com/assets/2054568/17052484/e7759d3e-4ffd-11e6-8538-8434762e87c8.png">

**Comment by Valareos** [comment]
http://ispokemongodownornot.com/  Pokemon GO Server is down.  (at least the ptc login side) if you happen to already be logged in you will be getting data

**Comment by brumie** [comment]
https://go.jooas.com/ just went down and up
try again

**Comment by Quebroph** [comment]
i restartet the server - nothing better.

<img width="735" alt="bildschirmfoto 2016-07-22 um 11 22 17" src="https://cloud.githubusercontent.com/assets/2054568/17052615/a2f5e1ea-4ffe-11e6-8324-1e6a8c531728.png">

**Comment by Valareos** [comment]
you use a ptc login correct? Its still down at the moment

**Comment by Quebroph** [comment]
are there other login methods? how can i use another?

**Comment by nikos90** [comment]
it's working now for me

**Comment by cool-story-bruh** [comment]
getting similar error
```
2016-07-22T09:23:21.443701+00:00 app[web.1]: Exception in thread search_thread:
2016-07-22T09:23:21.443711+00:00 app[web.1]: Traceback (most recent call last):
2016-07-22T09:23:21.443715+00:00 app[web.1]:     self.__target(*self.__args, **self.__kwargs)
2016-07-22T09:23:21.443716+00:00 app[web.1]:   File "/app/pogom/search.py", line 101, in search_loop
2016-07-22T09:23:21.443717+00:00 app[web.1]:   File "/app/pogom/search.py", line 70, in search
2016-07-22T09:23:21.443718+00:00 app[web.1]:     login(args, position)
2016-07-22T09:23:21.443724+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/json/decoder.py", line 364, in decode
2016-07-22T09:23:21.443724+00:00 app[web.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2016-07-22T09:23:21.443724+00:00 app[web.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2016-07-22T09:23:21.443721+00:00 app[web.1]:     if not self._auth_provider.login(username, password):
2016-07-22T09:23:21.443721+00:00 app[web.1]:   File "/app/pogom/pgoapi/auth_ptc.py", line 54, in login
2016-07-22T09:23:21.443722+00:00 app[web.1]:     jdata = json.loads(r.content)
2016-07-22T09:23:21.443722+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/json/__init__.py", line 339, in loads
2016-07-22T09:23:21.443723+00:00 app[web.1]:     return _default_decoder.decode(s)
2016-07-22T09:23:21.443726+00:00 app[web.1]: ValueError: No JSON object could be decoded
```

**Comment by Valareos** [comment]
the other method is using the google auth login. I don,t use this method myself, and I would NOT reccomend using it on your "live" account.  but you can use the switch -a google (instead of -a ptc) and put your google name and password in it.

**Comment by havenofear** [comment]
nikos90, are u using google or ptc account?

**Comment by nikos90** [comment]
ptc

**Comment by Quebroph** [comment]
i´m using PTC - how to use google account with this script?

**Comment by Valareos** [comment]
points up to his last response

**Comment by Valareos** [comment]
Also, if you happened to get lucky to sign in via PTC and are IN, then it will work (until you need to restart it). because the servers themselves are up. its the login server for ptc thats down

**Comment by Valareos** [comment]
of course now, according to http://ispokemongodownornot.com/, the europe google login server just went down again

**Comment by mhelmetag** [comment]
@Quebroph , you can change your `AUTH_SERVICE` env variable from ptc to google locally or on heroku and then set the other variables to use your google username and password.

**Comment by Quebroph** [comment]
python runserver.py **-a google -u MAILADDRESSE -p PASSWORD** -l "51.542367 9.937320" -st 10 -H 151.252.51.10 -ar -P 5000

Like this? Im getting login error.

<img width="701" alt="bildschirmfoto 2016-07-22 um 11 34 29" src="https://cloud.githubusercontent.com/assets/2054568/17053036/485cae88-5000-11e6-9bee-4304895c672a.png">

**Comment by elviric** [comment]
Login via PTC led to:
` RPC Session Token: error=invalid_grant`
Followed by
`[-] retrying_api_req: request error (Unexpected end-group tag.), retrying`

**Comment by lparkermg** [comment]
Yeah keep an eye on this http://ispokemongodownornot.com as they seem to be having server issues all over at the moment. It seems to be pretty unstable.

**Comment by ChristianLuxem** [comment]
By the way,
if the server is down, there should be an better Error-Message and not an Exception.
So for me that is a valid bug, and should be fixed.

**Comment by lparkermg** [comment]
@ChristianLuxem That's certainly true, maybe more error handling.

**Comment by medghaim** [comment]
Please open a separate issue guys.
