### ISSUE TITLE
Exception when logging in

### ISSUE THREAD

**Issue by DavidMaza** [AHAAAAAAA/PokemonGo-Map#1176]
I sometimes (but not always) receive the below exception when logging in:

Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\David\Desktop\PokeMonGo\pogom\search.py", line 101, in search_loop
    search(args)
  File "C:\Users\David\Desktop\PokeMonGo\pogom\search.py", line 70, in search
    login(args, position)
  File "C:\Users\David\Desktop\PokeMonGo\pogom\search.py", line 51, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "C:\Users\David\Desktop\PokeMonGo\pogom\pgoapi\pgoapi.py", line 144, in login
    if not self._auth_provider.login(username, password):
  File "C:\Users\David\Desktop\PokeMonGo\pogom\pgoapi\auth_ptc.py", line 54, in login
    jdata = json.loads(r.content)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

## Your Environment
* Version used: 512efc6
* Environment name and version: Python 2.7
* Operating System and version: Windows 10

**Comment by lparkermg** [comment]
See this #1173
