### ISSUE TITLE
SSL Error Google?

### ISSUE THREAD

**Issue by severeonz** [AHAAAAAAA/PokemonGo-Map#1180]
## Expected Behavior
Using Google account to log in to server.

## Current Behavior
Getting the following error while running this command:
Any ideas? I did not see this error come by yet. What am I doing wrong? I am using the dev branch

python /var/www/PokemonGo-Map/runserver.py -a google -u ****@gmail.com -p **** -l "51.5400805,4.2141663" -st 5 -sd 10 -H **.**.**.** -P 5001

2016-07-22 12:11:44,383 [  runserver] [   INFO] Parsed location is: 51.5401/4.2142/0.0000 (lat/lng/alt)
2016-07-22 12:11:44,386 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-22 12:11:44,389 [auth_google] [   INFO] Google login for: ****@gmail.com
2016-07-22 12:11:44,439 [  _internal] [   INFO]  * Running on http://*:5001/ (Press CTRL+C to quit)
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/www/PokemonGo-Map/pogom/search.py", line 99, in search_loop
    search(args)
  File "/var/www/PokemonGo-Map/pogom/search.py", line 70, in search
    login(args, position)
  File "/var/www/PokemonGo-Map/pogom/search.py", line 51, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "/var/www/PokemonGo-Map/pogom/pgoapi/pgoapi.py", line 144, in login
    if not self._auth_provider.login(username, password):
  File "/var/www/PokemonGo-Map/pogom/pgoapi/auth_google.py", line 45, in login
    login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)

## Your Environment
Debian GNU/Linux 7 \n \l
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u3 x86_64 GNU/Linux
Python 2.7.3

**Comment by severeonz** [comment]
I fixed this by doing the following.
I found a solution. There seems to be a major issue in the version of  certifi that was running.

pip uninstall -y certifi && pip install certifi==2015.04.28
