### ISSUE TITLE
ProxyError requests.packages.urllib3.connection.VerifiedHTTPSConnection

### ISSUE THREAD

**Issue by hendraakit** [AHAAAAAAA/PokemonGo-Map#1209]
Guys why i got proxy error?
This error appear after runserver.py -a ptc -u username -p passwrd
 -l "-7.782900, 110.392963" -st 10

Im sorry if my post so messed up, just a newbie.

Please help me. :(

Thanks

```
 D:\pogo\PokemonGo-Map-develop>runserver.py -a ptc -u username -p passwrd
 -l "-7.782900, 110.392963" -st 10
2016-07-22 19:35:44,098 [  runserver] [   INFO] Parsed location is: -7.7829/110.
3930/0.0000 (lat/lng/alt)
2016-07-22 19:35:44,099 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-22 19:35:44,101 [   auth_ptc] [   INFO] PTC login for: username
2016-07-22 19:35:44,131 [  _internal] [   INFO]  * Running on http://127.0.0.1:5
000/ (Press CTRL+C to quit)
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\pogo\PokemonGo-Map-develop\pogom\search.py", line 101, in search_loop

    search(args)
  File "D:\pogo\PokemonGo-Map-develop\pogom\search.py", line 70, in search
    login(args, position)
  File "D:\pogo\PokemonGo-Map-develop\pogom\search.py", line 51, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "D:\pogo\PokemonGo-Map-develop\pogom\pgoapi\pgoapi.py", line 144, in logi
n
    if not self._auth_provider.login(username, password):
  File "D:\pogo\PokemonGo-Map-develop\pogom\pgoapi\auth_ptc.py", line 52, in log
in
    r = self._session.get(self.PTC_LOGIN_URL, headers=head)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 465, in send
    raise ProxyError(e, request=request)
ProxyError: HTTPSConnectionPool(host='sso.pokemon.com', port=443): Max retries e
xceeded with url: /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth
2.0%2FcallbackAuthorize (Caused by ProxyError('Cannot connect to proxy.', NewCon
nectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection obje
ct at 0x035ACFF0>: Failed to establish a new connection: [Errno 11001] getaddrin
fo failed',)))
```
//

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
