### ISSUE TITLE
Does Heroku automatically update with the latest code?

### ISSUE THREAD

**Issue by Giggitybyte** [AHAAAAAAA/PokemonGo-Map#1235]
Not sure if this would be the best place to ask, but I'd like to know.

**Comment by frdmn** [comment]
Nope, it doesn't. You need to manually update the git repository.

**Comment by c133** [comment]
When running on Heroku, after scan reaches %100, it does not restart because of a crash:

`Jul 22 10:12:45 pkmongo-map app/web.1:  Traceback (most recent call last): 
Jul 22 10:12:45 pkmongo-map app/web.1:    File "/app/.heroku/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner 
Jul 22 10:12:45 pkmongo-map app/web.1:      self.run() 
Jul 22 10:12:45 pkmongo-map app/web.1:    File "/app/.heroku/python/lib/python2.7/threading.py", line 754, in run 
Jul 22 10:12:45 pkmongo-map app/web.1:      self.__target(*self.__args, **self.__kwargs) 
Jul 22 10:12:45 pkmongo-map app/web.1:    File "/app/pogom/search.py", line 96, in search_loop 
Jul 22 10:12:45 pkmongo-map app/web.1:      search(args) 
Jul 22 10:12:45 pkmongo-map app/web.1:    File "/app/pogom/search.py", line 60, in search 
Jul 22 10:12:45 pkmongo-map app/web.1:      remaining_time = api._auth_provider._ticket_expire/1000 - time.time() 
Jul 22 10:12:45 pkmongo-map app/web.1:  TypeError: unsupported operand type(s) for /: 'str' and 'int' `

Is there a fix for this?

**Comment by Giggitybyte** [comment]
@frdmn Darn, that sucks. Thanks for responding!

**Comment by orzeu** [comment]
Any help on how to update current heroku app to the newest release?

**Comment by Giggitybyte** [comment]
@orzeu The wiki tells how to [deploy to Heroku manually](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Heroku-Deployment). I was thinking that maybe a cron job that executes those commands would keep the Heroku app updated with the latest changes. I haven't played around with it, but I think that might work.

**Comment by Lorkster** [comment]
I'm wondering the same thing. Sure, I can go the manual route, but I'd like to know if that's how it's supposed to be done after doing the auto deploy?

**Comment by Lorkster** [comment]
I went with the following:
* Added heroku as a remote: ```heroku git:remote -a my_project_name```
* Added my ssl key: ```heroku keys:add````
* Pushed the develop branch to heroku master: ```git push -f heroku develop:master```
