### ISSUE TITLE
 ImportError: No module named google.protobuf

### ISSUE THREAD

**Issue by faxihrim** [AHAAAAAAA/PokemonGo-Map#1249]
Traceback (most recent call last):   File "example.py", line 19, in <module>     import pokemon_pb2   File "D:\PokemonGo-Map-master\pokemon_pb2.py", line 6, in <module>     from google.protobuf import descriptor as _descriptor ImportError: No module named google.protobuf

So?

**Comment by BillyWM** [comment]
Did you install dependencies per https://github.com/AHAAAAAAA/PokemonGo-Map/wiki?

**Comment by faxihrim** [comment]
"Requirement already satisfied"

**Comment by faxihrim** [comment]
fixed

- "pip uninstall protobuf" in cmd
run setup.bat in easy setup folder
Thank you.
