### ISSUE TITLE
Looping step error

### ISSUE THREAD

**Issue by princeomlet** [AHAAAAAAA/PokemonGo-Map#125]
### Environment info
Operating System: Mac OS El Capitan 10.11.5

Installed version of Python: Python ver 2.7

### Logs or other output that would be helpful
.......
[-] looping: step 0 of 1
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",))), retrying
Exception in thread search_thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 489, in main
    '<center class="label-countdown" data-disappears-at="'+disappear_timestamp+'">'+disappears_at+'</center>'
TypeError: coercing to Unicode: need string or buffer, float found

**Comment by sykhro** [comment]
Already fixed, pull latest master.
