### ISSUE TITLE
peewwee.ImproperlyConfigured

### ISSUE THREAD

**Issue by firstof9** [AHAAAAAAA/PokemonGo-Map#1250]
Getting the following error when attempting to run latest dev branch.
sqlite3 and pysqlite are both installed

`
Traceback (most recent call last):
  File "runserver.py", line 45, in <module>
    create_tables()
  File "/home/astroixb/domains/pokemap.astria-porta.net/public_html/PokemonGo-Map/pogom/models.py", line 157, in create_tables
    db.connect()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3657, in _connect
    raise ImproperlyConfigured('pysqlite or sqlite3 must be installed.')
peewee.ImproperlyConfigured: pysqlite or sqlite3 must be installed.
`

**Comment by firstof9** [comment]
Forgot to compile python2.7 with sqlite3-dev installed.

**Comment by QuitHub** [comment]
I've got the same issue, how should I go about resolving it? How do I 'compile python2.7 with sqlite3-dev installed.'

**Comment by jevdiego** [comment]
Having the same issue.. damn! How'd you go about fixing this?

**Comment by ndragon798** [comment]
sudo pip install pymysql

**Comment by firstof9** [comment]
In CentOS:
yum install sqlite3-dev

then compile your python2.7 source
