### ISSUE TITLE
Cronjob failed

### ISSUE THREAD

**Issue by ELusiveLPFAN** [AHAAAAAAA/PokemonGo-Map#1257]
Im starting server like this:
> nohup /home/eluzive/pogomap/runserver.py -a google -u user -p password -l "location" -st 15 -H 192.168.*.* -P 5000

And I wanna put it to cron, restarting every 30min.
Make script:
> #!/bin/bash
pkill -9 -f python
sleep 5
/usr/bin/python /home/eluzive/pogomap/runserver.py -a google -u user -p password -l "location" -st 15 -H 192.168.*.* -P 5000

Put it to cron:
> */10  * * * * /home/eluzive/pogomap/cron.sh 2> /tmp/out

And when time comes to do cronjob.. I get errors:

> 2016-07-22 18:40:06,947 [  runserver] [   INFO] Parsed location is: 00.00000/00.0000/0.0000 (lat/lng/alt)
2016-07-22 18:40:06,948 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-22 18:40:06,948 [auth_google] [   INFO] Google login for: user
2016-07-22 18:40:06,966 [  _internal] [   INFO]  * Running on http://192.168.*.*:5000/ (Press CTRL+C to quit)
[2016-07-22 18:40:07,473] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/eluzive/pogomap/pogom/app.py", line 34, in raw_data
    d['pokestops'] = Pokestop.get_all()
  File "/home/eluzive/pogomap/pogom/models.py", line 24, in get_all
    return [m for m in cls.select().dicts()]
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.active_pokemon_id
2016-07-22 18:40:07,473 [        app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/eluzive/pogomap/pogom/app.py", line 34, in raw_data
    d['pokestops'] = Pokestop.get_all()
  File "/home/eluzive/pogomap/pogom/models.py", line 24, in get_all
    return [m for m in cls.select().dicts()]

**Comment by myrdyr** [comment]
I get the same error at a7caf473ec554d80df90803a7085674c50e921b1. Not using Cron, but simply starting the app.

**Comment by denniskai1234** [comment]
go with cd in the directory before you start it.

**Comment by ELusiveLPFAN** [comment]
Temporary fixed it, buy running cron with sudo.
