### ISSUE TITLE
OperationalError: table pokestop has no column named active_pokemon_id

### ISSUE THREAD

**Issue by myrdyr** [AHAAAAAAA/PokemonGo-Map#1262]
## Expected Behavior
That the application works, just as in master, after all Python requirements are installed.

## Current Behavior
The application crashes after login.

## Steps to Reproduce (for bugs)

1. PokemonGo-Map> python runserver.py -a ptc -u username -p password -l "Central Park" -st 4
2. Get this error:

> 2016-07-22 17:51:29,543 [  runserver] [   INFO] Parsed location is: 46.9734/-123.6924/0.0000 (lat/lng/alt)
2016-07-22 17:51:29,546 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-22 17:51:29,551 [   auth_ptc] [   INFO] PTC login for: username
2016-07-22 17:51:33,006 [   auth_ptc] [   INFO] PTC Login successful
2016-07-22 17:51:33,470 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-22 17:51:33,470 [     search] [   INFO] Scanning step 1 of 16.
2016-07-22 17:51:33,901 [     models] [   INFO] Upserting 1 pokemon
2016-07-22 17:51:34,447 [     models] [   INFO] Upserting 2 pokestops
Exception in thread search_thread:
Traceback (most recent call last):
  File "Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "PokemonGo-Map\pogom\search.py", line 96, in search_loop
    search(args)
  File "PokemonGo-Map\pogom\search.py", line 79, in search
    parse_map(response_dict)
  File "PokemonGo-Map\pogom\models.py", line 138, in parse_map
    bulk_upsert(Pokestop, pokestops)
  File "PokemonGo-Map\pogom\models.py", line 151, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "Python27\lib\site-packages\peewee.py", line 3237, in execute
    return self._insert_with_loop()
  File "Python27\lib\site-packages\peewee.py", line 3220, in _insert_with_loop
    .upsert(self._upsert)
  File "Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table pokestop has no column named active_pokemon_id`

## Your Environment

* Version used: d7f4af957d7e280ede0f6cda4e14c1df6d28e089
* Windows 10 64-bit, Python 2.7.7
* Pip freeze output:

> bcrypt==2.0.0
beautifulsoup4==4.4.1
cffi==1.1.1
characteristic==14.3.0
click==6.6
coverage==4.1
coveralls==1.1
cryptography==0.9.1
cssselect==0.9.1
dicttoxml==1.6.6
dnspython==1.12.0
docopt==0.6.2
ecdsa==0.13
enum34==1.0.4
Flask==0.11.1
Flask-Cors==2.1.2
Flask-GoogleMaps==0.2.0
ftptool==0.7.1
future==0.15.2
geopy==1.11.0
gevent==1.1b2
gpsoauth==0.3.0
greenlet==0.4.7
hurry.filesize==0.9
idna==2.0
ipaddress==1.0.7
itsdangerous==0.24
Jinja2==2.8
jsonrpclib==0.1.3
lxml==3.4.4
MarkupSafe==0.23
mechanize==0.2.5
ndg-httpsclient==0.4.0
netaddr==0.7.11
olefile==0.42.1
pbr==1.8.1
peewee==2.8.1
protobuf==2.6.1
protobuf-to-dict==0.1.0
pyasn1==0.1.8
pyasn1-modules==0.0.5
pycparser==2.13
pycrypto==2.6
pycryptodomex==3.4.2
pyOpenSSL==0.15.1
PyPDF2==1.25.1
pywin32==219
queuelib==1.2.2
requests==2.10.0
s2sphere==0.2.4
Scrapy==0.24.6
service-identity==14.0.0
simplejson==3.8.1
six==1.10.0
slowaes==0.1a1
stevedore==1.10.0
twisted==15.2.1
virtualenv==13.1.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
virtualenvwrapper-win==1.2.1
w3lib==1.11.0
Werkzeug==0.11.10
XlsxWriter==0.7.3
zope.interface==4.1.3

**Comment by Faustvii** [comment]
Could you try to rename pogom.db and see if that solves the issue.

**Comment by myrdyr** [comment]
Thanks, this seems to have solved the issue. So this is a DB corruption issue? Is it recommended to clear this file every now and then or something?

**Comment by Faustvii** [comment]
Most likely a model change between versions causing the conflict.
It's a good idea to rename the file if you experience issues after upgrading versions.
