### ISSUE TITLE
HowTo or Request lets see where it goes! Multiple users.

### ISSUE THREAD

**Issue by neruve** [AHAAAAAAA/PokemonGo-Map#1298]
I use this along with about 4 other people I work with. Currently we all use the same map as I think you can only have it do one. Other than maintaining a different directory and using a different ddns port for each person. Is it possible to almost have separate users all with different locations? 

I'm not opposed to separate directories. I would just have to make a batch file to update all of them at once with new releases. Was just thinking there could be a need for someone else as well in a similar situation.

**Comment by PCVXD** [comment]
Run an instance for every location you need. Run one instance normally and the others with the -ns flag which disables the webserver. All the Pokemon will appear on the same map. Apperently you can even use the same log-in data for every instance but I wouldn't do this to be on the safe side. If you really want other maps, you would have to place them in different directories I think. Different port only probably wouldn't work.

**Comment by neruve** [comment]
Okay, so if I run it with the -ns flag and a different login then it will be like all the pokemon will show up on one big map. But each browser would be able to focus on that particular part of the map. that makes sense. That will make it much easier for upkeep as well. I'll just have the other couple people make there own ptc account and i'll use theirs for there starting locations. Seems like it should work. I won't be able to test until I get home later tonight.

**Comment by neruve** [comment]
One more question. Lets say there were 5 of us total and I run this server 24/7. Would I have to worry about the 25000 hit limit for the google maps api key I have?

**Comment by PCVXD** [comment]
I don't think so, I think the limit resets daily.

**Comment by vinsilsim** [comment]
Hello PCVXD, I'm trying to put the flag -ns bad says it is not a valid command. Can you help me with this?

My command

C:\Python27\python.exe C:\Users\Administrator\Desktop\Pokemonmap\PokemonGo-Map-master\example.py -ar 10 -u **** -p **** -l "85th St Transverse, New York, NY 10024, Estados Unidos" -st 8 -H 172.31.1.100 -P 80 -ns

**Comment by craigbaines** [comment]
When i try running a second server with -ns, i get the following error:

`Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\Users\Craig\pokemon3\pogom\search.py", line 96, in search_loop
    search(args)
  File "c:\Users\Craig\pokemon3\pogom\search.py", line 79, in search
    parse_map(response_dict)
  File "c:\Users\Craig\pokemon3\pogom\models.py", line 134, in parse_map
    bulk_upsert(Pokemon, pokemons)
  File "c:\Users\Craig\pokemon3\pogom\models.py", line 151, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().exec
te()
  File "C:\Python27\lib\site-packages\peewee.py", line 3237, in execute
    return self._insert_with_loop()
  File "C:\Python27\lib\site-packages\peewee.py", line 3220, in _insert_with_lo
p
    .upsert(self._upsert)
  File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked`


Did you encounter this / have a solution? Thanks

**Comment by 2-m** [comment]
Got the same error @craigbaines

**Comment by PCVXD** [comment]
@vinsilsim You're using the master branch, this function is only in the develop branch. @craigbaines  I don't know, I'm not a developer. Maybe open a new issue. The only thing I can think of is that you probably shouldn't run both -ns and a flag that controls the webserver like -H or -P.

**Comment by 2-m** [comment]
@PCVXD I didn't even run the -H or -P flags, only ran -ns

**Comment by craigbaines** [comment]
im using the develop branch

**Comment by PCVXD** [comment]
Maybe it has something to do with Windows permissions. I'm running mine on a Ubuntu server and it's currently working.
