### ISSUE TITLE
Error in Login with PTC

### ISSUE THREAD

**Issue by chadsaun** [AHAAAAAAA/PokemonGo-Map#1323]
Here's the Traceback:

```
Traceback (most recent call last):
  File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 99, in main
    bot.start()
  File "/Users/someguy/Development/PokemonGo-Bot/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/Users/someguy/Development/PokemonGo-Bot/pokemongo_bot/__init__.py", line 79, in _setup_api
    if not self.api.login(self.config.auth_service, str(self.config.username), str(self.config.password)):
  File "/Users/someguy/.virtualenvs/pokebot/src/pgoapi/pgoapi/pgoapi.py", line 144, in login
    if not self._auth_provider.login(username, password):
  File "/Users/someguy/.virtualenvs/pokebot/src/pgoapi/pgoapi/auth_ptc.py", line 56, in login
    jdata = json.loads(r.content.decode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

## Your Environment

* Development branch
* Python 2.7
* Mac OS (latest) desktop

**Comment by kaysond** [comment]
ptc is down right now

**Comment by jangrewe** [comment]
Wasn't there some commit that puts this in a try/catch loop, to keep it from dying?

**Comment by jnovack** [comment]
![image](https://cloud.githubusercontent.com/assets/387006/17069080/a818f3a0-5022-11e6-8e14-ab1f9eb84b23.png)

**Comment by lparkermg** [comment]
It might be worth putting something in the FAQs to make sure to check something like http://ispokemongodownornot.com before posting an issue here.

**Comment by jnovack** [comment]
I love that there is a tag called "Not an issue: servers are down."
