### ISSUE TITLE
Search thread exits, leaves web server up by no more pokemon

### ISSUE THREAD

**Issue by chuyskywalker** [AHAAAAAAA/PokemonGo-Map#1329]
The search thread is throwing an exception and the program doesn't exit or retry, leaving it in a weird "hung" state.

The program should either exit, or restart the searching loop/thread/whatever.

## Current Behavior

Output:

```
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/src/app/pogom/search.py", line 96, in search_loop
    search(args)
  File "/usr/src/app/pogom/search.py", line 65, in search
    login(args, position)
  File "/usr/src/app/pogom/search.py", line 48, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "/usr/src/app/pogom/pgoapi/pgoapi.py", line 144, in login
    if not self._auth_provider.login(username, password):
  File "/usr/src/app/pogom/pgoapi/auth_ptc.py", line 54, in login
    jdata = json.loads(r.content)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

## Steps to Reproduce (for bugs)
1. Run the server for a while
2. ...
3. Hit bug!

## Your Environment
* Version: develop @ d59e1b9cb00a40ade203850973a3a777c0f0ee6e
* Environment name and version (e.g. Python 2.7): python2.7-alpine docker image

**Comment by mhelmetag** [comment]
I had this happen recently while running for awhile (on heroku) and then again while trying to restart the dyno. It might be because the PTC auth service is down. I saw this same issue when the service was down last night (around 2am PST).

**Comment by wcastello** [comment]
Not sure if someone else did it but #1340 fixes exactly this.

**Comment by mhelmetag** [comment]
@wcastello , that rescue looks good! Thanks for that!

**Comment by wcastello** [comment]
@mhelmetag changed to #1346

**Comment by chuyskywalker** [comment]
I'll get that merged locally and check it out.

**Comment by chuyskywalker** [comment]
Seems much more stable now.
