### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, float found

### ISSUE THREAD

**Issue by sand500** [AHAAAAAAA/PokemonGo-Map#133]
### Environment info
Operating System: Ubuntu 14.04.4 x64

Installed version of Python: 2.7.6

### Steps to reproduce
1. Ran the python script

### Logs or other output 

```
[+] POKECOIN: 0
[+] STARDUST: 0
[-] looping: step 0 of 25
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 489, in main
    '<center class="label-countdown" data-disappears-at="'+disappear_timestamp+'">'+disappears_at+'</center>'
TypeError: coercing to Unicode: need string or buffer, float found

```

**Comment by DerScreever** [comment]
this is already fixed. pull the latest changes
