### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by louispires** [AHAAAAAAA/PokemonGo-Map#1330]
## Expected Behaviour

Same as #839

This issue is almost guaranteed to be related to the username of the account running on the Windows Environment. We need to find a more permanent solution to this.
## Current Behaviour

Unable to update with the latest requirements and thus no map is working
## Possible Solution

Resolve comparison of any paths that might be contain the Username.
## Steps to Reproduce (for bugs)

1.	User name contains é
2.	  ![image](https://cloud.githubusercontent.com/assets/8841644/17069345/7b44cdfc-5056-11e6-8111-6fe924c78b19.png)
3.	I assume this fails to convert to Unicode as Python tries to do a compare between some arguments that might contain the username.

## Context

`SUCCESS: Specified value was saved.
Requirement already up-to-date: pip in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
c:\python27\lib\urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 271, in populate_link
    self.link = self._wheel_cache.cached_wheel(self.link, self.name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 68, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 148, in cached_wheel
    return pip.index.Link(path_to_url(path))
  File "c:\python27\lib\site-packages\pip\download.py", line 457, in path_to_url
    url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "c:\python27\lib\nturl2path.py", line 67, in pathname2url
    path = path + '/' + urllib.quote(comp)
  File "c:\python27\lib\urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'
Requirement already up-to-date: Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
c:\python27\lib\urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 271, in populate_link
    self.link = self._wheel_cache.cached_wheel(self.link, self.name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 68, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 148, in cached_wheel
    return pip.index.Link(path_to_url(path))
  File "c:\python27\lib\site-packages\pip\download.py", line 457, in path_to_url
    url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "c:\python27\lib\nturl2path.py", line 67, in pathname2url
    path = path + '/' + urllib.quote(comp)
  File "c:\python27\lib\urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'
The system cannot find the file specified.
Enter your Google API key here:
`
## Your Environment
Windows 10 Pro
Python 2.7
Windows Username: shité

**Comment by kleinfreund** [comment]
The following approach gets one a bit closer while allowing one to install all requirements except for protobuf_to_dict.

    pip install --no-cache-dir -r requirements.txt

When using the `setup.bat` script from the EasySetup directory, one needs to add `--no-cache-dir` to the two pip install commands in the batch script as well.

Now the only thing left to get it to work would be installing `protobuf_to_dict`.
