### ISSUE TITLE
Error Code 1 .../build/protobuf

### ISSUE THREAD

**Issue by N0916** [AHAAAAAAA/PokemonGo-Map#1426]
## Procedure
When running the command: `pip install -r requirements.txt`
I get the error: `Command python setup.py egg_info failed with error code 1 in /root/PokemonGo-Map-develop/build/protobuf`

If I ignore the error and continue onto the script execution: `python example.py -ar 10 -u [USERNAME] -p [PASSWORD] -l "[LOCATION]" -st 10`
I get the following error: `
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from flask_cors import CORS, cross_origin
ImportError: No module named flask_cors
`

## Full Log
The complete log upon command execution -
```
~# pip install -r requirements.txt
Downloading/unpacking Flask==0.11.1 (from -r requirements.txt (line 1))
  Downloading Flask-0.11.1.tar.gz (564Kb): 564Kb downloaded
  Running setup.py egg_info for package Flask
    
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes'
Downloading/unpacking Jinja2==2.8 (from -r requirements.txt (line 2))
  Downloading Jinja2-2.8.tar.gz (357Kb): 357Kb downloaded
  Running setup.py egg_info for package Jinja2
    
    warning: no files found matching 'run-tests.py'
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no files found matching '*' under directory 'jinja2/testsuite/res'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py egg_info for package MarkupSafe
    
Downloading/unpacking Werkzeug==0.11.10 (from -r requirements.txt (line 4))
  Downloading Werkzeug-0.11.10.tar.gz (1.2Mb): 1.2Mb downloaded
  Running setup.py egg_info for package Werkzeug
    
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes'
    warning: no previously-included files matching '*.py[cdo]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /usr/lib/python2.7 (from -r requirements.txt (line 5))
Downloading/unpacking click==6.6 (from -r requirements.txt (line 6))
  Downloading click-6.6.tar.gz (283Kb): 283Kb downloaded
  Running setup.py egg_info for package click
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking itsdangerous==0.24 (from -r requirements.txt (line 7))
  Downloading itsdangerous-0.24.tar.gz (46Kb): 46Kb downloaded
  Running setup.py egg_info for package itsdangerous
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking peewee==2.8.1 (from -r requirements.txt (line 8))
  Downloading peewee-2.8.1.tar.gz (474Kb): 474Kb downloaded
  Running setup.py egg_info for package peewee
    
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/lib/python2.7 (from -r requirements.txt (line 9))
Downloading/unpacking geopy==1.11.0 (from -r requirements.txt (line 10))
  Downloading geopy-1.11.0.tar.gz (88Kb): 88Kb downloaded
  Running setup.py egg_info for package geopy
    
    warning: no files found matching 'CHANGELOG'
    warning: no previously-included files matching '*' found under directory 'test'
    no previously-included directories found matching 'geopy/__pycache__'
    no previously-included directories found matching 'geopy/geocoders/__pycache__'
Downloading/unpacking protobuf==2.6.1 (from -r requirements.txt (line 11))
  Downloading protobuf-2.6.1.tar.gz (188Kb): 188Kb downloaded
  Running setup.py egg_info for package protobuf
    
    Installed /root/PokemonGo-Map-develop/build/protobuf/google_apputils-0.4.2-py2.7.egg
    Searching for pytz>=2010
    Reading http://pypi.python.org/simple/pytz/
    Best match: pytz 2016.6.1
    Downloading https://pypi.python.org/packages/79/a7/74bf57f5b10bebb8e605dc277484bddc5559ad8cf5082c90fcd64ab5dcc6/pytz-2016.6.1-py2.7.egg#md5=3b1dd4a944e92e84a6510faf81abd655
    Processing pytz-2016.6.1-py2.7.egg
    Extracting pytz-2016.6.1-py2.7.egg to /root/PokemonGo-Map-develop/build/protobuf
    
    Installed /root/PokemonGo-Map-develop/build/protobuf/pytz-2016.6.1-py2.7.egg
    Searching for python-gflags>=1.4
    Reading http://pypi.python.org/simple/python-gflags/
    Best match: python-gflags 3.0.5
    Downloading https://pypi.python.org/packages/1f/01/3ca6527f51b7ff26abb635d4e7e2fa8413c7cf191564cc2c1e535f50dec7/python-gflags-3.0.5.tar.gz#md5=0e3a06cb99b9883bf6abacc489f31297
    Processing python-gflags-3.0.5.tar.gz
    Running python-gflags-3.0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oyCXxC/python-gflags-3.0.5/egg-dist-tmp-F08cKL
    zip_safe flag not set; analyzing archive contents...
    
    Installed /root/PokemonGo-Map-develop/build/protobuf/python_gflags-3.0.5-py2.7.egg
    Searching for python-dateutil>=1.4
    Reading http://pypi.python.org/simple/python-dateutil/
    Best match: python-dateutil 2.5.3
    Downloading https://pypi.python.org/packages/b7/9f/ba2b6aaf27e74df59f31b77d1927d5b037cc79a89cda604071f93d289eaf/python-dateutil-2.5.3.zip#md5=52b3f339f41986c25c3a2247e722db17
    Processing python-dateutil-2.5.3.zip
    Running python-dateutil-2.5.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-CgWU5u/python-dateutil-2.5.3/egg-dist-tmp-tqkU2Y
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    
    Installed /root/PokemonGo-Map-develop/build/protobuf/python_dateutil-2.5.3-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/PokemonGo-Map-develop/build/protobuf/setup.py", line 200, in <module>
        "Protocol Buffers are Google's data interchange format.",
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (six 1.1.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.5'))
    Complete output from command python setup.py egg_info:
    

Installed /root/PokemonGo-Map-develop/build/protobuf/google_apputils-0.4.2-py2.7.egg

Searching for pytz>=2010

Reading http://pypi.python.org/simple/pytz/

Best match: pytz 2016.6.1

Downloading https://pypi.python.org/packages/79/a7/74bf57f5b10bebb8e605dc277484bddc5559ad8cf5082c90fcd64ab5dcc6/pytz-2016.6.1-py2.7.egg#md5=3b1dd4a944e92e84a6510faf81abd655

Processing pytz-2016.6.1-py2.7.egg

creating /root/PokemonGo-Map-develop/build/protobuf/pytz-2016.6.1-py2.7.egg

Extracting pytz-2016.6.1-py2.7.egg to /root/PokemonGo-Map-develop/build/protobuf



Installed /root/PokemonGo-Map-develop/build/protobuf/pytz-2016.6.1-py2.7.egg

Searching for python-gflags>=1.4

Reading http://pypi.python.org/simple/python-gflags/

Best match: python-gflags 3.0.5

Downloading https://pypi.python.org/packages/1f/01/3ca6527f51b7ff26abb635d4e7e2fa8413c7cf191564cc2c1e535f50dec7/python-gflags-3.0.5.tar.gz#md5=0e3a06cb99b9883bf6abacc489f31297

Processing python-gflags-3.0.5.tar.gz

Running python-gflags-3.0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oyCXxC/python-gflags-3.0.5/egg-dist-tmp-F08cKL

zip_safe flag not set; analyzing archive contents...



Installed /root/PokemonGo-Map-develop/build/protobuf/python_gflags-3.0.5-py2.7.egg

Searching for python-dateutil>=1.4

Reading http://pypi.python.org/simple/python-dateutil/

Best match: python-dateutil 2.5.3

Downloading https://pypi.python.org/packages/b7/9f/ba2b6aaf27e74df59f31b77d1927d5b037cc79a89cda604071f93d289eaf/python-dateutil-2.5.3.zip#md5=52b3f339f41986c25c3a2247e722db17

Processing python-dateutil-2.5.3.zip

Running python-dateutil-2.5.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-CgWU5u/python-dateutil-2.5.3/egg-dist-tmp-tqkU2Y

warning: no previously-included files matching '__pycache__' found anywhere in distribution

warning: no previously-included files matching '*.py[co]' found anywhere in distribution



Installed /root/PokemonGo-Map-develop/build/protobuf/python_dateutil-2.5.3-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/PokemonGo-Map-develop/build/protobuf/setup.py", line 200, in <module>

    "Protocol Buffers are Google's data interchange format.",

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve

    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (six 1.1.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.5'))

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /root/PokemonGo-Map-develop/build/protobuf
Storing complete log in /root/.pip/pip.log
```

## Your Environment

* Version used: PokemonGo-Map-develop & PokemonGo-Map-master
* Environment name and version (e.g. Python 2.7): python 2.7.3, pip
* Operating System and version (desktop or mobile): Debian 7 (Wheezy)

**Comment by jault3** [comment]
some linux distros have six installed already. you may be able to get away with just `pip install --upgrade six`

**Comment by N0916** [comment]
@jault3 Perfect, fixed everything. Thank you!
