### ISSUE TITLE
Error when installing requirements

### ISSUE THREAD

**Issue by tab0rda** [AHAAAAAAA/PokemonGo-Map#1467]
When I'm installing requirements following the guide I get the following error

`Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 271, in populate_link
    self.link = self._wheel_cache.cached_wheel(self.link, self.name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 68, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 148, in cached_wheel
    return pip.index.Link(path_to_url(path))
  File "c:\python27\lib\site-packages\pip\download.py", line 457, in path_to_url
    url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "c:\python27\lib\nturl2path.py", line 67, in pathname2url
    path = path + '/' + urllib.quote(comp)
  File "c:\python27\lib\urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe1'`

Please help

**Comment by SammyO** [comment]
Same problem here.

**Comment by tab0rda** [comment]
Found the fix. We have an invalid character in our directory. For example my username in pc is Fábio and python doesn't recognize the á. Move the folder PokemonGo-Map-develop somewhere else
