### ISSUE TITLE
I get "Command "python setup.py egg_info" failed with error code 1" when I install dependancies

### ISSUE THREAD

**Issue by daveidivide** [AHAAAAAAA/PokemonGo-Map#1475]
I'm running OSX with Python 2.7.10 and Pip 8.1.2 and get the following after I try to install dependancies:

*Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vg/x4rm_ywn1yd5zp7vgdcqx6300000gn/T/pip-build-EWKz5q/protobuf-to-dict/*

Is there anything obvious I am doing wrong?

Many thanks

**Comment by Azzinoth** [comment]
Windows 10 64-bit with Python 2.7.12. Have the same issue :(

error text :

```
D:\PokemonGo-Map-develop>"C:\Python27\Scripts\pip2.exe" install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\python27\lib\site-packages\flask-0.11.1-py2.7.egg (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\python27\lib\site-packages\jinja2-2.8-py2.7.egg (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages\markupsafe-0.23-py2.7.egg (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\python27\lib\site-packages\werkzeug-0.11.10-py2.7.egg (from -r requirements.txt (line 4))
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
  Using cached argparse-1.2.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\python27\lib\site-packages\click-6.6-py2.7.egg (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\python27\lib\site-packages\itsdangerous-0.24-py2.7.egg (from -r requirements.txt (line 7))
Collecting peewee==2.8.1 (from -r requirements.txt (line 8))
  Using cached peewee-2.8.1.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 9))
  Using cached wsgiref-0.1.2.zip
Collecting geopy==1.11.0 (from -r requirements.txt (line 10))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 11))
  Using cached protobuf-2.6.1.tar.gz
Collecting requests==2.10.0 (from -r requirements.txt (line 12))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 13))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 14))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 15))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed c:\users\fa8e~1\appdata\local\temp\pip-build-xkzkyq\protobuf-to-dict\.eggs\nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.2b1
    Downloading https://pypi.python.org/packages/78/55/753efee83e38b67006336cd774308aa3e0652b2d35be693ad955dbee899f/coverage-4.2b1.win32-py2.7.exe#md5=16619f18427a1a6d4e5ba59c8efee9c7
    Processing coverage-4.2b1.win32-py2.7.exe
    creating 'c:\users\fa8e~1\appdata\local\temp\easy_install-lnfhsj\coverage-4.2b1-py2.7-win32.egg' and adding 'c:\users\fa8e~1\appdata\local\temp\easy_install-lnfhsj\coverage-4.2b1-py2.7-win32.egg.tmp' to it
    creating c:\users\fa8e~1\appdata\local\temp\pip-build-xkzkyq\protobuf-to-dict\.eggs\coverage-4.2b1-py2.7-win32.egg
    Extracting coverage-4.2b1-py2.7-win32.egg to c:\users\fa8e~1\appdata\local\temp\pip-build-xkzkyq\protobuf-to-dict\.eggs
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\fa8e~1\appdata\local\temp\pip-build-xkzkyq\protobuf-to-dict\setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "c:\python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1104, in obtain
        return installer(requirement)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 841, in install_eggs
        return [self.install_exe(dist_filename, tmpdir)]
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 983, in install_exe
        return self.install_egg(egg_path, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 934, in install_egg
        update_dist_caches(destination, fix_zipimporter_caches=False)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 1750, in update_dist_caches
        _uncache(normalized_path, sys.path_importer_cache)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 1824, in _uncache
        _update_zipimporter_cache(normalized_path, cache)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 1806, in _update_zipimporter_cache
        for p in _collect_zipimporter_cache_entries(normalized_path, cache):
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 1785, in _collect_zipimporter_cache_entries
        if (np.startswith(normalized_path) and
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 9: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\fa8e~1\appdata\local\temp\pip-build-xkzkyq\protobuf-to-dict\
```

**Comment by eiswuerfel** [comment]
Same Issue on Arch.

**Comment by ctluciani** [comment]
Without your full stack trace this error means almost nothing, there's a few solutions that most likely will solve this problem though:

` pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))
`
is fixed by upgrading the 'six' package (this solved this problem for me on a fresh install). You can do this with the following:
` sudo -H pip install --ignore-installed six`

Azzinoth, your error will likely be fixed by upgrading python.

**Comment by horror** [comment]
have same problem. Any fix?

**Comment by Azzinoth** [comment]
> Azzinoth, your error will likely be fixed by upgrading python.
How can I do that ?) (I know it is noob question....)

**Comment by Halvo317** [comment]
`C:\Python27\scripts\pip2.7.exe install -r requirements`

**Comment by ctluciani** [comment]
> Azzinoth, your error will likely be fixed by upgrading python.
> How can I do that ?) (I know it is noob question....)

A quick google search will answer this question better than I can, as it varies depending on operating system. That is actually how I found my possible solutions ;)

**Comment by horror** [comment]
problem with name of folder c:\users\<thisUserNameFolder>. If name of this folder have non ascii characters, u got an error.

**Comment by yifeic** [comment]
`brew install python` fixed my problem on OS X El Capitan

**Comment by Acidvenom73** [comment]
For me this was solved by installing VCForPython27.msi, worked for 2 other people I helped aswell. OS is windows.

**Comment by kevinyuliawan** [comment]
Also on El Capitan, what fixed it for me was using virtualenv for installing the requirements and running the server. Trying to upgrade six didn't work for me since it looks like it tries to upgrade the system-created 'six' which OSX wants to protect against. Here's a guide on using virtualenv: http://docs.python-guide.org/en/latest/dev/virtualenvs/#virtualenvironments-ref

Essentially, you run:

```
$ sudo pip install virtualenv
$ cd my_project_folder
$ virtualenv venv
$ source venv/bin/activate
$ pip install -r requirements.txt
$ python runserver.py -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]"
```

And then to stop the server, you can press Ctrl+C, but note that you'd still be in `venv`, so then you need to type `deactivate` to exit `venv`.

**Comment by shaosh** [comment]
This issue is very tricky and took me 2 hours to solve. This is the error message I saw.

 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0lQg4T/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 348, in __init__
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 394, in fetch_build_eggs
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 826, in resolve
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1085, in best_match
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 695, in find
    pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0lQg4T/protobuf-to-dict/

It seems to be a issue related to protobuf-to-dict, but actually a version conflict of six. 

The final solution is to uninstall the six by 

         pip uninstall six

And then run the 
    
        pip install -r requirements.txt 

it will install everything without any errors.

My system is ubuntu from AWS. Before figuring out this solution, I upgrade the python to 2.7.12 and upgrade pip to 8.1.2, but none of them works. 

Hope my answer can help someone.

**Comment by slin1202** [comment]
That worked for me shaosh, thanks for figuring it out.

**Comment by pgoparttime** [comment]
Win 10, had same issue with 7/29 dev branch.  fixed by installing Visual C++ compiler for Python 2.7  found [here](https://www.microsoft.com/en-us/download/details.aspx?id=44266)

**Comment by oynek** [comment]
If I try to uninstall six by this command i always get the following message:

> Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS

Any suggestions?

**Comment by saiyan86** [comment]
try this
'sudo pip install --ignore-installed six'
'pip install -r requirements.txt '

**Comment by hamxyy** [comment]
'sudo pip install --ignore-installed six'
'pip install -r requirements.txt '
works.

Thanks to saiyan86.
