### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#1487]
When im running multiply instances i get this error:

Exception in thread search_step_thread 66:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/PokemonGo-Map-develop/pogom/search.py", line 115, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "/root/PokemonGo-Map-develop/pogom/models.py", line 161, in parse_map
    bulk_upsert(Pokemon, pokemons)
  File "/root/PokemonGo-Map-develop/pogom/models.py", line 187, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked

Is there any solution yet or possible to be improved soon?

**Comment by andrewda** [comment]
#1319
