### ISSUE TITLE
Crashed, waiting 1 seconds before restarting 

### ISSUE THREAD

**Issue by loretoparisi** [AHAAAAAAA/PokemonGo-Map#1497]
This happens after the last project refactoring running `runserver.py`, not sure what's going on, but running the previous `example.py` it worked with same parameters and credentials.

```
2016-07-23 13:02:38,829 [  runserver] [   INFO] Parsed location is: 44.4944/11.3427/0.0000 (lat/lng/alt)
2016-07-23 13:02:38,830 [     search] [   INFO] Map iteration: 0
2016-07-23 13:02:38,830 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-23 13:02:38,830 [     search] [   INFO] Crashed, waiting 1 seconds before restarting search.
2016-07-23 13:02:39,834 [     search] [   INFO] Map iteration: 0
2016-07-23 13:02:39,834 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-23 13:02:39,834 [     search] [   INFO] Crashed, waiting 1 seconds before restarting search.
2016-07-23 13:02:40,839 [     search] [   INFO] Map iteration: 0
2016-07-23 13:02:40,839 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-23 13:02:40,840 [     search] [   INFO] Crashed, waiting 1 seconds before restarting search.
2016-07-23 13:02:41,845 [     search] [   INFO] Map iteration: 0
2016-07-23 13:02:41,845 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-23 13:02:41,845 [     search] [   INFO] Crashed, waiting 1 seconds before restarting search.
2016-07-23 13:02:42,849 [     search] [   INFO] Map iteration: 0
2016-07-23 13:02:42,849 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-23 13:02:42,849 [     search] [   INFO] Crashed, waiting 1 seconds before restarting search.
2016-07-23 13:02:43,855 [     search] [   INFO] Map iteration: 0
```

**Comment by Sejadis** [comment]
in pogom/search.py  remove /comment out the last part
`This seems appropriate
    except Exception as e:
        log.info('Crashed, waiting {:d} seconds before restarting search.'.format(args.scan_delay))
        time.sleep(args.scan_delay)
        search_loop(args)`

and post the actual error message

**Comment by loretoparisi** [comment]
I have added a `traceback` 

```python
import traceback
print traceback.format_exc()
```

```shell
2016-07-23 14:28:42,436 [     search] [   INFO] Map iteration: 0
2016-07-23 14:28:42,436 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-23 14:28:42,436 [     search] [   INFO] Crashed, waiting 1 seconds before restarting search.
Traceback (most recent call last):
  File "/PokemonGo-Map-master/pogom/search.py", line 185, in search_loop
    search(args, i)
  File "s/PokemonGo-Map-master/pogom/search.py", line 152, in search
    login(args, position)
  File "/PokemonGo-Map-master/pogom/search.py", line 95, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "/PokemonGo-Map-master/pogom/pgoapi/pgoapi.py", line 140, in login
    raise AuthException("Invalid authentication provider - only ptc/google available.")
AuthException: Invalid authentication provider - only ptc/google available.
```

so it is

`AuthException: Invalid authentication provider - only ptc/google available.`


but I have tried both `-a "google"` and `-a google`. Any hint?

**Comment by smallcinic** [comment]
As a fastfix in file pogom/pgoapi/pgoapi.py I change line 140 from this:
`raise AuthException("Invalid authentication provider - only ptc/google available.")`
to this:
`self._auth_provider = AuthPtc()`
And if you want use Google for auth you may change it for this:
`self._auth_provider = AuthGoogle()`

It is not a fix, just temporary solution.

**Comment by loretoparisi** [comment]
@smallcinic yes this works, very strange it fails to parse the `-a` parameter in some way.

**Comment by Sejadis** [comment]
could you tell us what command you run? i guess its messed up at another place

**Comment by loretoparisi** [comment]
`python runserver.py -a "google" -u "xxxxxx@gmail.com" -p "xxxxxx" -st 10 -l "Bologna, Piazza del Nettuno" -ar -st 10 -H localhost -P 5001 -k xxxxxxx`

**Comment by Sejadis** [comment]
remove the -ar its not needed anymore and its the flag thats messing it up

**Comment by smallcinic** [comment]
@Sejadis 
Without -ar flag it works fine.
Thank you!

**Comment by loretoparisi** [comment]
@Sejadis hahaha so `-ar` was parsed as `-a null` or `-a r` 👊
