### ISSUE TITLE
BUG: IntegrityError: NOT NULL constraint failed: pokemon.detect_time

### ISSUE THREAD

**Issue by darcycartwright** [AHAAAAAAA/PokemonGo-Map#1513]
Currently experiencing an IntegrityError when attempting to load the current master.

The previous fix of: delete pogo.db obviously won't work anymore.

## Expected Behaviour
Pokemon from scan should be displayed on map.

## Current Behaviour
Pokemon unable to be passed to map due to Integrity Error

## Steps to Reproduce (for bugs)
1. Download current master.
2. Run
3. Scan for Pokemon (yay)
4. IntegrityError

## Context
Map loads (yay)
Gyms load (kind of yay)
Pokestops don't load (no real worry)
Pokemon don't load (BOO!)

## Your Environment
* Version used: Master
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): OS X

**Comment by darcycartwright** [comment]
```
2016-07-23 22:30:21,694 [  runserver] [   INFO] Parsed location is: -35.3075/149.1244/0.0000 (lat/lng/alt)
2016-07-23 22:30:21,695 [     search] [   INFO] Map iteration: 0
2016-07-23 22:30:21,695 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-23 22:30:21,696 [   auth_ptc] [   INFO] PTC login for: *****
2016-07-23 22:30:24,975 [   auth_ptc] [   INFO] PTC Login successful
2016-07-23 22:30:25,574 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-23 22:30:25,574 [     search] [   INFO] Scanning step 1 of 61 started.
2016-07-23 22:30:25,577 [     search] [   INFO] Scanning step 2 of 61 started.
2016-07-23 22:30:26,244 [     models] [   INFO] Upserting 4 pokemon
Exception in thread search_step_thread 1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/darcycartwright/Development/Python/PokemapGO/pogom/search.py", line 115, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "/Users/darcycartwright/Development/Python/PokemapGO/pogom/models.py", line 164, in parse_map
    bulk_upsert(Pokemon, pokemons)
  File "/Users/darcycartwright/Development/Python/PokemapGO/pogom/models.py", line 190, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: pokemon.detect_time
```

**Comment by eelkefierstra** [comment]
Had same problem on develop.
Fixed it by manually deleting pogom.db

Hope this fixes it for you too.

**Comment by philals** [comment]
Deleting pogom.db fixes same issue for me

**Comment by darcycartwright** [comment]
So the issue is, if you run it as a subprocess it doesn't create the pogom.db file at all.
