### ISSUE TITLE
Peewee OperationalError: Unable to open database file (on Termux Android)

### ISSUE THREAD

**Issue by ArionMiles** [AHAAAAAAA/PokemonGo-Map#1533]
## Expected Behavior

I'm Trying to run this script on my Android 5.1 phone. The previous stable release worked fine. But peewee is giving me this error in the dev build and the latest stable release. The newest stable release and the dev build works completely fine on my computer, though.

## Current Behavior

I get this output:

`$ python2 runserver.py -a ptc -u **** -p ***** -l "<lat> <long>" -st 20
Traceback (most recent call last):
  File "runserver.py", line 47, in <module>
    create_tables()
  File "/data/data/com.termux/files/home/storage/pogo2/pogom/models.py", line 196, in create_tables
    db.connect()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/peewee.py", line 3316, in _exit_
    reraise(new_type, new_type(*exc_args), traceback)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/peewee.py", line 3658, in _connect
    conn = sqlite3.connect(database, **kwargs)
peewee.OperationalError: unable to open database file`

## Your Environment

* Version used: Latest
* Environment name and version (e.g. Python 2.7): Python 2.7 on Termux
* Operating System and version (desktop or mobile): Android 5.1 Lollipop

**Comment by ArionMiles** [comment]
The issue was with the read/write permissions for the folder. Once I made it 777 (in android terms) , it works like a charm. Peewee wasn't able to open a db in the directory because it had no read/write access.
