### ISSUE TITLE
After Website refresh  all Pokemons disappear from the map.

### ISSUE THREAD

**Issue by vinsilsim** [AHAAAAAAA/PokemonGo-Map#1551]
When I refresh the website get this error on the console:
After that all Pokemons disappear from the map.

latest version: Develop branch

OS: Windows Server 2012 R2

Database: mysql

Run Command: runserver.py -a ptc -u ***** -p ***** -l "Santa Monica Pier, Estados Unidos" -st 10 

-H 0.0.0.0 -P 80

2016-07-23 15:36:03,927 [     search] [   INFO] Scanning step 60 of 271 started.

Exception in thread Thread-107:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 654, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 283, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine

**Comment by FallenArchangel** [comment]
Try using a port other than 80.  Other than that, check your firewalls.
Those are the main things I've seen that cause that issue.  Although usually when that happens it won't let you connect at all, not even to an empty map.   Still worth a short.
