### ISSUE TITLE
AttributeError: 'module' object has no attribute 'is_running_from_reloader'

### ISSUE THREAD

**Issue by loretoparisi** [AHAAAAAAA/PokemonGo-Map#162]
I get this error after installing all dependencies

```
macbookproloreto:PokemonGo-Map admin$ python example.py -a "google" -u "xxxxx" -p "xxxxx" -l "New York, Central Park" -st 10 -H localhost -P 9999 -d
[-] register_background_thread called
Traceback (most recent call last):
  File "example.py", line 644, in <module>
    register_background_thread(initial_registration=True)
  File "example.py", line 555, in register_background_thread
    if not werkzeug.serving.is_running_from_reloader():
AttributeError: 'module' object has no attribute 'is_running_from_reloader'
```

I have 
```
macbookproloreto:PokemonGo-Map admin$ python --version
Python 2.7.10
macbookproloreto:PokemonGo-Map admin$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
```

**Comment by AHAAAAAAA** [comment]
PR #155 fixes this, will be merged soon!

**Comment by loretoparisi** [comment]
💯

**Comment by DerScreever** [comment]
merged

**Comment by loretoparisi** [comment]
👍

**Comment by andreyoshev** [comment]
Merged?

**Comment by mkody** [comment]
@andreyoshev Yes, the missing dependency has been added with a merge request: ac17d1606d19918556f5552f1bfdd5fc88e3a12c
