### ISSUE TITLE
Broken pipe error. Can't load externally

### ISSUE THREAD

**Issue by coffman34** [AHAAAAAAA/PokemonGo-Map#1711]
## Expected Behavior
Users should be able to load the site externally.

## Current Behavior
When browsing the site takes forever to load, and when it does it produces this. 

https://cdn.discordapp.com/attachments/206339978555293696/206578828997296129/Screenshot_20160723-211006.png

Output shows:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

## Your Environment

* Version used: master
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Fresh Ubuntu 16.04.1 LTS

**Comment by hhu94** [comment]
We're going to need more context to be able to reproduce this.

**Comment by coffman34** [comment]
I'm not sure what context you need.

It's a fresh Ubuntu server install.

Installed Python and Pip

Installed requirements.txt

Ran server.

Can view locally just fine.

When viewing externally it produces the bug above.

**Comment by coffman34** [comment]
This may be related to a port forwarding issue.

I am unable to access my server from anything externally. SSH, FTP, anything.
