### ISSUE TITLE
ImportError: No module named commands.install  (PIP Install error)

### ISSUE THREAD

**Issue by OkieAsh** [AHAAAAAAA/PokemonGo-Map#1737]
## Expected Behavior
 
Pip will not install

## Current Behavior

I have C:\Users\Ashley\Desktop\POKE\PokemonGo-Map-master>"C:\Python27\Scripts\pip2.7.exe" install -r requirements.txt entered into the cmd prompt window.  

It runs and gives me the following information with an install error at the end... 
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pip2.7.exe\__main__.py", line 9, in <module>
  File "c:\python27\pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "c:\python27\pip.py", line 83, in bootstrap
    from pip.commands.install import InstallCommand
ImportError: No module named commands.install     

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 10 Home

**Comment by Kryakz** [comment]
can you not just say 
`pip install -r requirements.txt`

**Comment by Kryakz** [comment]
try adding C:\Python27\Scripts\ to PATH in environment variables?
