### ISSUE TITLE
pip install -r requirements.txt FAIL

### ISSUE THREAD

**Issue by gregtampa** [AHAAAAAAA/PokemonGo-Map#1773]
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 980, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 216, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 255, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1

**Comment by medghaim** [comment]
Closing, not an issue.

For support: https://discord.gg/2wwnH

**Comment by fari-99** [comment]
@medghaim what's that? i still can't install it because of that. thanks before.
