### ISSUE TITLE
AttributeError: 'module' object has no attribute 'dot'

### ISSUE THREAD

**Issue by mcmaxl** [AHAAAAAAA/PokemonGo-Map#179]
```
root@BlackBox:/# python /opt/pokemon-go-map/example.py -u ****** -p ***** -l "48.158380, 11.508975" -st 10 -i "Pidgey, Rattata, Spearow, Weedle, Caterpie" -H 192.168.100.10 -P 5010
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://192.168.100.10:5010/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[+] Locale is en
 * Debugger is active!
[!] lat/long/alt: 48.15838 11.508975 0
[!] PTC login for: ******
 * Debugger pin code: 279-678-790
[+] RPC Session Token: TGT-35655-ch4Gwaa3tTrnFPi ...
91.52.18.38 - - [18/Jul/2016 23:48:57] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pokemon-go-map/example.py", line 708, in fullmap
    'icon': icons.dot.red,
AttributeError: 'module' object has no attribute 'dot'
```

**Comment by CarlTaylor1989** [comment]
Update to latest changes.

**Comment by mcmaxl** [comment]
apologies! development almost too fast to keep up with!

**Comment by DerScreever** [comment]
we are a good team :dancers:
