### ISSUE TITLE
Errors when running pip install -r requirements.txt

### ISSUE THREAD

**Issue by Skyrid3r** [AHAAAAAAA/PokemonGo-Map#1803]
Getting:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

---

When trying to install it on debian (Pi2) with Python 2.7.9. Stable build from yesterday (with example.py) worked perfectly. Now the stable builds includes runserver.py (so you know what build I mean that no longer has the example.py) which I am unable to install.

**Comment by Skyrid3r** [comment]
***FIXED***

Please include in the wiki that debian pip: v1.5.6
https://packages.debian.org/jessie/python-pip

is outdated, and will not work with the current pokemongo-map.

It has to be updated.
