### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2642

### ISSUE THREAD

**Issue by tj1627** [AHAAAAAAA/PokemonGo-Map#185]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 10 Professional x64

Installed version of Python:
2.7.12

### Steps to reproduce
1.C:\Users\User\Documents\GitHub\PokemonGo-Map\example.py -a ptc -u userName -p passWord -l "41.8917111,-87.6035756" -st 10
2. open localhost:5000
3. refresh once pokemon are loaded (~step 10-15 or so)

### What have you tried?
1. pulled current version down, no change

### Logs or other output that would be helpful

127.0.0.1 - - [18/Jul/2016 17:21:28] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Tim\Documents\GitHub\PokemonGo-Map\example.py", line 696, in fullmap
    clear_stale_pokemons()
  File "C:\Users\Tim\Documents\GitHub\PokemonGo-Map\example.py", line 648, in clear_stale_pokemons
    print "[+] removing stale pokemon %s at %f, %f from list" % (pokemon['name'], pokemon['lat'], pokemon['lng'])
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2642' in position 34: character maps to <undefined>
127.0.0.1 - - [18/Jul/2016 17:21:28] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Jul/2016 17:21:28] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Jul/2016 17:21:28] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Jul/2016 17:21:29] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [18/Jul/2016 17:21:29] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [18/Jul/2016 17:21:29] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[+] Locale is en
[!] lat/long/alt: 41.8917111 -87.6035756 0
[+] RPC Session Token: TGT-30455-p7da2C2nyvencJH ...
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/233/rpc
[+] Login successful
[+] Username: tmcdonnell
[+] You started playing Pokemon Go on: 2016-07-17 18:00:00
[+] POKECOIN: 0
[+] STARDUST: 0
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\Tim\Documents\GitHub\PokemonGo-Map\example.py", line 536, in main
    clear_stale_pokemons()
  File "C:\Users\Tim\Documents\GitHub\PokemonGo-Map\example.py", line 648, in clear_stale_pokemons
    print "[+] removing stale pokemon %s at %f, %f from list" % (pokemon['name'], pokemon['lat'], pokemon['lng'])
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2642' in position 34: character maps to <undefined

**Comment by RubenGM** [comment]
That happens when a Nidoran is removed. This fixed it for me:

diff --git a/example.py b/example.py
index 646c48e..636a6e1 100644
--- a/example.py
+++ b/example.py
@@ -645,7 +645,7 @@ def clear_stale_pokemons():
     for pokemon_key in pokemons.keys():
         pokemon = pokemons[pokemon_key]
         if current_time > pokemon['disappear_time']:
-            print "[+] removing stale pokemon %s at %f, %f from list" % (pokemon['name'], pokemon['lat'], pokemon['lng'])
+            print "[+] removing stale pokemon %s at %f, %f from list" % (pokemon['name'].encode('utf-8'), pokemon['lat'], pokemon['lng'])
             del pokemons[pokemon_key]
 
 def register_background_thread(initial_registration=False):

**Comment by Seqvek** [comment]
Where to i paste that in to? ;/  @RubenGM

**Comment by JZ6** [comment]
fixed
