### ISSUE TITLE
Could not find a version that satisfies

### ISSUE THREAD

**Issue by paperc07** [AHAAAAAAA/PokemonGo-Map#1880]
Could not find a version that satisfies the requirement requirements.txt (from
 versions: )
No matching distribution found for requirements.txt

**Comment by adrianocr** [comment]
Can you please provide the entire error text? What you posted doesn't mean much. We understand there's an error but we need more info to figure out why.

**Comment by Sejadis** [comment]
you probably forgot the -r in pip install -r requirements

**Comment by paperc07** [comment]
C:\Users\FRU5TRAT3\Desktop\PokemonGo-Map.git\trunk>pip install -r requirements
Could not open requirements file: [Errno 2] No such file or directory: 'requirem
ents'

C:\Users\FRU5TRAT3\Desktop\PokemonGo-Map.git\trunk>pip install -r requirements.t
xt
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\py
thon27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\pyth
on27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:
\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c
:\python27\lib\site-packages (from -r requirements.txt (line 4))
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Na
me Indication) extension to TLS is not available on this platform. This may caus
e the server to present an incorrect TLS certificate, which can cause validation
 failures. You can upgrade to a newer version of Python to solve this. For more
information, see https://urllib3.readthedocs.org/en/latest/security.html#snimiss
ingwarning.
  SNIMissingWarning
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:122: InsecurePlatformWarning: A true SSLContext object is not available. This p
revents urllib3 from configuring SSL appropriately and may cause certain SSL con
nections to fail. You can upgrade to a newer version of Python to solve this. Fo
r more information, see https://urllib3.readthedocs.org/en/latest/security.html#
insecureplatformwarning.
  InsecurePlatformWarning
  Using cached argparse-1.2.1.tar.gz
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run

    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_
files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 601, in _prepare
_file
    abstract_dist.prep_for_dist()
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 127, in prep_for
_dist
    self.req_to_install.run_egg_info()
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 397, in run_
egg_info
    self.setup_py, self.name,
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 372, in setu
p_py
    import setuptools  # noqa
  File "c:\python27\lib\site-packages\setuptools\__init__.py", line 14, in <modu
le>
    from setuptools.extension import Extension
  File "c:\python27\lib\site-packages\setuptools\extension.py", line 11, in <mod
ule>
    from . import msvc
  File "c:\python27\lib\site-packages\setuptools\msvc.py", line 28, in <module>
    import distutils.msvc9compiler as msvc9compiler
  File "c:\python27\lib\distutils\msvc9compiler.py", line 647
    ld_args.append('/MANIFESTFILE:' + temp_manifest)
   ^
IndentationError: unexpected indent

C:\Users\FRU5TRAT3\Desktop\PokemonGo-Map.git\trunk>

**Comment by paperc07** [comment]
still same error

Traceback (most recent call last):
  File "C:\Users\FRU5TRAT3\Desktop\PokemonGo-Map.git\trunk\runserver.py", line 1
0, in <module>
    from flask_cors import CORS, cross_origin
ImportError: No module named flask_cors

C:\Users\FRU5TRAT3\Desktop\PokemonGo-Map.git\trunk>

**Comment by paperc07** [comment]
I got it to work thanks so much guys for all your continued help and support,

I got sick of python always throwing me errors and saying "Insecure platform warning" so I uninstalled everything, reinstalled everything fresh. Python 2.7.12, get pip, and then just ran the requirements and everything is working flawlessly. Thanks again guys!!!

**Comment by ivanmayes** [comment]
adding -r worked for me, but just wanted to point out that there is no -r in the Mac OSX instructions currently.
