### ISSUE TITLE
Deadlock when upsert

### ISSUE THREAD

**Issue by jangrewe** [AHAAAAAAA/PokemonGo-Map#1889]
Running the latest commit from #1821 , one of my workers threw this:
```
24.7.2016 22:18:192016-07-24 20:18:19,530 [     search] [   INFO] Search queue depth is: 100
24.7.2016 22:18:192016-07-24 20:18:19,875 [     models] [   INFO] Upserting 103 pokestops
24.7.2016 22:18:192016-07-24 20:18:19,889 [     models] [   INFO] Upserting 6 gyms
24.7.2016 22:18:202016-07-24 20:18:20,892 [     search] [   INFO] Search queue depth is: 99
24.7.2016 22:18:212016-07-24 20:18:21,308 [     models] [   INFO] Upserting 65 pokestops
24.7.2016 22:18:21Exception in thread search_thread 0:
24.7.2016 22:18:21Traceback (most recent call last):
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
24.7.2016 22:18:21    self.run()
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/threading.py", line 754, in run
24.7.2016 22:18:21    self.__target(*self.__args, **self.__kwargs)
24.7.2016 22:18:21  File "/opt/pogom/search.py", line 124, in search_thread
24.7.2016 22:18:21    parse_map(response_dict, i, step, step_location)
24.7.2016 22:18:21  File "/opt/pogom/models.py", line 278, in parse_map
24.7.2016 22:18:21    bulk_upsert(Pokestop, pokestops)
24.7.2016 22:18:21  File "/opt/pogom/models.py", line 301, in bulk_upsert
24.7.2016 22:18:21    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3244, in execute
24.7.2016 22:18:21    cursor = self._execute()
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
24.7.2016 22:18:21    return self.database.execute_sql(sql, params, self.require_commit)
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
24.7.2016 22:18:21    self.commit()
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
24.7.2016 22:18:21    reraise(new_type, new_type(*exc_args), traceback)
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
24.7.2016 22:18:21    cursor.execute(sql, params or ())
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 161, in execute
24.7.2016 22:18:21    result = self._query(query)
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 317, in _query
24.7.2016 22:18:21    conn.query(q)
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 837, in query
24.7.2016 22:18:21    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1021, in _read_query_result
24.7.2016 22:18:21    result.read()
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1304, in read
24.7.2016 22:18:21    first_packet = self.connection._read_packet()
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 983, in _read_packet
24.7.2016 22:18:21    packet.check_error()
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 395, in check_error
24.7.2016 22:18:21    err.raise_mysql_exception(self._data)
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
24.7.2016 22:18:21    _check_mysql_exception(errinfo)
24.7.2016 22:18:21  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
24.7.2016 22:18:21    raise InternalError(errno, errorvalue)
24.7.2016 22:18:21InternalError: (1213, u'Deadlock found when trying to get lock; try restarting transaction')
24.7.2016 22:18:21
```
FYI: the worker didn't recover from this state.

**Comment by Pedrock** [comment]
In models.py, function bulk_upsert, try changing step = 120 to step = 1

**Comment by Pedrock** [comment]
I haven't tested this with mysql, but I had this problem with my postgresql implementation and this fixed it.

**Comment by NenadJAustralia** [comment]
Trying the steps to 1 instead of 120, Will report back.

Could this be a MySQL issue? Like when people were having issues launching multiple instances because they were on a shared box and it was limited to 10?

**Comment by GareRam** [comment]
Had the same issue, changing the steps to 1 seems to work.

I'll report back after a couple of hours with ±15 workers running.

**Comment by NenadJAustralia** [comment]
@GareRam 

How is it going so far? Mine usually crash about 30 min in.

**Comment by GareRam** [comment]
At this point, still going strong, no deadlocks in any of the 15 threads. Running for 45 mins now.

**Comment by GareRam** [comment]
Apart from current PTC issues, this works like a charm :)
