### ISSUE TITLE
global name 'APP' is not defined

### ISSUE THREAD

**Issue by hugoerg56** [AHAAAAAAA/PokemonGo-Map#191]
`Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 545, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 484, in login
    access_token = get_token(args.auth_service, args.username, args.password)
  File "example.py", line 420, in get_token
    global_token = login_google(username, password)
  File "example.py", line 314, in login_google
    APP,
`

**Comment by Orrielel** [comment]
#188 fixes this

**Comment by sykhro** [comment]
Fixed with latest commit
