### ISSUE TITLE
Wrong username/password

### ISSUE THREAD

**Issue by hugoerg56** [AHAAAAAAA/PokemonGo-Map#194]
Im using the email and password for the google account I use to play? any idea

`Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 545, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 486, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password`

**Comment by hugoerg56** [comment]
Works... maybe login server problem...
