### ISSUE TITLE
"Database is locked" Error

### ISSUE THREAD

**Issue by craywong** [AHAAAAAAA/PokemonGo-Map#1945]
Running with 75 threads at step size 20. Worked for a while, then got this error:

2016-07-25 05:48:44,949 [     models] [   INFO] Upserting 16 pokestops
[2016-07-25 05:48:45,020] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/PokemonGo-Map/pogom/app.py", line 56, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "/home/ec2-user/PokemonGo-Map/pogom/models.py", line 87, in get_active
    for p in query:
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-07-25 05:48:45,020 [        app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/PokemonGo-Map/pogom/app.py", line 56, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "/home/ec2-user/PokemonGo-Map/pogom/models.py", line 87, in get_active
    for p in query:
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-07-25 05:48:45,159 [     models] [   INFO] Upserting 3 gyms

**Comment by andrewda** [comment]
This has been reported numerous times. Please use the search.
