### ISSUE TITLE
UnboundLocalError: local variable 'poke' referenced before assignment

### ISSUE THREAD

**Issue by hugoerg56** [AHAAAAAAA/PokemonGo-Map#196]
`[-] looping: step 0 of 4
Completed: 0.0%
[-] looping: step 1 of 4
Completed: 25.0%
[-] looping: step 2 of 4
Exception in thread search_thread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 575, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 639, in process_step
    disappear_timestamp = time.time() + poke.TimeTillHiddenMs \
UnboundLocalError: local variable 'poke' referenced before assignment
`

**Comment by michi0987** [comment]
It has been already reported.

**Comment by Vivicus** [comment]
And fixed in #190 .

**Comment by DerScreever** [comment]
fixed
