### ISSUE TITLE
UnicodeDecodeError when trying to install requirements.txt

### ISSUE THREAD

**Issue by helsyQ** [AHAAAAAAA/PokemonGo-Map#1969]
When im trying to install requirements.txt to run pokemongo-map, im getting this error.

```
C:\Program Files (x86)\PokemonGo-Map-develop>pip install protobuf-to-dict
Collecting protobuf-to-dict
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed c:\users\0808~1\appdata\local\temp\pip-build-bgmbmt\protobuf-to-di
ct\.eggs\nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.2b1
    Downloading https://pypi.python.org/packages/a6/2f/efd55406ac51b1e8212f63e6e
840ceb2501fee0e438655abc2791b45dc4c/coverage-4.2b1.win-amd64-py2.7.exe#md5=c81f2
d34ece8aec545dd7a00dbe313d4
    Processing coverage-4.2b1.win-amd64-py2.7.exe
    creating 'c:\users\0808~1\appdata\local\temp\easy_install-etqcm4\coverage-4.
2b1-py2.7-win-amd64.egg' and adding 'c:\users\0808~1\appdata\local\temp\easy_ins
tall-etqcm4\coverage-4.2b1-py2.7-win-amd64.egg.tmp' to it
    creating c:\users\0808~1\appdata\local\temp\pip-build-bgmbmt\protobuf-to-dic
t\.eggs\coverage-4.2b1-py2.7-win-amd64.egg
    Extracting coverage-4.2b1-py2.7-win-amd64.egg to c:\users\0808~1\appdata\loc
al\temp\pip-build-bgmbmt\protobuf-to-dict\.eggs
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\0808~1\appdata\local\temp\pip-build-bgmbmt\protobuf-to-dict
\setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "c:\python27\lib\distutils\core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 348, in __in
it__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 394, in fetc
h_build_eggs
        replace_conflicting=True,
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 826,
in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1092,
 in best_match
        return self.obtain(req, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1104,
 in obtain
        return installer(requirement)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 461, in fetc
h_build_egg
        return cmd.easy_install(req)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 664, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 694, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 840, in install_eggs
        return [self.install_exe(dist_filename, tmpdir)]
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 982, in install_exe
        return self.install_egg(egg_path, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 933, in install_egg
        update_dist_caches(destination, fix_zipimporter_caches=False)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1749, in update_dist_caches
        _uncache(normalized_path, sys.path_importer_cache)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1823, in _uncache
        _update_zipimporter_cache(normalized_path, cache)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1805, in _update_zipimporter_cache
        for p in _collect_zipimporter_cache_entries(normalized_path, cache):
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1784, in _collect_zipimporter_cache_entries
        if (np.startswith(normalized_path) and
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordi
nal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\0808~1\a
ppdata\local\temp\pip-build-bgmbmt\protobuf-to-dict\
```
Other modules from requirements txt were installed successfully. Cant install only protobuf-to-dict.
Many thanks

**Comment by andrewda** [comment]
Please use the [discord](https://discord.gg/Vcz6S) to ask for help. This issues tracker should be exclusively for issues.
