### ISSUE TITLE
Db gets locked after a while

### ISSUE THREAD

**Issue by kazyka** [AHAAAAAAA/PokemonGo-Map#1993]
`2016-07-25 14:28:24,628 [     models] [   INFO] Upserting 5 gyms
2016-07-25 14:28:25,898 [     models] [   INFO] Upserting 1 pokemon
[2016-07-25 14:28:26,196] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mirza/github/GoMap/PokemonGo-Map (5th copy)/pogom/app.py", line 34, in raw_data
    d['pokemons'] = Pokemon.get_active()
  File "/home/mirza/github/GoMap/PokemonGo-Map (5th copy)/pogom/models.py", line 52, in get_active
    for p in query:
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-07-25 14:28:26,196 [        app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mirza/github/GoMap/PokemonGo-Map (5th copy)/pogom/app.py", line 34, in raw_data
    d['pokemons'] = Pokemon.get_active()
  File "/home/mirza/github/GoMap/PokemonGo-Map (5th copy)/pogom/models.py", line 52, in get_active
    for p in query:
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-07-25 14:28:26,438 [     models] [   INFO] Upserting 17 pokestops`

**Comment by npexte** [comment]
That's because you're running many instances and your database can't keep up with it.
There are 2 solutions as of now:
1) Comment out the pursing process for PokeStops, Gyms. You can also comment out ScannedLocations as they also take a toll on your database.
2) Use MySQL instead of SQLite. There's a merged pull (https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1223).

Number 2 is much better and actually improves your server

**Comment by medghaim** [comment]
Known issue, closing as duplicate.
