### ISSUE TITLE
getting DB error  "peewee.DatabaseError: database disk image is malformed"

### ISSUE THREAD

**Issue by kuldeeppatel123** [AHAAAAAAA/PokemonGo-Map#2049]
getting DB error 

## Expected Behavior
run the server 
## Current Behavior
Traceback (most recent call last):
  File "runserver.py", line 52, in <module>
    create_tables(db)
  File "/poke/PokemonGo-Map/pogom/models.py", line 325, in create_tables
    db.create_tables([Pokemon, Pokestop, Gym, ScannedLocation], safe=True)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3574, in create_tables
    create_model_tables(models, fail_silently=safe)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4940, in create_model_tables
    m.create_table(**create_table_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4615, in create_table
    if fail_silently and cls.table_exists():
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4611, in table_exists
    return cls._meta.db_table in cls._meta.database.get_tables(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3689, in get_tables
    'type = ? ORDER BY name;', ('table',))
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
peewee.DatabaseError: database disk image is malformed

## Steps to Reproduce (for bugs)
running with python runserver.py -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]"
on develop branch with latest commit pulled

## Your Environment
python 2.7
with ubuntu 12.4

**Comment by BlazeMuisNL** [comment]
Try removing the folder and download the latest build. This error usually means that there is a caching/writing/reading issue.

**Comment by Sejadis** [comment]
deleting the old  db seems to be a good idea in many cases when errors occur after getting a new build :D

**Comment by rlyons20** [comment]
how exactly do you do that?!?!
