### ISSUE TITLE
Problem Installing Module protobuf_to_dict

### ISSUE THREAD

**Issue by paddelx3** [AHAAAAAAA/PokemonGo-Map#2072]
```
F:\Pokemon GO\Map>pip install -r requirements.txt --no-cache
Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |################################| 81kB 521kB/s
Collecting Jinja2==2.8 (from -r requirements.txt (line 2))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |################################| 266kB 1.6MB/s
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Downloading MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 4))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |################################| 307kB 154kB/s
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
  Downloading argparse-1.2.1.tar.gz (69kB)
    100% |################################| 71kB 169kB/s
Collecting click==6.6 (from -r requirements.txt (line 6))
  Downloading click-6.6.tar.gz (283kB)
    100% |################################| 286kB 687kB/s
Collecting itsdangerous==0.24 (from -r requirements.txt (line 7))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |################################| 51kB 1.1MB/s
Collecting peewee==2.8.1 (from -r requirements.txt (line 8))
  Downloading peewee-2.8.1.tar.gz (474kB)
    100% |################################| 481kB 483kB/s
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 9))
  Downloading wsgiref-0.1.2.zip
Collecting geopy==1.11.0 (from -r requirements.txt (line 10))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 1.1MB/s
Collecting protobuf==2.6.1 (from -r requirements.txt (line 11))
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |################################| 194kB 731kB/s
Collecting requests==2.10.0 (from -r requirements.txt (line 12))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |################################| 512kB 656kB/s
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 13))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 14))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 15))
  Downloading protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed c:\users\patric~1\appdata\local\temp\pip-build-xxkjto\protobuf-to-dict\.eggs\nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.2b1
    Downloading https://pypi.python.org/packages/a6/2f/efd55406ac51b1e8212f63e6e840ceb2501fee0e438655abc2791b45dc4c/coverage-4.2b1.win-amd64-py2.7.exe#md5=c81f2d34ece8aec545dd7a00dbe313d4
    Processing coverage-4.2b1.win-amd64-py2.7.exe
    creating 'c:\users\patric~1\appdata\local\temp\easy_install-fjijxq\coverage-4.2b1-py2.7-win-amd64.egg' and adding 'c:\users\patric~1\appdata\local\temp\easy_install-fjijxq\coverage-4.2b1-py2.7-win-amd64.egg.tmp' to it
    creating c:\users\patric~1\appdata\local\temp\pip-build-xxkjto\protobuf-to-dict\.eggs\coverage-4.2b1-py2.7-win-amd64.egg
    Extracting coverage-4.2b1-py2.7-win-amd64.egg to c:\users\patric~1\appdata\local\temp\pip-build-xxkjto\protobuf-to-dict\.eggs
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\patric~1\appdata\local\temp\pip-build-xxkjto\protobuf-to-dict\setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "c:\python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1104, in obtain
        return installer(requirement)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 640, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 670, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 815, in install_eggs
        return [self.install_exe(dist_filename, tmpdir)]
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 946, in install_exe
        return self.install_egg(egg_path, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 897, in install_egg
        update_dist_caches(destination, fix_zipimporter_caches=False)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 1701, in update_dist_caches
        _uncache(normalized_path, sys.path_importer_cache)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 1775, in _uncache
        _update_zipimporter_cache(normalized_path, cache)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 1757, in _update_zipimporter_cache
        for p in _collect_zipimporter_cache_entries(normalized_path, cache):
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 1736, in _collect_zipimporter_cache_entries
        if (np.startswith(normalized_path) and
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 17: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\patric~1\appdata\local\temp\pip-build-xxkjto\protobuf-to-dict\
```

Got a Problem Installing the Module, and im not able to fix it by myself, any ideas why it doesnt work?

* Using Windows 10 with Python 2.7

**Comment by rneu31** [comment]
Does it happen if you do "pip install protobuf_to_dict" directly? Also, which version of Python 2.7 are you running? I had no problem with 2.7.12.

**Comment by NoMotion** [comment]
I had this same error and running it manually worked thanks @rneu31

**Comment by Racle** [comment]
Didn't fixed this for me. Manually running `sudo pip install six --upgrade` fixed my issue on ubuntu server.

**Comment by corycomer** [comment]
@Racle thanks for mentioning that, fixed it for me as well on Ubuntu 14.04 LTS

**Comment by navarr** [comment]
Running the `sudo pip install six --upgrade` mentioned by @Racle fixed it on Debian for me as well, and then had to `sudo pip install -r requirements.txt`
