### ISSUE TITLE
"Attribute error('lat and lng required')"

### ISSUE THREAD

**Issue by BrodrickChilds** [AHAAAAAAA/PokemonGo-Map#210]
![screen shot 2016-07-18 at 4 55 01 pm](https://cloud.githubusercontent.com/assets/1323227/16934131/64f2827a-4d08-11e6-9417-d031bd5b89d2.png)

**Comment by ebajumpaa** [comment]
running into the same issue with the latest commit

**Comment by h1pp0** [comment]
confirmed, I hard reset and pulled few minutes ago and get the same error
`Traceback (most recent call last):
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dev/pokemapper/PokemonGo-Map/example.py", line 767, in fullmap
    'example_fullmap.html', fullmap=get_map(), auto_refresh=auto_refresh)
  File "/home/dev/pokemapper/PokemonGo-Map/example.py", line 858, in get_map
    zoom='15', )
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 34, in __init__
    self.build_markers(markers)
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 58, in build_markers
    self.add_marker(**marker)
  File "/home/dev/pokemapper/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 81, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng `required``

**Comment by Piotrovskyi** [comment]
Confirm, still don't working

**Comment by DjentAgent** [comment]
It's because ur using coords, not address. Need to fix smth with coords. They're not working.

**Comment by AlpenDitrix** [comment]
I've found that coord input is working if you'll pass them with just a space-separator (without comma from the GMaps site)

Just `-l "lat lon"`

**Comment by jasonlaskowski** [comment]
I receive the same error with lat long:  -l"44.7787 -93.1639"

**Comment by blixem** [comment]
Confirming what @AlpenDitrix posted, works if you remove the comma from the command line.
> I've found that coord input is working if you'll pass them with just a space-separator (without comma from the GMaps site)
> Just -l "lat lon"

**Comment by abdilahrf** [comment]
`>py example.py -a authService -u xxx -p xxx -l "-6.1753657 106.8247925" -st 5`

still got that error "AttributeError: lat and lng required"

**Comment by JZ6** [comment]
fixed

**Comment by ccxuy** [comment]
when i tried to run the program on command line
```
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 278-196-633
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
127.0.0.1 - - [19/Jul/2016 03:16:42] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\Works\_works_from_others\PokemonGo-Map-master\example.py", line 792, in fullmap
    'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)
  File "F:\Works\_works_from_others\PokemonGo-Map-master\example.py", line 901, in get_map
    zoom='15', )
  File "E:\Programs\Evn\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 34, in __init__
    self.build_markers(markers)
  File "E:\Programs\Evn\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 58, in build_markers
    self.add_marker(**marker)
  File "E:\Programs\Evn\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 81, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng required
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
127.0.0.1 - - [19/Jul/2016 03:16:43] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2016 03:16:43] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2016 03:16:43] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2016 03:16:43] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2016 03:16:43] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2016 03:16:44] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying
Exception KeyboardInterrupt in <module 'threading' from 'E:\Programs\Evn\Python27\lib\threading.pyc'> ignored
```
Also from browser
```
Traceback (most recent call last)
File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "E:\Programs\Evn\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "F:\Works\_works_from_others\PokemonGo-Map-master\example.py", line 792, in fullmap
'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)
File "F:\Works\_works_from_others\PokemonGo-Map-master\example.py", line 901, in get_map
zoom='15', )
File "E:\Programs\Evn\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 34, in __init__
self.build_markers(markers)
File "E:\Programs\Evn\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 58, in build_markers
self.add_marker(**marker)
File "E:\Programs\Evn\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 81, in add_marker
raise AttributeError('lat and lng required')
AttributeError: lat and lng required
```

**Comment by ccxuy** [comment]
I was trying this command
```
python example.py -a ptc -u OOOOOO -p XXXXXX -l "-6.1753657 106.8247925" -st 5
```

**Comment by nickelnickel** [comment]
Fixing my login issues resolved this issue for me.

**Comment by ccxuy** [comment]
Would you like to share more detail? :)

**Comment by isnuryusuf** [comment]
make sure no white space between latitude and langitude, i have several problem multiple time copyin cordinate from web and put to linux shell
to make sure the whitespace is remove
just change  6.1753657 106.8247925  to 6.1753657<backspace>106.8247925 become 6.1753657106.8247925 and then give space again 6.1753657<space>106.8247925
