### ISSUE TITLE
socket.error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by heartfrappe** [AHAAAAAAA/PokemonGo-Map#2107]
C:\Users\%username%\Desktop\PokemonGo-Map-master1\PokemonGo-Map-master>C:\Python27\python.exe runserver.py -a google -u %e-mailaddress% -p %password% -st 10 -k %APIKEY% -l "%Location address%" -H 0.0.0.0 -P 5000
2016-07-25 18:02:54,042 [  runserver] [   INFO] Parsed location is: 31.1091/-97.7276/0.0000 (lat/lng/alt)
2016-07-25 18:02:54,052 [     search] [   INFO] Map iteration: 0
2016-07-25 18:02:54,056 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-25 18:02:54,073 [auth_google] [   INFO] Google login for: %e-mailaddress%
Traceback (most recent call last):
  File "runserver.py", line 83, in <module>
    app.run(threaded=True, debug=args.debug, host=args.host, port=args.port)
  File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
    inner()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 656, in inner
    fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "C:\Python27\lib\SocketServer.py", line 417, in __init__
    self.server_bind()
  File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "C:\Python27\lib\SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

Running on Windows. Worked fine before most recent release. Updated to new release and now getting this error... Any ideas?

**Comment by heartfrappe** [comment]
Turns out, you have to run the following command

"runserver.py -se"


This should be added to the wiki

**Comment by heartfrappe** [comment]
So running "runserver.py -se" was working fine yesterday.... Now I'm getting the error in the title again... I'm going to fiddle with the config.ini file to see if it changes anything, but I'm not confident that it will... Any other thoughts?
