### ISSUE TITLE
problem with geopy, can someone helpme with this problem?

### ISSUE THREAD

**Issue by croszw** [AHAAAAAAA/PokemonGo-Map#2171]
## Expected Behavior

geopy with new google API key work fine
## Current Behavior

this is the program respond, not quite sure why. the google account working fine with mobile phone

Traceback (most recent call last):
  File "runserver.py", line 49, in <module>
    position = get_pos_by_name(args.location)
  File "C:\Users\Muhammad Nur Wachid\Desktop\PokemonGo-Map-master\pogom\pgoapi\utilities.py", line 60, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 338, in _parse_json
    self._check_status(page.get('status'))
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 363, in _check_status
    'The given key has gone over the requests limit in the 24'
**geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.**
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by JasperG** [comment]
See the output:

> geopy.exc.GeocoderQuotaExceeded: **The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.**

**Comment by croszw** [comment]
any recommendation how to fix it, some possible reference or solution?

**Comment by JasperG** [comment]
No fix needed, apparently you just exceeded your allowance for geocoding requests.

Enable Pay-As-You-Go billing, to pay $0.50 per one thousand (1,000) extra requests.
https://developers.google.com/maps/documentation/geocoding/usage-limits

**Comment by croszw** [comment]
but i never use my quota? how is that possible?

**Comment by shermsaludez** [comment]
Have you found your problem? I have the exact same thing. And i can't find the answer

**Comment by JasperG** [comment]
Same issue, exceeded quota, if you keep bashing the geocoding service, timeouts will occur (as your client may be temporarily blocked).

**Comment by JasperG** [comment]
> Traceback (most recent call last):
> File "runserver.py", line 49, in 
> position = **get_pos_by_name(args.location)**
> File "C:\Users\Muhammad Nur Wachid\Desktop\PokemonGo-Map-master\pogom\pgoapi\utilities.py", > line 60, in get_pos_by_name
> loc = geolocator.geocode(location_name)
> File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in geocode
> self._call_geocoder(url, timeout=timeout), exactly_one
> File "C:\Python27\lib\site-packages\geopy\geocoders\base.py", line 163, in _call_geocoder
> raise GeocoderTimedOut('Service timed out')
> geopy.exc.GeocoderTimedOut: Service timed out

And, by using get_pos_by_name, you *are* in fact using your quota.

**Comment by shermsaludez** [comment]
Im sorry i don't understand what you said but do you want me to replace these lines with get_pos_by_name?? can you help me out? I have given you the files im not really great at this :(




________________________________

**Comment by coolaj86** [comment]
I've got your solution to a server that doesn't hit geocoder limits right here:

* https://github.com/Daplie/node-pokemap

It only does geo-coding in the client, and it even prompts you to enter your google maps api key right after you login, so you'll never have a problem with hitting limits.

It's a node.js server that uses the same web ui, but is easy to install and none of the problems with installing python, compiling c code, dealing with threads, ports are already open, single-user, setting up https, etc. Super easy and simple.

Pre-Built Packages
------

It even has pre-built downloadable packages:

* https://github.com/Daplie/pokemap-webapp

(though windows is untested, but I'd love to know if the windows-pokemap.bat works)

Disclaimer
----

I haven't merged in all of the UI updates from this main repo yet, but they're coming.

**Comment by sefirotjl** [comment]
Hi, im having the same problem

```
Traceback (most recent call last):
  File "runserver.py", line 51, in <module>
    position = get_pos_by_name(args.location)
  File "C:\Users\jorgeper\Desktop\PokemonGo-Map-master\pogom\pgoapi\utilities.py
", line 61, in get_pos_by_name
    loc = geolocator.geocode(location_name, timeout=0)
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in
 geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\base.py", line 163, in _ca
ll_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out
```


Doing some research i found out that this is a common error in geopy
http://stackoverflow.com/questions/27914648/geopy-catch-timeout-error

So, i tested this change in pogom/pgoapi/utilities.py line 60
`loc = geolocator.geocode(location_name)`
Changed it to 
`loc = geolocator.geocode(location_name, timeout=10)`

this change fixed the problem.

Hope this can help you.
