### ISSUE TITLE
everything seems to be installed correctly getting an error on run server line

### ISSUE THREAD

**Issue by benc99** [AHAAAAAAA/PokemonGo-Map#2201]
after i enter python runserver.py -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]"

it seems to be running fine until i get this

 OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

I have never used python before sorry if this is vague or obscure.

**Comment by overload08** [comment]
`sudo pip install -r requirements.txt`

**Comment by benc99** [comment]
'sudo' is not recognized as an internal or external command, operable program or batch file.
@overload08

**Comment by overload08** [comment]
So just : 
`pip install -r requirements.txt`

**Comment by benc99** [comment]
i already did that. I've done every thing to the letter that was in the wiki on how to set it up. i dont know why it Cannot load native module 'Cryptodome.Cipher._raw_ecb'

**Comment by JasperG** [comment]
Because, apparently, it did not install cryptodomex. Re-run the pip install script.

**Comment by benc99** [comment]
i just did again it is still giving me the same response

**Comment by JasperG** [comment]
Did the installation complete succesfully?

**Comment by overload08** [comment]
Please past the responses of commands here.

**Comment by benc99** [comment]
yes it completed succesfully

**Comment by JasperG** [comment]
Are you running pip install as root?

**Comment by benc99** [comment]
yes

**Comment by benc99** [comment]
this is what i get when i enter the run server line

Traceback (most recent call last):
  File "runserver.py", line 15, in <module>
    from pogom.search import search_loop
  File "C:\Users\Ben Cooper\Desktop\PokemonGo-Map-master (4)\PokemonGo-Map-master\pogom\search.py", line 10, in <module>
    from pgoapi import PGoApi
  File "C:\Users\Ben Cooper\Desktop\PokemonGo-Map-master (4)\PokemonGo-Map-master\pogom\pgoapi\__init__.py", line 1, in <module>
    from pgoapi      import *
  File "C:\Users\Ben Cooper\Desktop\PokemonGo-Map-master (4)\PokemonGo-Map-master\pogom\pgoapi\pgoapi.py", line 34, in <module>
    from auth_google import AuthGoogle
  File "C:\Users\Ben Cooper\Desktop\PokemonGo-Map-master (4)\PokemonGo-Map-master\pogom\pgoapi\auth_google.py", line 29, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

**Comment by JasperG** [comment]
That's *windows*.
Go to the easy setup folder and run setup.bat.

**Comment by GreenflyM** [comment]
Are you running the runserver.py command with square brackets? The command should be run without them.

**Comment by benc99** [comment]
no i deleted the square brackets

**Comment by benc99** [comment]
ok i ran the easy setup it is still giving me the same error

**Comment by JasperG** [comment]
Do you have Administrator rights in Windows, and/or, do you have UAC enabled?

**Comment by overload08** [comment]
Can you past the response of setup.bat here ?

**Comment by benc99** [comment]
setup.bat response:

SUCCESS: Specified value was saved.
Requirement already up-to-date: pip in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): Six in c:\python27\lib\site-packages (from flask-cors==2.1.2->-r requirements.txt (line 16))
Requirement already up-to-date: Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: argparse==1.2.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: peewee==2.8.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: protobuf==2.6.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: protobuf-to-dict==0.1.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: flask-cors==2.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already up-to-date: setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 11))
Requirement already up-to-date: future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 13))
Requirement already up-to-date: pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 14))
Requirement already up-to-date: Six in c:\python27\lib\site-packages (from flask-cors==2.1.2->-r requirements.txt (line 16))

**Comment by benc99** [comment]
yes i do I'm admin on my pc and no uac
