### ISSUE TITLE
Error when doing runserver.py

### ISSUE THREAD

**Issue by arm4139** [AHAAAAAAA/PokemonGo-Map#2207]
Receive this everytime i try to use. 
>C:\Python27\python runserver.py -a ptc -u ****** -p ******* -l "Henrietta, Rochester" -st 10
2016-07-26 10:59:18,490 [  runserver] [   INFO] Parsed location is: 43.1400/-77.5915/0.0000 (lat/lng/alt)
2016-07-26 10:59:18,494 [     search] [   INFO] Map iteration: 0
2016-07-26 10:59:18,496 [     search] [   INFO] Attempting login to Pokemon Go.
Traceback (most recent call last):
2016-07-26 10:59:18,500 [   auth_ptc] [   INFO] PTC login for: *******
  File "runserver.py", line 76, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "C:\Users\Bobby\Desktop\PokemonGo-Map-master\pogom\utils.py", line 142, in load_credentials
    "No Google Maps Javascript API key entered in \config\credentials.json file!"
pogom.exceptions.APIKeyException: No Google Maps Javascript API key entered in \config\credentials.json file! Please take a look at the wiki for instructions on how to generate this key, then add that key to the file!

**Comment by heartfrappe** [comment]
looks like you didn't generate a google maps API key.

This is now a requirement so that you can use the maps.

Try this link:
https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by heartfrappe** [comment]
P.S. Once you've generated the key, there is a file called config.ini in the config subdirectory. You can store all of your auth settings there and then run "runserver.py -se" to start the thread
