### ISSUE TITLE
runserver.py not working - "No module named configargparse"

### ISSUE THREAD

**Issue by Wolfsblvt** [AHAAAAAAA/PokemonGo-Map#2210]
I refreshed my repo on the latest develop state. After that, the app stopped working for me.
If I run the runserver.py with given arguments, it shows me the following error:

`C:\OneDrive\Stuff\PokemonGo\PokemonGo-Map>runserver.py
Traceback (most recent call last):
  File "C:\OneDrive\Stuff\PokemonGo\PokemonGo-Map\runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "C:\OneDrive\Stuff\PokemonGo\PokemonGo-Map\pogom\app.py", line 12, in <module>
    from pogom.utils import get_args
  File "C:\OneDrive\Stuff\PokemonGo\PokemonGo-Map\pogom\utils.py", line 6, in <module>
    import configargparse
ImportError: No module named configargparse`

## Expected Behavior
I think the app... should run again?

## Current Behavior
It doesn't work no matter what arguments I use. even a simple `--help` throws the same error. So I think the python file is broken.
I would look into it myself but I've never worked with Python before.

## Your Environment

* Latest commit used: 808b466
* Operating System and version (desktop or mobile): Windows 10

(Oh, and on a side note. What's the best way to get my own config.ini to my heroku app, with my own database connection?)

**Comment by Wolfsblvt** [comment]
Oh god, my bad. I should really learn to use python someday.
Of course the solution is easy. I should run the Easy Setup every time I update my repo, cause maybe someone has added new dependecies which I am missing...

Nice. Solved xD
