### ISSUE TITLE
Errors during runserver.py execution, getting "HTTP 500 Internal Server Error" when attempting to access map

### ISSUE THREAD

**Issue by HolyApoc** [AHAAAAAAA/PokemonGo-Map#2258]
For the past two days, have been getting this issue consistently with attempting to do a fresh install of the program on both OSX and Windows. I can get API requests that show that the program is scanning for pokestops and finding pokemon, but I can't access the actual map - navigating to 127.0.0.1:5000 or localhost:5000 just produces http://imgur.com/a/KJtUl

Screencap of the console output as it's happening: http://imgur.com/a/zN4AG

I've tried reinstalling Python and its dependencies, and used both the master and develop branches with the same problem. Anyone know what's going on?

## Steps to Reproduce (for bugs)

1. Install Python 2.7
2. Download and install pip (get-pip.py)
3. Clone current development or master branch
4. pip install -r requirements.txt
5. runserver.py with commands

Error thrown during the execution:

```

[2016-07-26 17:58:34,052] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\----\Downloads\PokemonGo-Map-develop\pogom\app.py", line 29, in fullmap
    lang=config['LOCALE'])
  File "C:\Python27\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\----\Downloads\PokemonGo-Map-develop\templates\map.html", line 145, in top-level template code
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ gmaps_key }}&callback=initMap&libraries=places"></script>
  File "C:\Python27\lib\site-packages\markupsafe\_native.py", line 22, in escape
    return Markup(text_type(s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 0: ordinal not in range(128)
2016-07-26 17:58:34,052 [        app] [  ERROR] Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\----\Downloads\PokemonGo-Map-develop\pogom\app.py", line 29, in fullmap
    lang=config['LOCALE'])
  File "C:\Python27\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\----\Downloads\PokemonGo-Map-develop\templates\map.html", line 145, in top-level template code
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ gmaps_key }}&callback=initMap&libraries=places"></script>
  File "C:\Python27\lib\site-packages\markupsafe\_native.py", line 22, in escape
    return Markup(text_type(s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 0: ordinal not in range(128)
```

## Your Environment

* Version used: Master commit https://github.com/AHAAAAAAA/PokemonGo-Map/commit/d8cdab2332d8297f20bcc3b56d47d5f03dc24567, Develop commit https://github.com/AHAAAAAAA/PokemonGo-Map/commit/27e6ca08840ae44502cd3b5e99ef4ba28de432ff as well as previous
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 7, Mac OSX 10.11.6

**Comment by medghaim** [comment]
`UnicodeDecodeError: 'ascii' codec can't decode byte 0x93`

`byte 0x93` and `0x94` are: 
![image](https://cloud.githubusercontent.com/assets/7801031/17157366/c69a3edc-535c-11e6-8a82-e39c18284af2.png)

You can thank OSX and smart quotes. The punctuation you should use is:

![image](https://cloud.githubusercontent.com/assets/7801031/17157394/eedfd82a-535c-11e6-8516-b5e48004bbd2.png)
