### ISSUE TITLE
ImportError: No module named 'SocketServer'

### ISSUE THREAD

**Issue by crckdns** [AHAAAAAAA/PokemonGo-Map#23]
Python 3.6.0a3:

`Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 65, in <module>
    from SocketServer import ThreadingMixIn, ForkingMixIn
ImportError: No module named 'SocketServer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 14, in <module>
    import werkzeug.serving
  File "C:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 68, in <module>
    from socketserver import ThreadingMixIn, ForkingMixIn
ImportError: cannot import name 'ForkingMixIn'`

**Comment by devian223** [comment]
Try Python 2
