### ISSUE TITLE
Server crashes on load with Disk I/O error

### ISSUE THREAD

**Issue by GibbyOH** [AHAAAAAAA/PokemonGo-Map#2320]
For some reason I am getting the following error.

C:\PokemonGo-Map-Dev>"C:\Python27\python.exe" runserver.py -a google -u username -p ******** -l "Sandusky, OH" -st 20 -H 192.168.79.12 -t 25
sqlite
2016-07-27 09:28:58,302 [     models] [   INFO] Connecting to local SQLLite data
base.
Traceback (most recent call last):
  File "runserver.py", line 52, in <module>
    create_tables(db)
  File "C:\PokemonGo-Map-Dev\pogom\models.py", line 310, in create_tables
    db.create_tables([Pokemon, Pokestop, Gym, ScannedLocation], safe=True)
  File "C:\Python27\lib\site-packages\peewee.py", line 3574, in create_tables
    create_model_tables(models, fail_silently=safe)
  File "C:\Python27\lib\site-packages\peewee.py", line 4940, in create_model_tab
les
    m.create_table(**create_table_kwargs)
  File "C:\Python27\lib\site-packages\peewee.py", line 4615, in create_table
    if fail_silently and cls.table_exists():
  File "C:\Python27\lib\site-packages\peewee.py", line 4611, in table_exists
    return cls._meta.db_table in cls._meta.database.get_tables(**kwargs)
  File "C:\Python27\lib\site-packages\peewee.py", line 3689, in get_tables
    'type = ? ORDER BY name;', ('table',))
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: disk I/O error

I have reinstalled Python, and PIP and rerun the requirements.txt file.

**Comment by Forza4Development** [comment]
Have you tried this using MySQL as well?

**Comment by GibbyOH** [comment]
no how would I make that change?

**Comment by Forza4Development** [comment]
They have a section in the Wiki that guides you through the switch.  Has this command worked in the past: 'C:\PokemonGo-Map-Dev>"C:\Python27\python.exe" runserver.py -a google -u username -p ******** -l "Sandusky, OH" -st 20 -H 192.168.79.12 -t 25'

**Comment by GibbyOH** [comment]
Yes, it has worked for the last few days, woke up this morning to this error stoped the server and restarted it and it just kept crashing. I just found the MySQL wiki so I am going to give it a try and see if it helps.

**Comment by Forza4Development** [comment]
'peewee.OperationalError: disk I/O error' could indicate a problem with the HDD.  Are you using a HDD or SSD?

**Comment by GibbyOH** [comment]
I thought the same thing so I did a windows disk check which came back fine and then I used vcenter to check the VMDK as well which came back without error.

**Comment by GibbyOH** [comment]
After migrating to MySQL this issue has been resolved.
