### ISSUE TITLE
Anyone had issues setting up mysql and docker? 

### ISSUE THREAD

**Issue by Daniel-ltw** [AHAAAAAAA/PokemonGo-Map#2366]
Tried using a mysql docker container and have another docker container for my map. 
It seems that the map container have issues connecting to the mysql docker container. 

## Expected Behavior
It should just work off the code that you have with the develop branch. 

## Current Behavior
```
Traceback (most recent call last):
  File "./runserver.py", line 49, in <module>
    create_tables(db)
  File "/usr/src/app/pogom/models.py", line 332, in create_tables
    db.connect()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3929, in _connect
    return mysql.connect(db=database, **conn_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 690, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 908, in connect
    self._request_authentication()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1116, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
peewee.OperationalError: (1045, u"Access denied for user 'root'@'172.17.0.9' (using password: YES)")
```

## Possible Solution
Seem like an access issue or a create table issue. 

## Steps to Reproduce (for bugs)
Followed most steps from the wiki. 

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile): Ubuntu 16.04 VPS

**Comment by jnovack** [comment]
which wiki page?

**Comment by Daniel-ltw** [comment]
MySQL wiki page, last section.

**Comment by jnovack** [comment]
The text "MySQL wiki page" is unclickable.

**Comment by Daniel-ltw** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-start-using-a-MySQL-Server#viii-docker-settings-w-lets-encrypt

**Comment by Daniel-ltw** [comment]
Tried with latest develop branch, everything seems fine now.
