### ISSUE TITLE
How to cover a wider area with multiple searchers, Implementation

### ISSUE THREAD

**Issue by viper065505** [AHAAAAAAA/PokemonGo-Map#2379]
Hi All,

I'm trying to implement the honeycomb searchers. Where do I addd the code from "https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-cover-a-wider-area-with-multiple-searchers" ? I am sorry if this is a stupid question in advance, I'm still new to this. Thanks! Any guidance or documentation would be greatly appreciated, I have sifted through the site and google, this is my last resort.

## Expected Behavior
Honeycomb searchers
## Current Behavior
N/A

## Possible Solution
???

## Steps to Reproduce (for bugs)
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-cover-a-wider-area-with-multiple-searchers

## Context
I'm trying to implement the honeycomb searchers

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by kevinpark1217** [comment]
That way of honeycomb search is not the most efficient way to go. As you can see from the picture that there are useless overlaps that could be utilized somewhere else. This is how you do it properly.

https://pokemon.tekhak.com

Also, I have a separate database for my website, so I can allow people to connect to my database and create a one huge master map.

**Comment by TJohnson93** [comment]
@kevinpark1217 You mentioned that honeycomb search is not the most efficient way to go? Any recommendations on a better way? I too am looking for a similar thing to the OP.

**Comment by kevinpark1217** [comment]
@TJohnson93 I guess that was a bad wording on my part. Honeycomb search is the most efficient way far as I know, but it is best if you try to remove overlaps like this

![Overlap](https://i.gyazo.com/2972dd9069c5ffa8fc683f1345c83915.png)

**Comment by reyqn** [comment]
@viper065505 @TJohnson93 I've no clue why they are not merging #2266 but you could use https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-use-Hex-Beehive-Generator with it and it should solve the issues mentionned by @kevinpark1217 .

**Comment by TJohnson93** [comment]
@kevinpark1217 Thanks... I currently am running this on linux and have it working by selecting the one location and then running runserver.py. I noticed on your site that you were able to run it on multiple locations. Would I do a similar approach to what @reyqn suggested with Hex Beehive Generator and instead of using a bat file use a bash script? Sorry to be annoying... been mucking around with this for hours :|... Thanks

**Comment by reyqn** [comment]
@TJohnson93 it's even easier if you are running on linux. Just check Tools/Hex-Beehive-Generator for instructions

**Comment by kevinpark1217** [comment]
@TJohnson93 I didn't even know there was a PR for this feature. Anyway, I am also running this on a linux, and I have created my own python script to calculate each beehive starting location through an algorithm and start each scan as a background process and save logs to a file.

**Comment by TJohnson93** [comment]
@reyqn Thanks... stupid me didn't pull the Dev... another question if you don't mind? Have run the following as per instructions...
```
./beehive_builder.sh 5 4 -19.280479 146.768370
./beehive.sh
```

which results in an output of:

```
nohup: nohup: nohup: nohup: nohup: nohup: nohup: nohup: nohup: appending output to 'nohup.out'
appending output to 'nohup.out'
appending output to 'nohup.out'
appending output to 'nohup.out'
appending output to 'nohup.out'
nohup: nohup: nohup: nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
nohup: nohup: nohup: appending output to 'nohup.out'
appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
appending output to 'nohup.out'appending output to 'nohup.out'

appending output to 'nohup.out'
appending output to 'nohup.out'appending output to 'nohup.out'

nohup: nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
nohup: nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
appending output to 'nohup.out'
appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
appending output to 'nohup.out'
root@dbe475173253:~/PokemonGo-Map/Tools/Hex-Beehive-Generator# appending output to 'nohup.out'
appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
nohup: nohup: nohup: nohup: nohup: nohup: nohup: nohup: appending output to 'nohup.out'
appending output to 'nohup.out'
appending output to 'nohup.out'appending output to 'nohup.out'
appending output to 'nohup.out'

appending output to 'nohup.out'
appending output to 'nohup.out'
appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
```

followed by my server completely crashing... Do you have any ideas what might have caused it?

Thanks.

**Comment by reyqn** [comment]
Seems like you used lots of leaps. Could you also paste the content of beehive.sh?

**Comment by TJohnson93** [comment]
Thanks for the help :D 

```
nohup python ../../runserver.py -ns -l '-19.280479, 146.76837' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2683558103, 146.76837' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2744170689, 146.779492419' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2865402585, 146.779492419' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2926015167, 146.768368765' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2865395852, 146.757245522' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2744163955, 146.757245522' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2562326207, 146.76837' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2622938794, 146.779491597' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2683551381, 146.790613604' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2804783277, 146.790613604' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2926015174, 146.790613604' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2986627754, 146.779489538' -st 5 &
nohup python ../../runserver.py -ns -l '-19.3047240334, 146.76836506' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2986621017, 146.757240993' -st 5 &
nohup python ../../runserver.py -ns -l '-19.29260017, 146.746117339' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2804769804, 146.746117339' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2683537907, 146.746117339' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2622918597, 146.757238935' -st 5 &
nohup python ../../runserver.py -ns -l '-19.244109431, 146.76837' -st 5 &
nohup python ../../runserver.py -ns -l '-19.25017069, 146.779490775' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2562319489, 146.79061196' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2622932076, 146.801733557' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2744163973, 146.801733557' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2865395869, 146.801733557' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2986627766, 146.801733557' -st 5 &
nohup python ../../runserver.py -ns -l '-19.3047240345, 146.790609078' -st 5 &
nohup python ../../runserver.py -ns -l '-19.3107852924, 146.779484187' -st 5 &
nohup python ../../runserver.py -ns -l '-19.3168465501, 146.768358884' -st 5 &
nohup python ../../runserver.py -ns -l '-19.3107846181, 146.757233993' -st 5 &
nohup python ../../runserver.py -ns -l '-19.3047226863, 146.746109515' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2986607545, 146.734985449' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2865375649, 146.734985449' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2744143752, 146.734985449' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2622911855, 146.734985449' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2562292546, 146.746106634' -st 5 &
nohup python ../../runserver.py -ns -l '-19.2501673238, 146.757227408' -st 5 &
nohup python ../../runserver.py -os -l '-19.280479, 146.768370' &
```

**Comment by reyqn** [comment]
Yeah it actually seems okay. I wouldn't use more than 3 leaps though. Maybe try with `./beehive_builder.sh 5 3 -19.280479 146.768370`

**Comment by TJohnson93** [comment]
@reyqn Cheers... Probably more stupid questions... Where am I meant to be storing credentials for the runserver.py and well as the -H and -P args? Otherwise I am not receiving anything on webpage...

**Comment by reyqn** [comment]
In config/config.ini

**Comment by TJohnson93** [comment]
That did... Thank you sooo much!!! If I might bug you once more? Any recommendations on getting it run/scan quicker? Seems to be going pretty slow - http://138.68.9.90:8083

**Comment by reyqn** [comment]
How many threads are you using? It can be configured in config.ini too

**Comment by kevinpark1217** [comment]
@reyqn Isn't mutithreading broken at the moment? Or did it get fixed? It used to override pokemons in databases so some wouldn't be shown on the website.

**Comment by TJohnson93** [comment]
I left it at default (which is 1 I believe) and I just changed it to 6... and it crashed my server :S

**Comment by reyqn** [comment]
@kevinpark1217 It has been hotfixed in #1913 I belive. Works well for me. @TJohnson93 I think you should use mysql for multithreading

**Comment by stekern** [comment]
@reyqn Do you by any chance know how to setup mysql on Heroku?

**Comment by reyqn** [comment]
@stekern no idea but a quick search gave me this [https://elements.heroku.com/addons/cleardb](url)

**Comment by TJohnson93** [comment]
@reyqn I changed it to 10 which stopped crashing the server... It seems to work other than missing certain sections... [Screenshot](http://awesomescreenshot.com/07261whs5f)

**Comment by reyqn** [comment]
@TJohnson93 check nohup.out for errors maybe?

**Comment by TJohnson93** [comment]
I don't know alot about mult-threading... Not sure what to make of this?

```
Traceback (most recent call last):
  File "../../runserver.py", line 74, in <module>
    create_search_threads(args.num_threads)
  File "/root/PokemonGo-Map/pogom/search.py", line 133, in create_search_threads
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
Traceback (most recent call last):
  File "../../runserver.py", line 99, in <module>
    app.run(threaded=True, use_reloader=False, debug=args.debug, host=args.host, port=args.port)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 607, in process_request
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

**Comment by reyqn** [comment]
Yeah your workers crash. Don't know why though. You can go to issue #2388 now ^^

**Comment by TJohnson93** [comment]
@reyqn Couldn't really find a solution on that issue... you mentioned before that maybe mysql threading would help? How would I go about setting that up?

**Comment by moggd** [comment]
This didn't work for me.  I followed the instructions, executed the batch file and it seems to load python but quickly closes and I see nothing

**Comment by reyqn** [comment]
@moggd see #2327
