### ISSUE TITLE
cant run     can someone help me 

### ISSUE THREAD

**Issue by coremaya** [AHAAAAAAA/PokemonGo-Map#2389]
Traceback (most recent call last):
  File "runserver.py", line 51, in <module>
    position = get_pos_by_name(args.location)
  File "C:\Users\wunan\Desktop\PokemonGo-Map-2.1.0\pogom\pgoapi\utilities.py", line 60, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\base.py", line 163, in _call_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out

**Comment by jasonfoy21** [comment]
Double check to make sure you have both API's attached to your key; Javascript/Places Service.

**Comment by coremaya** [comment]
@jasonfoy21 can u tell the Specific operation steps？

**Comment by andrewda** [comment]
Read the wiki. https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API-Key

**Comment by coremaya** [comment]
@jasonfoy21  @andrewda  Thanks a lot   But a new error 

"Google Maps API error: DeletedApiProjectMapError https://developers.google.com/maps/documentation/javascript/error-messages#deleted-api-project-map-error" js:34:405

TypeError: bounds is undefined

**Comment by coremaya** [comment]
hah so stupid
