### ISSUE TITLE
Server not running

### ISSUE THREAD

**Issue by apmbsd** [AHAAAAAAA/PokemonGo-Map#2427]
## Expected Behavior
Server should run

## Current Behavior
$ python ./runserver.py --help
Traceback (most recent call last):
  File "./runserver.py", line 10, in <module>
    from flask_cors import CORS
  File "/Library/Python/2.7/site-packages/flask_cors/__init__.py", line 11, in <module>
    from .decorator import cross_origin
  File "/Library/Python/2.7/site-packages/flask_cors/decorator.py", line 12, in <module>
    from flask import make_response, request, current_app
  File "/Library/Python/2.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Library/Python/2.7/site-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/Library/Python/2.7/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/Library/Python/2.7/site-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/Library/Python/2.7/site-packages/werkzeug/http.py", line 28, in <module>
    from urllib.request import parse_http_list as _parse_list_header
ImportError: No module named request

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
* Version used: All versions
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): OSX El Capitan

**Comment by fjozsef** [comment]
Have you tried to run `pip install -r requirements` again? I think there have been new dependencies added.

**Comment by apmbsd** [comment]
pip install -r requirements.txt
pip install --upgrade -r requirements.txt
Both tell me everything's up to date.

**Comment by Hoekynl** [comment]
pip install -U requests==2.10.0

**Comment by apmbsd** [comment]
$ pip install -U requests==2.10.0
Requirement already up-to-date: requests==2.10.0 in /Library/Python/2.7/site-packages

**Comment by Zentrik** [comment]
have you tried using pip2

**Comment by apmbsd** [comment]
Same result with pip2

**Comment by Zentrik** [comment]
why are you using `--help` if you are trying to run the server

**Comment by apmbsd** [comment]
Because the error is the same whether I run `--help` or `-u blah -p blah -l blah `

**Comment by Zentrik** [comment]
I'm out of ideas😞.

**Comment by apmbsd** [comment]
Thanks for your help. I now think it's a permissions problem 'cos `sudo python ./runserver.py ` runs fine.

**Comment by Hoekynl** [comment]
In what folder is this executed? If it is not in /home/<you>/<folder> it needs sudo python ./server.py.
In your own home folder you dont need sudo
