### ISSUE TITLE
start issue

### ISSUE THREAD

**Issue by chpoint** [AHAAAAAAA/PokemonGo-Map#2430]
when i do the start on the map they give me this error

  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "c:\pogo2\pogom\app.py", line 6, in <module>
    from flask_compress import Compress
ImportError: No module named flask_compress

**Comment by georgo** [comment]
Did you follow https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Windows-Installation-and-requirements ? Especially check your pip.

**Comment by Simbe90** [comment]
I'm on a mac and had the same issue. Old version worked fine, today I did "git pull" as instructed on the Machintosh installation guide. It then gave me the same error. Tried installing everything again as per the updated guide but no luck. Finally got everything to work by running "pip install -r requirements.txt" inside the PokemonGo-Map directory.

So whoever is updating the Machintosh guide should update the updating procedure, because just running "git pull" wont work.

**Comment by chpoint** [comment]
yep, last version work for me to, but this one doesnt work. my installation is fine i follow the instrutions

**Comment by commanderjsoc** [comment]
Please close issue if this solved your problem

**Comment by chpoint** [comment]
sorry but still in the same error

**Comment by ioudeveldhuis** [comment]
I am also on a mac and did a git pull and got the same error.
When trying todo the pip install -r requirements.txt I get the following error:
`Installing collected packages: configargparse, PyMySQL, flask-compress
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/configargparse.py'`

**Comment by georgo** [comment]
> IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/configargparse.py'

Dude, c'mon.

**Comment by ioudeveldhuis** [comment]
I already noticed it right after I posted and I removed my comment right after that...

Verstuurd vanaf mijn iPhone

**Comment by commanderjsoc** [comment]
For those who didn't notice, please close this issue. Also @georgo you just need `sudo pip install -r requirements.txt` I did both with and without sudo
