### ISSUE TITLE
EOF Read Where Object Expected

### ISSUE THREAD

**Issue by IrwinAllen13** [AHAAAAAAA/PokemonGo-Map#2474]
Hey Guys,

First time on github, so please go easy on me. :)

## Current Behavior
```
Traceback (most recent call last):
  File "/home/pi/PokemonGo-Map/runserver.py", line 10, in <module>
    from flask_cors import CORS
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/__init__.py", line 11, in <module>
    from .decorator import cross_origin
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 12, in <module>
    from flask import make_response, request, current_app
  File "/usr/local/lib/python2.7/dist-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/http.py", line 22, in <module>
    from email.utils import parsedate_tz
  File "/usr/lib/python2.7/email/utils.py", line 32, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python2.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
EOFError: EOF read where object expected
```

## Steps to Reproduce (for bugs)
`sudo python /home/pi/PokemonGo-Map/runserver.py -a google -u ***** -p *****  -l "Some Location" -st 5 -dc -H 0.0.0.0 -P 5002 -t1`

## Context

Not 100% what is going on here as I have never used google API's. I know the account has not been blocked as I have logged into it.

Any help on this great app would be greatly appreciated!

## Your Environment
* Version used: Latest
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Linux Jessie - Running on a RPI 2

**Comment by Dragonprovidence** [comment]
Are you using the latest from development branch or the latest from release?

It sounds like it ran into an unexpected end of a file while reading.

1. Did you modify config.ini as well?
2. Did you copy the files to the RPI2 from a Windows or Mac environment?
3. I think someone else reported seeing this when they ran it without correct permissions, but not sure that was related, just something to consider.
