### ISSUE TITLE
Exception in thread search_thread-0:

### ISSUE THREAD

**Issue by DomGrieco** [AHAAAAAAA/PokemonGo-Map#2528]
## Expected Behavior
No errors

## Current Behavior
New error for me.

`Exception in thread search_thread-0:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\PokemonGo-Map-develop\pogom\search.py", line 159, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "D:\Downloads\PokemonGo-Map-develop\pogom\models.py", line 319, in parse_map
    bulk_upsert(Pokestop, pokestops)
  File "D:\Downloads\PokemonGo-Map-develop\pogom\models.py", line 349, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\playhouse\shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 161, in execute
    result = self._query(query)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 317, in _query
    conn.query(q)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1021, in _read_query_result
    result.read()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 983, in _read_packet
    packet.check_error()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1213, u'Deadlock found when trying to get lock; try restarting transaction')`

## Steps to Reproduce (for bugs)
I'm not sure. Just running the current dev version last commit 3ebb51ef48d73190e6171712c6395c119800fb35

## Your Environment

* Version used: 3ebb51ef48d73190e6171712c6395c119800fb35
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10, haven't seen the error on my ubuntu machine.

**Comment by chuyskywalker** [comment]
> Deadlock found when trying to get lock; try restarting transaction

Looks like mysql got into a bad state. I've not used that integration much, so I can't comment why/how though.

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2528
