### ISSUE TITLE
[BUG] u'Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by stappjno** [AHAAAAAAA/PokemonGo-Map#2560]
I'm running 8 instances of the script with a nearly equal configuration like this one:
python runserver.py -a ptc -u user -p pass -l "city" -st 15 -P 4444 -H 0.0.0.0 -L de -t 1 -sd 0.5 -td 0.5 -ld 0.5
After the last Update from yesterday I changed my DB-Type to mysql (the sql-server bundled with the newest version of xampp) and in the first moment, everything worked well. But after some secondes two of my 8 instances stopped running with the error message "u'Deadlock found when trying to get lock; try restarting transaction". After a restart everything worked well for about 30min. After that another instance had the same error. 

## Expected Behavior
I think the script doesent catch this exeption. Maybe it's possible to fix that bug or if this would need too much time it would be great if the script would make a retry.

## Current Behavior

The full Python Error Message Log

Exception in thread search_thread-0:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Stappjno\Downloads\PoGoMap\v3\pogom\search.py", line 159, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "C:\Users\Stappjno\Downloads\PoGoMap\v3\pogom\models.py", line 302, in parse_map
    bulk_upsert(Pokestop, pokestops)
  File "C:\Users\Stappjno\Downloads\PoGoMap\v3\pogom\models.py", line 332, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 161, in execute
    result = self._query(query)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 317, in _query
    conn.query(q)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1021, in _read_query_result
    result.read()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 983, in _read_packet
    packet.check_error()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\Python27\lib\site-packages\pymysql\err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1213, u'Deadlock found when trying to get lock; try restarting transaction')

## Possible Solution
If a fix is too complex, build a retry please

## Your Environment
Windows 8 64bit, 16GB Ram, i7 @ 3.2GHz

**Comment by Pedrock** [comment]
Please take a look at pull request #2016. It should fix this problem, but makes the performance worse.

**Comment by stappjno** [comment]
Fixed the problem for me. I can't see any larger performance consumption. Thank you!
