### ISSUE TITLE
IndexError on response.payload[0] in get_heartbeat()

### ISSUE THREAD

**Issue by benemorius** [AHAAAAAAA/PokemonGo-Map#258]
```
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "example.py", line 604, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 640, in process_step
    profile_response))
  File "example.py", line 421, in get_heartbeat
    payload = response.payload[0]
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 64, in __getitem__
    return self._values[key]
IndexError: list index out of range
```

This seems rare enough to be low priority for now, so I'm not currently working on this.

Basically we just need to handle retries of either `process_step()` or `get_heartbeat()`, similar to `retrying_set_location()`.

Or we could just `return None` like we do `if response is None` for now. Still better to retry though I think.

**Comment by benemorius** [comment]
Ok so this may be less rare than I thought. It's a duplicate of #257 posted 5 minutes earlier. I'll go ahead and work around it as I proposed.
