### ISSUE TITLE
response.payload[0] would cause out of range exception

### ISSUE THREAD

**Issue by akorenkoff** [AHAAAAAAA/PokemonGo-Map#267]
Quick fix for out of range error would be to check for its length first

Exception in thread search_thread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "example.py", line 595, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 631, in process_step
    profile_response))
  File "example.py", line 410, in get_heartbeat
    payload = response.payload[0]
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/containers.py", line 64, in __getitem__
    return self._values[key]
IndexError: list index out of range

**Comment by DerScreever** [comment]
same as #257
