### ISSUE TITLE
Grunt Build Error on Run - EC2 Nano Instance [Amazon Linux AMI 2016.03.3 (HVM)]

### ISSUE THREAD

**Issue by stvlange** [AHAAAAAAA/PokemonGo-Map#2678]
Getting the following error when trying to run latest development code on a T2.Nano instance using the Amazon Linux AMI 2016.03.3.  Any help is appreciated.

Error:
[PokemonGo-Map-develop]$ ./runserver.py 
2016-07-30 00:47:45,117 [    MainThread][     runserver] [CRITICAL] Please run "grunt build" before starting the server.

[PokemonGo-Map-develop]$ grunt build
Traceback (most recent call last):
  File "/usr/local/bin/grunt", line 9, in <module>
    load_entry_point('grunt==0.1.1', 'console_scripts', 'grunt')()
  File "/usr/local/lib/python2.7/site-packages/grunt/render.py", line 94, in main
    render_from_file(**options)
  File "/usr/local/lib/python2.7/site-packages/grunt/render.py", line 54, in render_from_file
    with codecs.open(input, encoding=encoding) as f:
  File "/usr/lib64/python2.7/codecs.py", line 884, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'build'

**Comment by johnflavin** [comment]
I'm having that same error. 
* Dev branch
* commit c5fe7d6
* default docker build (`docker build -t <name> .`)

```bash
$ docker run -v $(pwd):/usr/src/app -p 5000:5000 <name>  -l <location>
2016-07-30 01:24:50,735 [    MainThread][     runserver] [CRITICAL] Please run "grunt build" before starting the server.
```

**Comment by Mandalorian007** [comment]
Noticed this red error output during:
`pip install -r requirements.txt`

`Command "python setup.py egg_info" failed with error code 1 in c:\users\matthew\appdata\local\temp\pip-build-vnqz_e\pyproj\`

**Comment by CJBok** [comment]
I am getting the same message but I have no idea what to do.

**Comment by Lenny188** [comment]
same here :/

**Comment by tkSimon** [comment]
@johnflavin:
I think you are using the regular `Dockerfile` like you would use `Dockerfile.dev` (with `-v $(pwd):/usr/src/app`)

Check out the Dockerfile you're using, the instructions differ.
You can't/shouldn't use Dockerfile with `-v $(pwd):/usr/src/app`.
If you really want to do that, use Dockerfile.dev (`docker build -f Dockerfile.dev -t name .`)

**Comment by AndrewYoungs** [comment]
I am getting the same message to run "grunt build" on my Windows VPS.

**Comment by aisotia** [comment]
Getting this on a Windows 8.1 machine, did a new git clone -b of develop, and fresh config, same issue.

**Comment by Dynamico** [comment]
Im also having issues with grunt build...
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'jshint-stylish'
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

**Comment by Dynamico** [comment]
Got it to work had to run npm install again and even had to update minimatch and then run the grunt build

**Comment by AndrewYoungs** [comment]
@Dynamico Got NPM and nodejs installed again. what command did you run exactly? Because I am still getting the missing file / directory error.

**Comment by AndrewYoungs** [comment]
@Dynamico Disregard, forgot to run npm update after the reinstall.

**Comment by Dynamico** [comment]
@AndrewYoungs Ok run this after and see if u dont get any warnings or errors.
sudo npm install -g grunt-cli
**had to update minimatch:**
sudo npm install -g minimatch@3.0.2
**then had to install this:**
sudo npm install jshint-stylish
ran grunt build after that and it got it to work

**Comment by AndrewYoungs** [comment]
@Dynamico Alright done and done but I am getting this still:

http://imgur.com/a/48UCl

Thanks for your help by the way. (Also I am running Windows Server)

**Comment by AndrewYoungs** [comment]
@Dynamico Hey actually got it working. Just forgot to set up the project. RIP.

**Comment by Dynamico** [comment]
@AndrewYoungs hahahahaha I was trying to look up your error but I guess that'll do! :)

**Comment by SkOODaT** [comment]
im also getting this error and cant seem to resolve it i have NPM and nodejs installed and ive ran 
npm install -g grunt-cli
sudo npm install -g minimatch@3.0.2
sudo npm install jshint-stylish
but it still says [ MainThread][ runserver] [CRITICAL] Please run "grunt build" before starting the server.

**Comment by neobithia** [comment]
I'm getting this "grunt build" error too.  Can someone please explain the steps to resolve using Windows Command Prompt?

'sudo' isn't recognized in Windows?

**Comment by SkOODaT** [comment]
im slowing figureing this out you need to install npm nodejs and install grunt ....
http://gruntjs.com/getting-started

teaching myself lmao

**Comment by Dynamico** [comment]
@neobithia sudo is to run commands with permissions on mac
@SkOODaT What error do u get when u run grunt build?
If you guys run npm -v what version does it say???

**Comment by SkOODaT** [comment]
@Dynamico way past that :) i just finished grunt build lol

**Comment by neobithia** [comment]
@SkOODaT Thanks for the link!  I tried:

`npm install -g grunt-cli`

But got this?

`'npm' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by SkOODaT** [comment]
@neobithia that means npm/nodejs isnt installed or its not being picked up by command prompt uesing npm

**Comment by neobithia** [comment]
@skoodat how do we install that?
