### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 15: ordinal not in range(128)

### ISSUE THREAD

**Issue by maxlager** [AHAAAAAAA/PokemonGo-Map#2707]
Script working, but i have page, looks like: [https://postimg.org/image/pk3ckkjmf/](picture)
And when i'm pressing Pokemon Go Map (http://localhost:5000/#) i see in terminal this: 
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 15: ordinal not in range(128)
2016-07-30 10:35:40,387 [           app] [  ERROR] Exception on /static/appicons/favicon.ico [GET]
Traceback (most recent call last):
  File "/home/maxlager/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/maxlager/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/maxlager/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/maxlager/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/maxlager/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/maxlager/.local/lib/python2.7/site-packages/flask/helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/maxlager/.local/lib/python2.7/site-packages/flask/helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "/home/maxlager/.local/lib/python2.7/site-packages/flask/helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
`

**Comment by maxlager** [comment]
That's error appears every time when i refresh page.

**Comment by Welcius** [comment]
Are you actually replacing GMAPS_KEY for the key you've received from the google api?

**Comment by maxlager** [comment]
Yep.

**Comment by Welcius** [comment]
I think it's key that they give you when you create the project, I don't remember having to click on those options. Also I remember having that error but I don't remember how I solved it, can you try running the commands on the last answer of this thread? http://askubuntu.com/questions/393638/unicodedecodeerror-ascii-codec-cant-decode-byte-0x-in-position-ordinal-n

**Comment by maxlager** [comment]
No, that's doesn't help.

**Comment by Welcius** [comment]
Can you try using a ptc account instead of a google one? Just trying things since I dont remember how i solved it

**Comment by maxlager** [comment]
I tried, but that's also useless. I think i need to set a en_GB as a language in the system.
