### ISSUE TITLE
Connection Pooling causing mysql to reach max_connections + error 500 on map page

### ISSUE THREAD

**Issue by bartosh0** [AHAAAAAAA/PokemonGo-Map#2743]
## Expected Behavior

As mentioned in #2424 only max 5 connections should be spawned by default in each instance of the map - be it scanner (-ns) or webserver (-os).

## Current Behavior

Each iteration of scan spawns additional 1 connection to db.
Because of that MySQL server reaches max_connections limit (which I can set pretty high since Im using VPS) and I'm starting to get the following errors in webserver thread and map loads are giving me mostly HTTP 500 (some requests are successful, but like 80% are giving Internal Server Error)
```
[2016-07-30 15:18:36,058] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
```

## Possible Solution

Are we sure that connections are closed after search threads are finished?
Or maybe I got too old MySQL verison or settings are wrong? I tried searching but found nothing.

## Steps to Reproduce (for bugs)

1. Start webserver
2. Start all scanners (~~21 of them)
3. let scanner do a full run (all steps defined in -st)
4. check number of connections in mysql:
```
mysql> show status like 'Con%';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| Connections   | 2192  |
+---------------+-------+
1 row in set (0.00 sec)
```
5. Wait a bit more
6. Start getting error 500.

## Context

I just need to get my map up and running without those annoying HTTP 500's

## Your Environment

* Version used: newest development branch
* Python: 2.7.9
* debian jessie
* MySQL 5.5.49-0+deb8u1 (stable for this debian release)
* running ~~21 scanner instances (-ns) and one webserver (-os) with the following commands:
```
python runserver.py -nk -ng -u censored -p censored -st 15 -t 2 -sd 1 -td 1 -ld 1 -k censored -l "somestreet 1, somecity" -H 0.0.0.0 -P 4443 -ns
```
```
python runserver.py -k censored -l "somestreet 1, somecity" -H 0.0.0.0 -P 4443 -os
```

**Comment by Pedrock** [comment]
Add:
db-max_connections: 100
to your config.ini You can change this number to what you see fit.

**Comment by bartosh0** [comment]
@Pedrock yes, sure... but im going to run into the same eventually. 
In only ~~2 hours i got to the point of having >2k connections and I aim to run the map 24/7.

**Comment by Niksunen** [comment]
Im getting  4053 connections couple of hours.

**Comment by bartosh0** [comment]
Even with code commented out like below from models.py, I'm still getting errors as above.
```
def init_database(app):
    if args.db_type == 'mysql':
        db = MyRetryDB(
            args.db_name,
            user=args.db_user,
            password=args.db_pass,
            host=args.db_host,
            #max_connections=args.db_max_connections,
            stale_timeout=300)
        log.info('Connecting to MySQL database on {}.'.format(args.db_host))
```

**Comment by ingwarsw** [comment]
Guys you dont have any extra things done with db.. witch dont close connections?

**Comment by bartosh0** [comment]
I don't think so. I may post my configuration here or reconfigure MySQL from debian repositories if you think this might help

**Comment by ingwarsw** [comment]
Nope.. I rather ask if you have any changes to codebase..

Mayby you open connections somewhere (of pewee is opening one for you) and not closing them?

**Comment by bartosh0** [comment]
I'm running a clear develop branch. No changes apart from the one I pasted above.

**Comment by ingwarsw** [comment]
If you comment out that line it just use default witch is 10 :)

**Comment by ingwarsw** [comment]
Im not using all features.. mayby there is one witch is leaking connections..

**Comment by bartosh0** [comment]
@ingwarsw which one are you using?
lol... I'll uncomment it then.

**Comment by HinoReo** [comment]
This is happening to me too with the latest development build.
I have 1 -os thread and 24 -ns workers (3 accounts per instance, 8 instances, 5.6 writes into DB / second, mysql db at the same machine), after 2-3 hours of somewhat okay run -os drops dead with ValueError('Exceeded maximum connections.').

**Comment by GareRam** [comment]
Came here looking because I have the same problem.

**Comment by DeviantEng** [comment]
I also have the same problem.

What's interesting is I've increased my `max_connections` to 2500, verified it's set within mysql (mariadb), and my actual connections are much lower (because I just restarted mysql).  I don't understand why I'm getting the errors if I'm so far below my max_connections.

```
MariaDB [(none)]> show variables like 'max_connections';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 2500  |
+-----------------+-------+
1 row in set (0.01 sec)

MariaDB [(none)]> show status like 'Connections';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| Connections   | 88    |
+---------------+-------+
1 row in set (0.00 sec)
```

**Comment by GareRam** [comment]
I disabled max connections in mySQL server altogether and am still getting these errors...

**Comment by DeviantEng** [comment]
So here's something interesting I found in ./pogo/utils.py..

```
parser.add_argument('--db-max_connections', help='Max connections for the database', type=int, default=5)
```

Seems that an arg was added `--db-max_connections` on the app side, which defaults to...`5`.  I've added that arg to my startup script and set the value equal to my `max_connections` set in `/etc/my.cnf`, and no more `Exceeded maximum connections.`  Now to deal with these...

```
Exception in thread Thread-5600:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/SocketServer.py", line 596, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib64/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

**Comment by HinoReo** [comment]
I find this somewhat amusing:
Each time the process finishes the cycle and starts over, one more connection is added and non is closed. So, for my 1 -os and 8 -ns processes it goes 9, 17, 25, 33, and so on, +8 connections every cycle (1 for each -ns). So the connections ARE NOT being closed after use. What is interesting is, that the on failing in the end is -os process.

**Comment by HanSolo80** [comment]
I can confirm that setting the max_connections parameter to the one specified in my.conf doesn't work at all. The MySQL instance is flooded with connections and shortly after starting the app the server refuses connections.

**Comment by DeviantEng** [comment]
@HanSolo80 You set `--db-max_connections` to what you have set in `my.conf` and it's not working for you?

Mines working, but as @HinoReo said, connections are not closing so they build up quickly.  In ~2 hours I've gone from ~60 connections, to ~1300.  my limit is 2500, which I will soon hit.  A workaround for me is to set my max_connections (`--db-max_connections` and in `my.conf`) to 10000, and use cron to restart my start script every few hours.

**Comment by HanSolo80** [comment]
@DeviantEng No, doesn't work for me. I have multiple workers that share the same db and so I divided the max_connections evenly between these workers. This causes to exceed the connections soon and nothing  works anymore. The cron restart is a workaround so I think we should fix the issue that the connections aren't closed. This is a very bad behavior anyway.

**Comment by DeviantEng** [comment]
@HanSolo80 I have 5 servers doing scan duty (each running 4-6 scans, with `-st 20` or `-st 30` with at least 100 PTC accounts per server), and my 6th server runs my DB and web frontend.  I like to think I have one of the bigger setups of this project.  

I haven't confirmed yet, but I think I have to restart mariadb to drop those connections, not just my scanners.  I use SaltStack to manage all 6 servers, and have a shell script managed by systemd to start all my scans.  I can easily restart everything from my web server.

Regardless, definitely need to get the issue fixed so those connections close when they're done.

**Comment by hannahbanana** [comment]
subscribing...

**Comment by Brian-Graham** [comment]
I'm not getting the exceeded maximum connections error but none of the scanner connections are being closed.

**Comment by Brian-Graham** [comment]
I felt I should point out that you guys should be running the following query to determine currently open connections: `show status like 'Threads_con%';`.

The `show status like 'Con%';` cquery only shows how many connections have existed since mysql was started.

**Comment by DeviantEng** [comment]
@Brian-Graham Oh, thanks for sharing that.  

Seems my `Threads_connected` are more around 40-60, while `Connections` are over 15000.  That would make sense considering those errors are gone after adding `--db-max_connections` to my runserver.py script.
