### ISSUE TITLE
Trouble With Python Code

### ISSUE THREAD

**Issue by thebrownzombie** [AHAAAAAAA/PokemonGo-Map#2762]
I am new to this Python business and I am getting stuck at the command:

python ./runserver.py --help

It keeps telling me that it is an invalid command, so I have tried taking out the ./ but it still shows its the wrong command. I have Python 2.7 and Pip installed just like the instructions said and I am trying the developer version of the pokemon go map. I have Python installed on the root of C and the maps are in a folder saved to the desktop.

Win7 + Android

**Comment by kylebrower** [comment]
My first guess is that you need to add python to your system environment variables. I thought this would occur at runtime but for me it did not.

[http://superuser.com/questions/143119/how-to-add-python-to-the-windows-path](http://superuser.com/questions/143119/how-to-add-python-to-the-windows-path)

**Comment by jhuberus** [comment]
did you try to put c:\Python27 in system settings/environment Variables/path I have seen a lot of people have problems with python with windows that didn't have c:\Python27 in path

**Comment by Incestosaurus** [comment]
Try: "C:\Python27" install -r requirements.txt

**Comment by boredcoding** [comment]
The easy way to verify the python executable is set as a variable in your operating systems environment is to open a command prompt and simply ask the system what version of python it's using:

`python --version`

If it can't find python it'll tell you. If you know it's installed, google something like:

"How to add python path to windows 10"

repeat.

**Comment by thebrownzombie** [comment]
So the environment variables were not added, so I was able to manually add C:\python27 and now when I went into a CMD window and typed python --version it did bring up the version which is 2.7.12. I tried to run the command of "python runserver.py --help" and it says "Traceback (most recent call last): File "runserver.py", line 14, in <module> from flash_cors import CORS ImportError: no Module named flask_cors"

Any idea on that one?

Thanks

**Comment by Kasmodan1** [comment]
There is a one-click setup for Windows. After you've installed Python, go into the Easy Setup folder and run setup.bat. This should install pip and the dependencies for you, and put your Google API key into the right place.

**Comment by boredcoding** [comment]
When you see the no module error it means that a dependency of the program is not installed or can't be found.

Dependencies are typically handled through a program named pip in python. On windows, pip is installed in versions > 2.7.9. Which you have.

So if you're missing the dependencies, you should install them with pip. Dependencies are listed in a requirements file, in the case of this app, they're in the root folder. The name of the file is requirements.txt

Open your windows explorer (the graphical gui you navigate around with to see files etc...) navigate to the root folder (the highest lvl folder with app contents) of the app, on the white space in the folder shift+right click and choose "open command window here". you'll get a cmd prompt in that directory.

then, verify pip is installed, which it should be.
```
pip --version
pip 1.5.6 from C:\Python27\lib\site-packages (python 2.7)
```

then, tell pip to install the application dependencies.

`pip install -r requirements.txt 
`

if for some reason pip is not installed, you can download it here:
https://pip.pypa.io/en/stable/installing/

then you run it using python.
`python get-pip.py`

If you're going to continue playing with python. This is a good place to start.
http://docs.python-guide.org/en/latest/

**Comment by thebrownzombie** [comment]
So got a little further, when I run the command of "pip install -r requirements.txt" and "npm install" it goes through the whole install but at the end gives this message:

"command "python setup.py egg_info" failed with error code 1 in c:\users\X\appdata\local\temp\pip-build-e1ba2i\pyproj\"

When I go to run the command "python ./runserver.py --help" it says:

"Traceback (most recent call last):
File "./runserver.py", line 14, in <modele>
from flask_cors import CORS
ImportError: No module named flash_cors"

It seems i am hung up at flash_cors. Any ideas?

Thanks

**Comment by boredcoding** [comment]
sometimes if pip isn't updated to the latest version, it has difficulty installing modules.

Try a:
`pip install -U pip`

This tells pip to upgrade itself. Been a while since I've done this in windows, but if i remember right, you will have to use a cmd prompt that has been opened in admin mode.

To do that hit windows key type cmd, right click it and run as administrator.

run the pip command to upgrade, then repeat the steps you used to install the requirements file.

FWIW, you can use the python interpreter to test if a module is installed, might save you a little time/frustration.

just run python / python.exe in a cmd prompt. and try to run the import manually. in this case.
`from flask_cors import CORS`

it'll bark at you if it failed, meaning the install attempt didn't work again. Or if it did work the you won't see anything, it'll just move to the next line.

ctrl + c to break out of the interpreter.

**Comment by thebrownzombie** [comment]
Thanks, i will try this when I get home.
