### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by Glitterbeam** [AHAAAAAAA/PokemonGo-Map#2769]
Traceback (most recent call last):
  File "runserver.py", line 9, in <module>
    from pogom.app import Pogom
  File "C:\Users\Nickolai\Desktop\pogom-master\pogom\app.py", line 13, in <module>
    from .search import set_cover
  File "C:\Users\Nickolai\Desktop\pogom-master\pogom\search.py", line 10, in <module>
    from geographiclib.geodesic import Geodesic
ImportError: No module named geographiclib.geodesic

^^^^ I have searched everywhere for a way to fix this problem, haven't seen anyone else with it.  Is there a step I'm missing in the installation?

Thanks

**Comment by Paralysing** [comment]
Try pip install geographiclib

**Comment by fehgab** [comment]
Run this one:
pip install -r requirements.txt
