### ISSUE TITLE
Unable to setup server on mac

### ISSUE THREAD

**Issue by zelin** [AHAAAAAAA/PokemonGo-Map#2870]
I am trying to setup the tool on my mac. 
## Expected Behavior
While installation i am getting this error

Muhammads-MBP:PokemonGo-Map Umar$ pip install -r requirements.txt 

Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 2))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 4))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r requirements.txt (line 5))
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 6))
  Using cached click-6.6.tar.gz
Collecting itsdangerous==0.24 (from -r requirements.txt (line 7))
  Using cached itsdangerous-0.24.tar.gz
Collecting peewee==2.8.1 (from -r requirements.txt (line 8))
  Using cached peewee-2.8.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7 (from -r requirements.txt (line 9))
Collecting geopy==1.11.0 (from -r requirements.txt (line 10))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 11))
  Using cached protobuf-2.6.1.tar.gz
Collecting requests==2.10.0 (from -r requirements.txt (line 12))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 13))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 14))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 15))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /private/var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/pip-build-UYvVxV/protobuf-to-dict/nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.2
    Downloading https://pypi.python.org/packages/f5/47/2e39972c41eb988d551bb2da25c4ee16ea78492ec1b6ffdf09f50cd09b92/coverage-4.2.zip#md5=9841c9e1ddc862144fda3fd7e5ba5106
    Processing coverage-4.2.zip
    Writing /var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/easy_install-ve9sIa/coverage-4.2/setup.cfg
    Running coverage-4.2/setup.py -q bdist_egg --dist-dir /var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/easy_install-ve9sIa/coverage-4.2/egg-dist-tmp-FcEV9U
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    
    Installed /private/var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/pip-build-UYvVxV/protobuf-to-dict/coverage-4.2-py2.7-macosx-10.11-intel.egg
    Searching for nose>=1.0
    Reading https://pypi.python.org/simple/nose/
    Best match: nose 1.3.7
    Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
    Processing nose-1.3.7.tar.gz
    Writing /var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/easy_install-AaCzHP/nose-1.3.7/setup.cfg
    Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/easy_install-AaCzHP/nose-1.3.7/egg-dist-tmp-cUvGJM
    no previously-included directories found matching 'doc/.build'
    
    Installed /private/var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/pip-build-UYvVxV/protobuf-to-dict/nose-1.3.7-py2.7.egg
    Searching for protobuf>=2.3.0
    Reading https://pypi.python.org/simple/protobuf/
    Best match: protobuf 3.0.0
    Downloading https://pypi.python.org/packages/e7/ff/df198f342f1b6e71be00a4601973297c0399f112327e8d5e48595ba95fe9/protobuf-3.0.0-py2.7.egg#md5=a2aa47b202784121a3d8ea17daee5e25
    Processing protobuf-3.0.0-py2.7.egg
    creating /private/var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/pip-build-UYvVxV/protobuf-to-dict/protobuf-3.0.0-py2.7.egg
    Extracting protobuf-3.0.0-py2.7.egg to /private/var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/pip-build-UYvVxV/protobuf-to-dict
    
    Installed /private/var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/pip-build-UYvVxV/protobuf-to-dict/protobuf-3.0.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yk/wxljrqt57wj72v7mcnmd_x500000gn/T/pip-build-UYvVxV/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))
    
## Your Environment
Mac OSX El Capitan

**Comment by polyisobutylene** [comment]
You need to run the pip command with root privileges, to do that just add sudo in from of the command:
```
sudo pip install -r requirements.txt
```
it will ask for your users password to elevate its permissions

**Comment by MichaelMartinez** [comment]
Zelin... Do you want to help develop the app or simply run the service/app? If you want the latter, Docker took less than 5 minutes to spin up and provide some interesting pokestops/gyms for my children and I to explore. Getting the API key from Google was the longest part...
