### ISSUE TITLE
No DB mode?

### ISSUE THREAD

**Issue by Monoblos** [AHAAAAAAA/PokemonGo-Map#2872]
I set up all dependencys except for a database.
In the wiki (https://github.com/AHAAAAAAA/PokemonGo-Map/wiki) it does not mention it as a requirement, however I can not start the server (with the example call) due to a peewee.OperationalError as it tries to connect the database.  
Is this a mistake in the wiki? Is there a option to disable the db? I don't need any persistence.

**Comment by jangrewe** [comment]
You don't need to "set up" a database. It creates the database file itself (unless you're telling it to use MySQL, in which case you need to provide all the info needed).

**Comment by Monoblos** [comment]
Well, not in my case. Here is the stack trace when it crashes:
```
C:\Program Files\PoGoMap>python2 runserver.py -st 10 -l "48.739630 9.307694"
Traceback (most recent call last):
  File "runserver.py", line 49, in <module>
    create_tables(db)
  File "C:\Program Files\PoGoMap\pogom\models.py", line 341, in create_tables
    db.connect()
  File "C:\Program Files (x86)\Python27\lib\site-packages\peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "C:\Program Files (x86)\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Program Files (x86)\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\peewee.py", line 3658, in _connect
    conn = sqlite3.connect(database, **kwargs)
peewee.OperationalError: unable to open database file
```

**Comment by moggoly** [comment]
Try using a different folder. Anything underneath C:\Program Files requires administrator privileges to create files.

**Comment by Monoblos** [comment]
Yes, just realized that was the issue.
Running it once with administrative privilliges to create the file solved the isse.
Thanks!
