### ISSUE TITLE
[HELP] Need help understanding error

### ISSUE THREAD

**Issue by Varatnar** [AHAAAAAAA/PokemonGo-Map#2876]
Right after the login attempt the program crash.
My knowledge about programming is not high enough for me to understand where the problem is.
Here is the code : 
```
$ python runserver.py -a google -u xxxxxx -p xxxxxx -t 1 -sd 5 -l "xxx -xxx"
2016-07-31 14:37:18,549 [    MainThread][     runserver] [   INFO] Parsed location is: xxx/xxx/0.0000 (lat/lng/alt)
2016-07-31 14:37:18,557 [    MainThread][        models] [   INFO] Connecting to MySQL database on x.x.x.x.
2016-07-31 14:37:18,575 [ search_thread][        search] [   INFO] Search loop 0 starting
2016-07-31 14:37:18,579 [ search_thread][        search] [   INFO] Attempting login to Pokemon Go.
Traceback (most recent call last):
  File "runserver.py", line 113, in <module>
2016-07-31 14:37:18,580 [ search_thread][   auth_google] [   INFO] Google login for: xxxxxx
    app.run(threaded=True, use_reloader=False, debug=args.debug, host=args.host, port=args.port)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 112] Address already in use
```
The problem have only started happening after i installed the last version (this error is happening in my old build too, it was working minutes before)
-I have kept both build (i do not know if this is relevant info)

**Comment by Dgc2002** [comment]
> socket.error: [Errno 112] Address already in use  
  
That means another process is already bound to the socket(address and port). You likely have an older process still running so you'll have to kill it.

**Comment by Varatnar** [comment]
I have just browsed quite a few pages on the internet and can confirm that you were right. I change the port for testing and it was running fine.

As far as i can tell i have no python process ongoing. Could it have a specific name ?
Because right now the port 5000 is simply unusable on my computer ... Will it ever timeout ? Is there a way to forcefully close this port ?

**Comment by Varatnar** [comment]
The port was eventually freed, I assume some sort of timeout happened.

Closing this, no clue what caused the socket to stay open, probably a "frame perfect" manual interrupt ..
