### ISSUE TITLE
No module named protobuf.internal

### ISSUE THREAD

**Issue by Kai4615** [AHAAAAAAA/PokemonGo-Map#2890]
Kais-Air:PokemonGo-Map-master Kai$ python runserver.py -a google -u ***************** -p *********** -st 100 -k ************************* -l "37.787933, -122.407440" 
Traceback (most recent call last):
  File "runserver.py", line 15, in <module>
    from pogom.search import search_loop, create_search_threads, fake_search_loop
  File "/Users/Kai/Desktop/PokemonGo-Map-master/pogom/search.py", line 23, in <module>
    from pgoapi import PGoApi
  File "/Users/Kai/Desktop/PokemonGo-Map-master/pogom/pgoapi/__init__.py", line 1, in <module>
    from pgoapi      import *
  File "/Users/Kai/Desktop/PokemonGo-Map-master/pogom/pgoapi/pgoapi.py", line 28, in <module>
    from utilities import f2i
  File "/Users/Kai/Desktop/PokemonGo-Map-master/pogom/pgoapi/utilities.py", line 31, in <module>
    from google.protobuf.internal import encoder
ImportError: No module named protobuf.internal
Kais-Air:PokemonGo-Map-master Kai$

**Comment by Paralysing** [comment]
Try pip install protobuf

**Comment by danielhampton** [comment]
Have you run

`pip install -r requirements.txt`

(While in the root of the map directory)

**Comment by Kai4615** [comment]
Yes

`Requirement already satisfied`
