### ISSUE TITLE
having problems with the new version of pokemonGo-Map

### ISSUE THREAD

**Issue by Rawr2134** [AHAAAAAAA/PokemonGo-Map#2913]
So I am new to this whole thing and am kind of stuck...I cant seem to find any other information on how to fix it. any help is appreciated.

Here is what i am getting:
D:\User\Downloads\PokemonGo-Map-master>C:\python27\python.exe runserver.py -u Username -p Password -st 10 -k GMAPS API KEY -l "COORDS" -H 0.0.0.0 -P 5000
Traceback (most recent call last):
File "runserver.py", line 15, in 
from pogom.search import search_loop, create_search_threads, fake_search_loop
File "D:\User\Downloads\PokemonGo-Map-master\pogom\search.py", line 23, in 
from pgoapi import PGoApi
File "D:\User\Downloads\PokemonGo-Map-master\pogom\pgoapi__init__.py", line 1, in 
from pgoapi import *
File "D:\User\Downloads\PokemonGo-Map-master\pogom\pgoapi\pgoapi.py", line 32,
in 
from auth_google import AuthGoogle
File "D:\User\Downloads\PokemonGo-Map-master\pogom\pgoapi\auth_google.py", line 27, in 
from gpsoauth import perform_master_login, perform_oauth
File "C:\python27\lib\site-packages\gpsoauth__init__.py", line 4, in

from . import google
File "C:\python27\lib\site-packages\gpsoauth\google.py", line 4, in 
from Cryptodome.PublicKey import RSA
File "C:\python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in
from Cryptodome.IO import PKCS8, PEM
File "C:\python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in 
from Cryptodome.IO.PBES import PBES1, PBES2, PbesError
File "C:\python27\lib\site-packages\Cryptodome\IO_PBES.py", line 44, in 
from Cryptodome.Cipher import DES, ARC2, DES3, AES
File "C:\python27\lib\site-packages\Cryptodome\Cipher__init_.py", line 78, in 
from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
File "C:\python27\lib\site-packages\Cryptodome\Cipher_mode_ecb.py", line 46,in 
"""
File "C:\python27\lib\site-packages\Cryptodome\Util_raw_api.py", line 168, in
load_pycryptodome_raw_lib
raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

**Comment by excitedbox** [comment]
run the setup file in the tools directory

**Comment by Rawr2134** [comment]
ok so i ran the setup file in the tools directory, but it still returns the same stuff. is there a way to do a fresh install or something? i feel like i may have missed a step someplace, but i'm not sure

**Comment by NoMotion** [comment]
Looks like you're missing a cryptography python library try running pip install -r requirements.txt again

**Comment by Rawr2134** [comment]
Ok so i ran the pip install again, is it asking me to upgrade? or is it telling me that its ok? 

If i run the setup and get-pip in tools directory, it tells me the requirement is already up to date

D:\User\Downloads\PokemonGo-Map-master>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\py
thon27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\pyth
on27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:
\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c
:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): configargparse==0.10.0
 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\pytho
n27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in
c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in c:\py
thon27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in c:\p
ython27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\py
thon27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in c:\
python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:
\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\
python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\
python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.
0 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): PyMySQL==0.7.5 in c:\p
ython27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in c
:\python27\lib\site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): flask-compress==1.3.0
in c:\python27\lib\site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\pytho
n27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\
lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in
c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 1
4))
Requirement already satisfied (use --upgrade to upgrade): Six in c:\python27\lib
\site-packages (from flask-cors==2.1.2->-r requirements.txt (line 17))

D:\User\Downloads\PokemonGo-Map-master>
