### ISSUE TITLE
Pokemon Not Showing. Only showing: Pokestops and Gyms

### ISSUE THREAD

**Issue by shermsaludez** [AHAAAAAAA/PokemonGo-Map#2919]
## Expected Behavior
Should be able to **scan pokemon** and **scanned locations "hexagons"**

## Current Behavior
I have made my beehive.bat with:
 `python location_generator.py -lat -33.9 -lon 151.1 -st 5 -lp 3 --accounts C:\Documents\accounts.csv --windows --installdir="C:\Downloads\PokemonGo-Map"
`
I followed the Instuctions for location_generator.txt
I have made 1000 PTC accounts, only used 400
With the code above i was able to generate a beehive.bat

This is my line of code, everything else is repeated

> taskkill /IM python.exe /F
> Start "Server" /d C:\Users\Sherman\Desktop\PokemonGo-Map-develop /MIN E:\Python27\python.exe 
>  C:\Users\Sherman\Desktop\PokemonGo-Map-develop\runserver.py -os -l "43.826969 -79.27214" -st 4 -t 1 -sd 5 ping 127.0.0.1 -n 6 > nul

```
Start "Movable0" /d C:\Users\Sherman\Desktop\PokemonGo-Map-develop /MIN E:\Python27\python.exe C:\Users\Sherman\Desktop\PokemonGo-Map-develop\runserver.py -a google -u saludezfam0 -p "ip07cu4u" -ns -l "43.826969 -79.27214" -st 4 -t 1 -sd 5
ping 127.0.0.1 -n 6 > nul
```

## Possible Solution
API Key? 
Number of steps used?
Scan delay used?

## Your Environment

Python 2.7
Windows 10

**Comment by HusbandoMax** [comment]
What colour are you scan circles?

**Comment by shermsaludez** [comment]
@HusbandoMax  i dont have any scanned circles, cause i can't see them! lol thats my problem

**Comment by pokegothrow** [comment]
Check your computer's clock! I had the same problem, because of a time-zone issue when I dual boot Windows.

If your time is wrong, the pokemons will be considered "outdated" and will simply not be drawn by the javascript code in the browser.

Hope that helps!

**Comment by shermsaludez** [comment]
@pokegothrow  my computer clock looks fine to me?? Date good, time good, it's on EST as well

**Comment by pokegothrow** [comment]
Could also be  your server or VM's clock that is wrong then?

**Comment by nolany** [comment]
I am having this same issue. If I leave the Pokemon switch to off then everything works fine, including scans, which are green BTW. I have checked the server clock as well and it is synced up with there I am searching. As soon as I turn on the Pokemon scanning this happens on my server CLI. Ubuntu 14.04 BTW. And I have attempted removing all pip packages and re installing them, as well as wiping the entire git repo on my server and recreating it. 

`2016-07-31 20:30:48,537 [     Thread-22][           app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/panda/PokemonGo-Map/pogom/app.py", line 81, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "/home/panda/PokemonGo-Map/pogom/models.py", line 96, in get_active
    p['pokemon_name'] = get_pokemon_name(p['pokemon_id'])
  File "/home/panda/PokemonGo-Map/pogom/utils.py", line 248, in get_pokemon_name
    return i8ln(get_pokemon_data(pokemon_id)['name'])
  File "/home/panda/PokemonGo-Map/pogom/utils.py", line 244, in get_pokemon_data
    get_pokemon_data.pokemon = json.loads(f.read())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")`

**Comment by shermsaludez** [comment]
@pokegothrow  im stupid i had it set to -a google, i replaced it with PTC now it's working. Now im trying to figure out how to get MariaDB working so i can use mysqlite.... but im not able to connect to localhost:5000 now

**Comment by Scalpweb** [comment]
Hum, sorry for the out-of-subject question, but what did you use to make 1000 PTC account ?
