### ISSUE TITLE
MacOS Sierra Installation issue

### ISSUE THREAD

**Issue by mexyn** [AHAAAAAAA/PokemonGo-Map#3001]
I followed the setup instructions of the wiki. Everything worked except the startup of the server. I used the following command:

python runserver.py -a google -u mygooglelogin -p mygooglepw -st 5 -k mygoogleapikey -l "any location string"

## Expected Behavior
Server starts up without any error and i'm able to open the map locally

## Current Behavior
I'm getting the following error:

```
Traceback (most recent call last):
  File "runserver.py", line 49, in <module>
    create_tables(db)
  File "/Users/mexyn/Documents/projects/pokelocal/pogom/models.py", line 341, in create_tables
    db.connect()
  File "/Users/mexyn/Documents/projects/pokelocal/venv/lib/python2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/Users/mexyn/Documents/projects/pokelocal/venv/lib/python2.7/site-packages/peewee.py", line 3657, in _connect
    raise ImproperlyConfigured('pysqlite or sqlite3 must be installed.')
peewee.ImproperlyConfigured: pysqlite or sqlite3 must be installed.
```

pip list gives the following:
```
click (6.6)
ConfigArgParse (0.10.0)
Flask (0.11.1)
Flask-Compress (1.3.0)
Flask-Cors (2.1.2)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
peewee (2.8.1)
pip (8.1.2)
protobuf (2.6.1)
protobuf-to-dict (0.1.0)
pycryptodomex (3.4.2)
PyMySQL (0.7.5)
pysqlite (2.8.2)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (25.1.1)
six (1.10.0)
Werkzeug (0.11.10)
wheel (0.29.0)
```

**Comment by nickg819** [comment]
How is it that I got no pysqlite on my Sierra install? 

`click (6.6)
ConfigArgParse (0.10.0)
Flask (0.11.1)
Flask-Compress (1.3.0)
Flask-Cors (2.1.2)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
itsdangerous (0.24)
Jinja2 (2.8)
LatLon (1.0.1)
MarkupSafe (0.23)
peewee (2.8.1)
pip (8.1.2)
protobuf (2.6.1)
protobuf-to-dict (0.1.0)
pycryptodomex (3.4.2)
PyMySQL (0.7.5)
pyproj (1.9.5.1)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (25.1.3)
six (1.10.0)
Werkzeug (0.11.10)
wheel (0.29.0)
`
