### ISSUE TITLE
Error while "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by Supsuop** [AHAAAAAAA/PokemonGo-Map#3044]
Hello there,
I'm getting an error when i am trying to install requirements and don't know how to fix it.

```
  Failed building wheel for pycryptodomex
  Running setup.py clean for pycryptodomex
Failed to build pycryptodomex
Installing collected packages: itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, Flask, configargparse, peewee, geopy, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, protobuf-to-dict, PyMySQL, Six, flask-cors, flask-compress
Exception:
Traceback (most recent call last):
  File "/home/pokemon/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/pokemon/.local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/pokemon/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/home/pokemon/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/pokemon/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/home/pokemon/.local/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/pokemon/.local/lib/python2.7/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/itsdangerous.py'
```

**Comment by HibikiFox** [comment]
1) another Python script is running (-if windows- open task manager and kill anything that is python.exe /  -if Lunix.... someone help?)
2) you are not running the command from an elevated prompt (IE as admin or SuDo)

**Comment by Znuff** [comment]
`sudo`

**Comment by Supsuop** [comment]
I'm using Linux Ubuntu 16.04.
when i run the command as sudo i get
```
The directory '/home/pokemon/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/pokemon/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```
is this massage difficult?
