### ISSUE TITLE
The browser does not display the Pokemon

### ISSUE THREAD

**Issue by princeomlet** [AHAAAAAAA/PokemonGo-Map#305]
Mac OS 10.11.5

Terminal: python example.py -a ptc -u princemap -p **** -l "Balashikha" -st 5

when the lopping range up to 100% I turn the browser and Pokémons are not displayed on the map. In this case, the terminal reports the following error

### Logs
<img width="840" alt="2016-07-19 12 42 41" src="https://cloud.githubusercontent.com/assets/20522034/16945595/534d4df6-4dae-11e6-8f34-4e35f7d328f7.png">

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 27: ordinal not in range(128)

**Comment by DerScreever** [comment]
do git pull and get the latest version.
this was fixed already some time ago. for me all work.

**Comment by princeomlet** [comment]
@DerScreever i get latest version and this bug still here

**Comment by DerScreever** [comment]
pls post the command you use to start the server.

**Comment by DerScreever** [comment]
pls do git pull and try again.
we merged a fix for é letter

**Comment by maximal** [comment]
Got the same issue with latest code.

`-dp -dg "Moscow, Russia" -st 5`

**Comment by maximal** [comment]
Any static file returns the error:
http://127.0.0.1:5000/static/forts/Mystic.png

![2016-07-19 13-55-39](https://cloud.githubusercontent.com/assets/980679/16947563/7e2ac742-4db8-11e6-9f37-1d6147b09c51.png)

**Comment by maximal** [comment]
You should use Unicode in order to work with non-latin pathes.

**Comment by EstherMartz** [comment]
Same issue here :/

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 15: ordinal not in range(128)
127.0.0.1 - - [19/Jul/2016 17:56:43] "GET /static/icons/133.png HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask/helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Python/2.7/site-packages/flask/helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "/Library/Python/2.7/site-packages/flask/helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 15: ordinal not in range(128)`

**Comment by princeomlet** [comment]
Use only the English folder names
