### ISSUE TITLE
[Errno 2] No such file or directory: '/var/www/go.chutastic.com/htdocs/tommy.chutastic.com/PokemonGo-Map/static/dist/data/pokemon.min.json'

### ISSUE THREAD

**Issue by xomikronx** [AHAAAAAAA/PokemonGo-Map#3058]
Updated from the lates changes in develop branch.

Getting the following error:
`2016-08-01 16:14:59,618 [       Thread-77][           app][   ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/SOMEDOMAIN/htdocs/SOMEDOMAIN/PokemonGo-Map/pogom/app.py", line 87, in raw_data
    d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng)
  File "/var/www/SOMEDOMAIN/htdocs/SOMEDOMAIN/PokemonGo-Map/pogom/models.py", line 96, in get_active
    p['pokemon_name'] = get_pokemon_name(p['pokemon_id'])
  File "/var/www/SOMEDOMAIN/htdocs/SOMEDOMAIN/PokemonGo-Map/pogom/utils.py", line 248, in get_pokemon_name
    return i8ln(get_pokemon_data(pokemon_id)['name'])
  File "/var/www/SOMEDOMAIN/htdocs/SOMEDOMAIN/PokemonGo-Map/pogom/utils.py", line 243, in get_pokemon_data
    with open(file_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '/var/www/SOMEDOMAIN/htdocs/SOMEDOMAIN/PokemonGo-Map/static/dist/data/pokemon.min.json'`

## Expected Behavior
You should see in logs

## Current Behavior
lots of errors

## Possible Solution
missing file?

## Steps to Reproduce (for bugs)
update to latest changes
run runserver.py

## Your Environment
CentOS7

**Comment by MRokas** [comment]
Download+install node.us
Run:
`npm install && npm install -g grunt && grunt`
