### ISSUE TITLE
Python.exe problem can't load localhost

### ISSUE THREAD

**Issue by tv101** [AHAAAAAAA/PokemonGo-Map#3060]
Hi guys,

First of all i'm new to coding and thanks to the help of the wiki's you provided even i was able to produce my own pokemon server. I had it all set up including beehive, the only thing i had to do was tap on the beehive icon and everything worked like a charm. 
Tonight i wanted to start up my servers and the first thing i noticed was that there was a error: ERROR: the process ''python.exe'' not found. I immediately checked if the path for python was still correct and it was exactly the same as stated in the wiki. 
Then i tried to connect to the localhost:5000 to see if it would show anything but i couldn't even reach the localhost. Even though i could see that the movable's i made where able to login to the ptc server and collect data.

I really don't know what i'm missing hopefully somebody can help.

\_(notice: that i didn't make any changes during the last time when everything worked and tonight were it seems to fail)._

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET PythonPath=  C:\Python27\Python.exe

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET BranchPath=  C:\Users\T\Desktop\map1\PokemonGo-Map

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET Executable=runserver.py

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET GAPI=  ****

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET auth=  PTC

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username1= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username2= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username3= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username4= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username5= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username6= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username7= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET username8= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET password= ***

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET thread=-t 1

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>SET locale=EN

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>taskkill /IM python.exe /F
ERROR: The process "python.exe" not found.

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>echo Starting worker processes....
Starting worker processes....

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>title Pokemon Go Map

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>Start "Movable1" /d   C:\Users\T\Desktop\map1\PokemonGo-Map /MIN   C:\Python27\Python.exe   runserver.py   -a   PTC -u  *** -p  *** -l "***" -st 5 -H 0.0.0.0 -P 5000 -k   *** -L EN   -t 1

C:\Users\T\Desktop\map1\PokemonGo-Map\Tools\Hex-Beehive-Generator>ping 127.0.0.1 -n 6
                                                                         1>nul

## Your Environment

* Version used:
Python 2.7
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Windows 10

**Comment by tv101** [comment]
I just run in to a second problem. I tried to run the server without the beehive but i got another error. I don't know if it has anything to do with the previous error while runnig beehive. 

C:\Users\T>cd C:\Users\T\Desktop\map1\PokemonGo-Map

C:\Users\T\Desktop\map1\PokemonGo-Map>python runserver.py -a ptc -u ***-p ***-l "400 Broad St, Seattle, WA 98109, USA" -st 5
2016-08-02 11:15:16,595 [     runserver] [   INFO] Parsed location is: 47.6205/-122.3491/0.0000 (lat/lng/alt)
2016-08-02 11:15:16,595 [        search] [   INFO] Search loop 0 starting
2016-08-02 11:15:16,609 [        search] [   INFO] Attempting login to Pokemon Go.
Traceback (most recent call last):
  File "runserver.py", line 99, in <module>
2016-08-02 11:15:16,625 [      auth_ptc] [   INFO] PTC login for: ***
    app.run(threaded=True, use_reloader=False, debug=args.debug, host=args.host, port=args.port)
  File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
    inner()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 656, in inner
    fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "C:\Python27\lib\SocketServer.py", line 417, in __init__
    self.server_bind()
  File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "C:\Python27\lib\SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013] An attempt was made to access a socket in a way forbidden by access permissions
