### ISSUE TITLE
Map not loading when accessing URL

### ISSUE THREAD

**Issue by pokesense** [AHAAAAAAA/PokemonGo-Map#3068]
Hi,

For some reason when we try to access our maps, both locally and externally on http://maps.pokesense.com/, the top header loads, but the main map itself doesn't load up.

We are getting the below errors from the google chrome console:
![maps](https://cloud.githubusercontent.com/assets/20782033/17310749/482e3152-583e-11e6-83c7-cc5870b04fc5.png)

The server itself is running without any issues.

* Version used:
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows server 2012R2 Running IIS 8 - Desktop + Mobile

**Comment by Maxsky5** [comment]
Did you try a `grunt build` ?

**Comment by itztq** [comment]
Same issue 

Failed to load resource: the server responded with a status of 404 (NOT FOUND)
2http:/(IP)/static/dist/js/map.min.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://(IP) /static/dist/js/stats.min.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
js?
key=xxx&callback=initMap&libraries=places,geometry:97 Uncaught InvalidValueError: initMap is not a function

**Comment by pokesense** [comment]
Maxsky5: Done that and now we are getting some different errors as below:

![maps2](https://cloud.githubusercontent.com/assets/20782033/17311796/e03b47c6-5845-11e6-929a-277922cf278b.png)

**Comment by itztq** [comment]
@pokesense 

try to run 

npm install babel-preset-es2015 --save
npm install babel-preset-react --save

**Comment by pokesense** [comment]
Hey,

Tried that and it didn't work. Below is the screenshot of errors I am now getting:

![map3](https://cloud.githubusercontent.com/assets/20782033/17312426/7abbf29c-584a-11e6-8b0d-1024ab6e9e60.png)

**Comment by itztq** [comment]
@pokesense 

which branch do you run dev or Master map?

**Comment by pokesense** [comment]
Currently running the master map

**Comment by pokesense** [comment]
Hmm,

Just moved it over the the linux box and when I try to ru the runserver.py file I get the following:

Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/home/pokesense/domains/pokesense.com/public_html/maps/pogom/app.py", line 11, in <module>
    from s2sphere import *
  File "/usr/lib/python2.6/site-packages/s2sphere/__init__.py", line 5, in <module>
    from .sphere import *
  File "/usr/lib/python2.6/site-packages/s2sphere/sphere.py", line 12, in <module>
    @functools.total_ordering
AttributeError: 'module' object has no attribute 'total_ordering'

**Comment by andreblue** [comment]
What did you do to install the map? I have just installed it about 5 minutes ago on a deb 8 box with no issues

**Comment by pokesense** [comment]
Good morning,

To install the map, I simply downloaded the zip file from github and then uploaded the contents of it to my servers FTP address.

**Comment by andreblue** [comment]
You did rum the pip command like it says?
If so run it again and post the output. Make sure it is ran on the server

**Comment by pokesense** [comment]
Below are the last few commands I have ran:

![maps4](https://cloud.githubusercontent.com/assets/20782033/17324575/1cd67fb2-589f-11e6-8124-49d0d4c146d0.png)

**Comment by andreblue** [comment]
Does the maps console have any errors in it and what system of Linux are you on?

**Comment by pokesense** [comment]
Below are the errors I get from the Google Chrome console:

![maps5](https://cloud.githubusercontent.com/assets/20782033/17325194/3a7137da-58a2-11e6-8a70-8e1601b7f1e9.png)

I am running Centos 6.

**Comment by andreblue** [comment]
From the Linux box. Where is spams things like pokemon upserted

**Comment by pokesense** [comment]
Apologies,

No there are no errors there, it is just happily ticking away updating the pokemon, pokestops and gyms.

**Comment by pokesense** [comment]
Seem to have gotten a bit further now. If I access http://maps.pokesense.com:5000/ it loads, however if I remove the 5000 it doesn't work. If I set the port to 80 in the config file then the server refuses to start.

**Comment by pokesense** [comment]
When going to maps.pokesense.com it is loading an index.html file which is a copy of the maps.html file that is in Templates folder.

**Comment by Maxsky5** [comment]
I know nothing about IIS, but i remember a friend had same kind of problem with Apache. He was missing a / in the proxy settings.
Can you show us your proxy settings ?

**Comment by andreblue** [comment]
Are you using apache, nginx or something else for the webserver to bring it to port 80?

If you are using apache, i suggest this: https://gist.github.com/andreblue/956dc6bee599d5ae3509c2476c1a80bf

You can un comment the proxy stuff if you want it to be password protected.

Simply create this in the apache config files, https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-centos-6 has some info on doing so. 

Make sure to enable mod_proxy_http and mod_proxy

**Comment by c133** [comment]
I have a similar issue on my OVH vps. 
In my beehive.sh, I have 1 server and then the rest are workers with no server:

nohup python runserver.py -u 1 -p -os -ng -nk -k key -os -l 'location' -H 0.0.0.0 -P 80  & sleep 0.5; 
nohup python runserver.py -u 2 -p -ns -ng -nk -k key -os -l 'location' -H 0.0.0.0 -P 80  & sleep 0.5; 
nohup python runserver.py -u 3 -p -ns -ng -nk -k key -os -l 'location' -H 0.0.0.0 -P 80  & sleep 0.5;

When I start beehive.sh, the map loads and everything works, however after a while (I have ~100 workers scanning) the map breaks and I get:

<img width="671" alt="screen shot 2016-08-03 at 11 29 54 am" src="https://cloud.githubusercontent.com/assets/5353882/17373492/0fb369f6-596e-11e6-9d80-7b042689c217.png">

To @andreblue @itztq @Maxsky5 @pokesense,
Can anyone tell me how to fix this? 
Do I need to use a different -H or -P? I feel like the problem is because I am using port 80 but I haven't done anything to "bring it to port 80" like @andreblue mentioned, and I have no idea if my server is using apache, nginx or etc.

I just want to start server + workers and access the map from mydomain.com to see the map, without it eventually breaking and giving 404 for app.min.css and .js files.

**Comment by andreblue** [comment]
What os are you running?

**Comment by Maxsky5** [comment]
Type "netstat -anp | grep :80" to know what is listening on port 80.
