### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by flickerstop** [AHAAAAAAA/PokemonGo-Map#3086]
Currently unable to run the map on a fresh install of Ubuntu 14.10. I've tried everything to make it run, installed, uninstalled, reinstalled.... Nothing seems to solve this problem.

Python 2.7.8
Ubuntu 14.10

root@ubuntu:~/PokemonGo-Map# python ./runserver.py --help
Traceback (most recent call last):
  File "./runserver.py", line 14, in <module>
    from queue import Queue
ImportError: No module named queue

**Comment by JonLim** [comment]
Are you hosting this locally?

If so, make sure you do `pip install -r requirements.txt`, per [setup instructions](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Development).

**Comment by flickerstop** [comment]
I am hosting this locally, I've ran that and I get the error 

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9lWM1_/protobuf-to-dict/
`

**Comment by JonLim** [comment]
A quick google turns up this [StackOverflow answer](http://stackoverflow.com/questions/17886647/cant-install-via-pip-because-of-egg-info-error). Hope it helps!

**Comment by flickerstop** [comment]
Didn't solve any problems. Thanks for the link though!

**Comment by NoMotion** [comment]
You might be missing a dependency however Queue comes with python 2.7. You might want to make sure you are using the right version of python. Try typing the full real path of python 2.7

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9lWM1_/protobuf-to-dict/
This looks like a dependency issue as well run `pip install protobuf-to-dict` and see if it goes away

**Comment by flickerstop** [comment]
You mean something like this?

`/usr/bin/python ./runserver.py --help`

The install path of my python is `/usr/bin/python` and checking the version gives me the correct 2.7.8.

Attempting that pip install gives me this
```

root@ubuntu:~# pip install protobuf-to-dict
Collecting protobuf-to-dict
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs/nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Downloading https://pypi.python.org/packages/f5/47/2e39972c41eb988d551bb2da25c4ee16ea78492ec1b6ffdf09f50cd09b92/coverage-4.2.zip#md5=9841c9e1ddc862144fda3fd7e5ba5106
    Best match: coverage 4.2
    Processing coverage-4.2.zip
    Writing /tmp/easy_install-SshSyz/coverage-4.2/setup.cfg
    Running coverage-4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SshSyz/coverage-4.2/egg-dist-tmp-XX7WB0
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    creating /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs/coverage-4.2-py2.7-linux-x86_64.egg
    Extracting coverage-4.2-py2.7-linux-x86_64.egg to /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs
    
    Installed /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs/coverage-4.2-py2.7-linux-x86_64.egg
    Searching for nose>=1.0
    Reading https://pypi.python.org/simple/nose/
    Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
    Best match: nose 1.3.7
    Processing nose-1.3.7.tar.gz
    Writing /tmp/easy_install-PjDXea/nose-1.3.7/setup.cfg
    Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-PjDXea/nose-1.3.7/egg-dist-tmp-sh5dek
    no previously-included directories found matching 'doc/.build'
    creating /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs/nose-1.3.7-py2.7.egg
    Extracting nose-1.3.7-py2.7.egg to /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs
    
    Installed /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs/nose-1.3.7-py2.7.egg
    Searching for protobuf>=2.3.0
    Reading https://pypi.python.org/simple/protobuf/
    Downloading https://pypi.python.org/packages/e7/ff/df198f342f1b6e71be00a4601973297c0399f112327e8d5e48595ba95fe9/protobuf-3.0.0-py2.7.egg#md5=a2aa47b202784121a3d8ea17daee5e25
    Best match: protobuf 3.0.0
    Processing protobuf-3.0.0-py2.7.egg
    creating /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs/protobuf-3.0.0-py2.7.egg
    Extracting protobuf-3.0.0-py2.7.egg to /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs
    
    Installed /tmp/pip-build-0HV23r/protobuf-to-dict/.eggs/protobuf-3.0.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0HV23r/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 348, in __init__
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 394, in fetch_build_eggs
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 826, in resolve
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1091, in best_match
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 695, in find
    pkg_resources.VersionConflict: (six 1.7.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0HV23r/protobuf-to-dict/
```

**Comment by NoMotion** [comment]
Looks like you're going to have to play the dependency game like i did. 
`pkg_resources.VersionConflict: (six 1.7.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))
`
This means you need to upgrade six package. `pip install --upgrade six`

**Comment by flickerstop** [comment]
Thank you sooo much! `python ./runserver.py --help` now works perfectly! Problem has been solved.

**Comment by NoMotion** [comment]
Glad it works! Please close this issue
