### ISSUE TITLE
error installing with dev build for mysql

### ISSUE THREAD

**Issue by cmills47** [AHAAAAAAA/PokemonGo-Map#3094]
I am on Windows and trying to run the easy setup wizard on the dev download and adjust the config.ini to allow for MySQL usage.  Unfortunately, I am getting an error on the easy install script, and then when I try to run the program it fails with a different error, presumably caused by the install issue.

Any help or suggestions would be appreciated!

## Current Behavior
running setup, I get this error before it asks me to enter my google api key:

Collecting LatLon==1.0.1 (from -r requirements.txt (line 19))
  Using cached LatLon-1.0.1-py2-none-any.whl
Collecting setuptools (from protobuf==2.6.1->-r requirements.txt (line 11))
  Downloading setuptools-25.1.2-py2.py3-none-any.whl (442kB)
    100% |################################| 450kB 578kB/s
Requirement already up-to-date: future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 13))
Requirement already up-to-date: pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 14))
Requirement already up-to-date: Six in c:\python27\lib\site-packages (from flask-cors==2.1.2->-r requirements.txt (line 17))
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 19))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\chad\appdata\local\temp\pip-build-vps2qn\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1103, in return_env
        [self.VCIncludes,
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 811, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 541, in VCInstallDir
        python_vc = self.ri.lookup(reg_path, 'installdir')
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 451, in lookup
        bkey = winreg.OpenKey(hkey, key, 0, winreg.KEY_READ)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\chad\appdata\local\temp\pip-build-vps2qn\pyproj\

when I try to run the server, I get this error (note: sensitive variables edited out in brackets, but copied over from my run on the non-dev version which works fine):
C:\PokemonMap\PokemonGo-Map-develop\PokemonGo-Map-develop>python runserver.py -a google -u [account] -p [password] -st 40 -k [key] -l [location]
2016-08-01 19:16:59,335 [    MainThread][     runserver] [CRITICAL] Please run "grunt build" before starting the server.

C:\PokemonMap\PokemonGo-Map-develop\PokemonGo-Map-develop>

If I run "grunt build" grunt isn't recognized as a command in Windows.  Is this a python script I need to run perhaps?  Or maybe something I just need to add to my path?  Or my fear is it's a Linux thing there's no equivalent for...

## Context
I've downloaded the dev build in order to use MySQL so I can build a DB and query that to learn about stats and analyze them.

I have installed MariaDB successfully but since the dev build is required for that and I haven't gotten that working yet, I can't test that out.  I initially tried doing both updates at once (using dev download, MySQL settings in one update) but since I got these errors I reverted back to just using my old setup that was working on the release build but on the dev build (i.e. not using MySQL).  I'm hoping to get the dev build working so I can then experiment with MySQL and ideally an API hook.

## Your Environment
* Version used: PokemonGo-Map-develop
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Win10 desktop / Surface Book

**Comment by Poeles** [comment]
Getting the same error when I run pip install -r requirements.txt.
Dev Branch, python 2.7 and running on Windows 7.

**Comment by cmills47** [comment]
Hmm...well, on the bright side, I tried running the MySQL stuff on the non-dev (master) branch I was already using and it seems to work just fine.  Maybe the changes in dev needed to run the MySQL stuff have already been integrated into the main build and it's no longer necessary to use dev anyway?

**Comment by Grifan** [comment]
> Getting the same error when I run pip install -r requirements.txt. Dev Branch, python 2.7 and running on Windows 7.
Same problem

**Comment by k4n30** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3277#issuecomment-237156671 #3277 

This should be updated in the wiki / install instructions
