### ISSUE TITLE
Issue while install dependencies

### ISSUE THREAD

**Issue by Brenza** [AHAAAAAAA/PokemonGo-Map#3135]
I completed all the previuos steps correctly but then i get this...
Seems like one of the files got pulled from pypi.python.org

C:\Users\user\Desktop\PokemonGo-Map-develop>pip install -r requirements.txt
Collecting six==1.10.0 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connec
tion broken by 'ProtocolError('Connection aborted.', error(10054, 'An existing c
onnection was forcibly closed by the remote host'))': /simple/six/
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 3))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 5))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r requirements.txt (line 6))
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 7))
  Using cached click-6.6.tar.gz
Collecting itsdangerous==0.24 (from -r requirements.txt (line 8))
  Using cached itsdangerous-0.24.tar.gz
Collecting peewee==2.8.1 (from -r requirements.txt (line 9))
  Using cached peewee-2.8.1.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 10))
  Using cached wsgiref-0.1.2.zip
Collecting geopy==1.11.0 (from -r requirements.txt (line 11))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 12))
  Using cached protobuf-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\user\appdata\local\temp\2\pip-build-ypimw7\protobuf\setup.p
y", line 200, in <module>
        "Protocol Buffers are Google's data interchange format.",
      File "c:\python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 269, in __in
it__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 313, in fetc
h_build_eggs
        replace_conflicting=True,
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 826,
in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1092,
 in best_match
        return self.obtain(req, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1104,
 in obtain
        return installer(requirement)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 380, in fetc
h_build_egg
        return cmd.easy_install(req)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 628, in easy_install
        not self.always_copy, self.local_index
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 615
, in fetch_distribution
        return dist.clone(location=self.download(dist.location, tmpdir))
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 531
, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 772
, in _download_url
        return self._attempt_download(url, filename)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 778
, in _attempt_download
        headers = self._download_to(url, filename)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 678
, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 728
, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://pypi.python.org/
packages/e4/a9/05540567740506890677937aff845bc02e17c3d4cf9bf59eb92ea3dc054b/goog
le_apputils-0.4.2-py2.7.egg#md5=38b003cf8b73264340ffa8beeafaaf84: [Errno 10054]
An existing connection was forcibly closed by the remote host

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\user\app
data\local\temp\2\pip-build-ypimw7\protobuf\

**Comment by felixvd** [comment]
Have you tried doing it again?

**Comment by navarr** [comment]
I am also getting this issue on Debian - Linux 2.6.32-042stab108.8 x86_64

**Comment by Brenza** [comment]
Yes, the issue has been present for a couple days right now.. I obviously downloaded the last zip anytime I tried but nothing changed =(

**Comment by meliorit** [comment]
I needed Microsoft Visual C++ Compiler for Python 2.7 ( [http://aka.ms/vcpython27](url) ) to resolve this error.

**Comment by Brenza** [comment]
Thank you @meliorit , I installed the compiler but unfortunately the error persist :(
Any other suggestion?
