### ISSUE TITLE
Develop Branch issue

### ISSUE THREAD

**Issue by 1111121RicardoBrandao** [AHAAAAAAA/PokemonGo-Map#3143]
File not found (pokemon.min.js)

## Expected Behavior

When run the develop branch, i cant run it more than one minute, im always getting this issue

Exception in thread search_worker_0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File ".../pogom/search.py", line 213, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File ".../pogom/models.py", line 257, in parse_map
    p['longitude'], d_t)
  File ".../pogom/customLog.py", line 17, in printPokemon
    pokemon_name = get_pokemon_name(id).lower()
  File ".../pogom/utils.py", line 248, in get_pokemon_name
    return i8ln(get_pokemon_data(pokemon_id)['name'])
  File ".../pogom/utils.py", line 243, in get_pokemon_data
    with open(file_path, 'r') as f:
IOError: [Errno 2] No such file or directory: '.../static/dist/data/pokemon.min.json'

## Context

This issue is breaking the software and he stops after some scans

## Your Environment

* Version used: Develop branch code
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu server

**Comment by Ashex** [comment]
Gotta get that [grunt](https://jonaharagon.github.io/PoGoMapWiki/#!installation.md#Installing_required_python_and_nodejs_modules) going.

**Comment by 1111121RicardoBrandao** [comment]
@Ashex thanks for the help, working again
I never noticed this issue with master branch
