### ISSUE TITLE
Workers occasionally throw an exception in 2.1

### ISSUE THREAD

**Issue by jaytanz** [AHAAAAAAA/PokemonGo-Map#3157]
I'm using the hex beehive generator with multiple accounts. Also switched the db to mysql to avoid the "database is locked" issues from sqlite when running with multiple (>5?) workers. Occasionally one of the workers will throw an exception with this traceback:

2016-08-02 16:24:20,327 [        models] [   INFO] Upserted 2 pokemon, 63 pokestops, and 5 gyms
Exception in thread search_thread-0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/joe/Pokemap2.1/pogom/search.py", line 159, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "/home/joe/Pokemap2.1/pogom/models.py", line 302, in parse_map
    bulk_upsert(Pokestop, pokestops)
  File "/home/joe/Pokemap2.1/pogom/models.py", line 332, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1213, u'Deadlock found when trying to get lock; try restarting transaction')

Totally possible there's something with the mysql setup I'm using, not at all experienced with it.

## Steps to Reproduce (for bugs)

My beehive.sh looks like this (some information redacted):

nohup python ../../runserver.py -ns -a ptc -u account0 -p password --db-type mysql --db-name pogom_mysql --db-user user --db-pass pass --db-host 127.0.0.1 -l 'lat, long' -st 3 -t 1 -sd 5 > logs/log_0 &
nohup python ../../runserver.py -ns -a ptc -u account1 -p password --db-type mysql --db-name pogom_mysql --db-user user --db-pass pass --db-host 127.0.0.1 -l 'lat, long' -st 3 -t 1 -sd 5 > logs/log_1 &
nohup python ../../runserver.py -ns -a ptc -u account2 -p password --db-type mysql --db-name pogom_mysql --db-user user --db-pass pass --db-host 127.0.0.1 -l 'lat, long' -st 3 -t 1 -sd 5 > logs/log_2 &
nohup python ../../runserver.py -ns -a ptc -u account3 -p password --db-type mysql --db-name pogom_mysql --db-user user --db-pass pass --db-host 127.0.0.1 -l 'lat, long' -st 3 -t 1 -sd 5 > logs/log_3 &
nohup python ../../runserver.py -ns -a ptc -u account4 -p password --db-type mysql --db-name pogom_mysql --db-user user --db-pass pass --db-host 127.0.0.1 -l 'lat, long' -st 3 -t 1 -sd 5 > logs/log_4 &
nohup python ../../runserver.py -ns -a ptc -u account5 -p password --db-type mysql --db-name pogom_mysql --db-user user --db-pass pass --db-host 127.0.0.1 -l 'lat, long' -st 3 -t 1 -sd 5 > logs/log_5 &
nohup python ../../runserver.py -ns -a ptc -u account6 -p password --db-type mysql --db-name pogom_mysql --db-user user --db-pass pass --db-host 127.0.0.1 -l 'lat, long' -st 3 -t 1 -sd 5 > logs/log_6 &
nohup python ../../runserver.py -os -l 'lat, long' &

## Context

Requires me to restart the worker that failed. Just a bit annoying, especially if I'm out and about catching pokemans.

## Your Environment

* Version used: 2.1
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): ubuntu 14.04

**Comment by invisiblek** [comment]
This is fixed in the develop branch and will be fixed when 2.2.0 is released

**Comment by jaytanz** [comment]
Thanks, I'll try switching to dev (just been waiting for it to stabilize a bit).
