### ISSUE TITLE
ERROR: Exceeded Maximum Connections (Beehive/Multiworker functioning ok though)

### ISSUE THREAD

**Issue by hack3rjack** [AHAAAAAAA/PokemonGo-Map#3167]
Getting an "Exceeded Maximum Connections" error when running runserver.py AFTER successfully connecting to mySQL, google logins, and 25 steps with successful adds of pokemon (code below), then steps resume without any additional errors. 

## Expected Behavior

Expecting to not get error :)

## Current Behavior

Cloned github develop branch, ran through setup per wiki, and things run great for 25 scans, but then getting Exception on /static/dist/js/stats.min.js twice, and then things work great again

## Possible Solution

Not sure of build, and can't locate any missed steps in wiki or similar open or closed issues like this one....possibly some dependency or setup that is not able to handle stats.min.js. Hoping this is a simple fix or missed step during setup.bat, location_generator.py, requirements.txt, npm grunt, npm install, or configuration of mySQL DB, config.ini or beehive.bat. 

## Steps to Reproduce (for bugs)

1. Clone development branch & Install (previously) Git, Python27, C++ compiler, node
2. Run EasySetup/setup.bat
3. pip install -r requirements.txt, npm install -g grunt-cli, npm install
4. ran location_generator.py, update spreadsheet for location_generator.py with coordinates, create updated beehive.bat with scans
5. Add accounts.csv (five google emails, one shared password)
6. Update config.ini with auth, usernames, passwords, db settings, gmaps, webserver settings
7.  python runserver.py -a google -u [username1] -u [username2] -u [username3] -u [username4] -u [username5] -p [sharedpwd] -k [googleapi] -l "[location]" -P 425 -H 0.0.0.0
8. See error for stats.min.js after 25 steps on line 80 ([Exceed Max Connections.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/397332/Exceed.Max.Connections.txt)

## Context

Trying to determine if there is a bug or setup dependency not covered in wikis (IMPORTANT: seems the two wikis are getting out of sync, and there is conflicting information)

## Your Environment

* Version used: dev version #3028
* Environment name and version:  Python 2.7
* Operating System and version (desktop or mobile): Windows 10 desktop
* Database: MariaDB/mySQL

## Error Code
2016-08-02 07:32:13,717 [ search_worker_0][        models][    INFO] Upserted 1 pokemon, 0 pokestops, and 3 gyms
2016-08-02 07:32:13,806 [ search_worker_4][        models][    INFO] Upserted 1 pokemon, 0 pokestops, and 4 gyms
[2016-08-02 07:32:16,141] ERROR in app: Exception on /static/dist/js/stats.min.js [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1837, in preprocess_request
    rv = func()
  File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Python27\lib\site-packages\playhouse\pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
2016-08-02 07:32:16,141 [        Thread-8][           app][   ERROR] Exception on /static/dist/js/stats.min.js [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Python27\lib\site-packages\flask-0.11.1-py2.7.egg\flask\app.py", line 1837, in preprocess_request
    rv = func()
  File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Python27\lib\site-packages\playhouse\pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
2016-08-02 07:32:18,528 [ search_worker_1][        search][    INFO] Searching step 26, remaining 371
2016-08-02 07:32:18,618 [ search_worker_2][        search][    INFO] Searching step 27, remaining 370

**Comment by hack3rjack** [comment]
Here is screenshot of scanning after 40 or so scans. Looks great, filters/buttons and stats work fine, and logs and scanner works very fast. 
 
![beehivemultithread](https://cloud.githubusercontent.com/assets/20573875/17334182/25143d1e-588a-11e6-8b61-ad2c56f5e770.JPG)

Just not sure what to do about the error described above (or if there is any negative consequence or anything needs to be done).

**Comment by hack3rjack** [comment]
Just ran it again with same command and not getting errors for stats.min.js or Exceeded Maximum Connections, not sure what that means??

**Comment by DeviantEng** [comment]
See my last post in #2743

**Comment by hack3rjack** [comment]
This was fixed by adding --db-max_connections 1000. 

Closing.
