### ISSUE TITLE
"[Errno 32] Broken pipe" messages in logs from instance with -os

### ISSUE THREAD

**Issue by DeviantEng** [AHAAAAAAA/PokemonGo-Map#3171]
CentOS 7 + mariadb instance running commit `b76099a`.  This is my startup script: 
```
python /opt/PokemonGo-Map/runserver.py -l REDACTED -ga REDACTED -nsc -os --db-max_connections 250
```

Log file is filling up with messages like this:
```
2016-08-02 11:39:12,292 [     Thread-5135][           app][    INFO] Changing next location: 37.6583120088,-82.7866642178
[...]
Exception in thread Thread-5315:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/SocketServer.py", line 596, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib64/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib64/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

I've snipped a bit of the logs, to simplify (only thing cut were more of these same 2 messages).  It looks like a `Changing next location` starts on thread `5135`, then shortly after that thread throws an exception of `Broken pipe`.  I'm not sure what that exception really means, but more importantly, what is this `Changing next location`?  Does that show every time the map is moved, or is that doing some sort of scanning?  This box is running with `-os`, so I don't want it doing any scanning at all.  All scanning is done by 2 other instances.

Thanks.

**Comment by theresthatguy** [comment]
I got same error today.
`Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
`

**Comment by hannahbanana** [comment]
+1
