### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by maddock34** [AHAAAAAAA/PokemonGo-Map#3206]
Working fine, decided to stop it and reduce the steps. Tried launching it again (with a .bat), it shows up on screen for a few seconds displays some text and rapidly disappears. I started by hand in CMD and got this 
"C:\Users\RaptorZ\Downloads\Pokemon GO\PokemonGo-Map-develop\PokemonGo-Map-develo
p>python runserver.py -u user -p pass -st 6 -k APIkey -l "location" -H 0.0.0.0
Traceback (most recent call last):
  File "runserver.py", line 58, in <module>
    position = get_pos_by_name(args.location)
  File "C:\Users\RaptorZ\Downloads\Pokemon GO\PokemonGo-Map-develop\PokemonGo-Ma
p-develop\pogom\pgoapi\utilities.py", line 60, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in
 geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\base.py", line 163, in _ca
ll_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out"

**Comment by qcjustin** [comment]
This happens to me when there are NETWORK issues. Try using Lat/Lon instead of an address.

**Comment by maddock34** [comment]
So it would be -l "34.5656 54.4353"? (those are random numbers?

**Comment by qcjustin** [comment]
Yes, Make sure the negative is there when it needs to etc, but thats correct.

**Comment by maddock34** [comment]
Wow, that worked. Great! Thanks!
