### ISSUE TITLE
Can't run runserver.py because no module flask_cors on Mac

### ISSUE THREAD

**Issue by jedichen121** [AHAAAAAAA/PokemonGo-Map#3213]
I've been trying to install this for hours. I finally went through the following command without errors:
```
curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
sudo python ./get-pip.py
sudo -H easy_install --upgrade six
sudo -H easy_install --upgrade setuptools
sudo -H pip install -r requirements.txt
```
But when I try `python ./runserver.py --help` it shows

`Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from flask_cors import CORS
ImportError: No module named flask_cors`

## Expected Behavior

I think the module flask_cors should be installed. If I run `pip list` that module is included there

`
click (6.6)
ConfigArgParse (0.10.0)
extern (0.1.0)
Flask (0.11.1)
Flask-Compress (1.3.0)
Flask-Cors (2.1.2)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
peewee (2.8.1)
pip (8.1.2)
protobuf (2.6.1)
protobuf-to-dict (0.1.0)
pycryptodomex (3.4.2)
PyMySQL (0.7.5)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (25.1.3)
six (1.10.0)
Werkzeug (0.11.10)
wheel (0.29.0)
`

## Current Behavior

Now it's only showing 

`Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from flask_cors import CORS
ImportError: No module named flask_cors`

when I try to run the runserver.py file.

## Possible Solution

Somehow the python couldn't find the installed packages? 

## Your Environment

* Version used:
* Python 2.7.12
* pip 8.1.2
* Mac OS X El Capitan

**Comment by Paralysing** [comment]
try pip install flask_cors

**Comment by jedichen121** [comment]
I tried that as well, it didn't work.

**Comment by wowfood** [comment]
pip install setuptools==21.2.1
pip install flask_cors

For some reason the latest version of setuptools can't install Flask_Cors.

**Comment by jedichen121** [comment]
Thank you but this doesn't work. It still tells me no module named flask_cors. The setuptools is version 21.2.1.

**Comment by josegrobles** [comment]
Same error :/

**Comment by jedichen121** [comment]
OK this seems to help me.  `python -m pip install <package>`. Previously when I used `pip install flask_cors`, it just said "Requirement already satisfied." But now I see it's actually installing stuffs. So I run 

`python -m pip install -r requirements.txt`

and this seems to install all packages correctly. 

Thanks for all the help guys!
