### ISSUE TITLE
Cant start

### ISSUE THREAD

**Issue by xDarkOne** [AHAAAAAAA/PokemonGo-Map#322]
Download new version and have this text

http://dl2.joxi.net/drive/2016/07/19/0013/2871/908087/87/30ca7ab36a.png

[-] looping: step 1 of 100
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 613, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 633, in process_step
    print('[+] Searching for Pok'+u'\xe9'+'mon at location {} {}'.format(FLOAT_LAT, FLOAT_LONG))
  File "C:\Python27\lib\encodings\cp866.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xe9' in position 21: character maps to <undefined>

**Comment by DerScreever** [comment]
retry with the latest fix pls.

**Comment by lorddusk** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/commit/d0a98a9a57ae8c2f1e6edac6a114ff00e73b6666 Fixed it.

**Comment by xDarkOne** [comment]
Yeah, ty, everything ok now!
