### ISSUE TITLE
Launch error. No module named request

### ISSUE THREAD

**Issue by snake-345** [AHAAAAAAA/PokemonGo-Map#323]
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    import flask
  File "/usr/local/lib/python2.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/usr/local/lib/python2.7/site-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python2.7/site-packages/werkzeug/http.py", line 28, in <module>
    from urllib.request import parse_http_list as _parse_list_header
ImportError: No module named request

How i can fix it?)

**Comment by DerScreever** [comment]
Installation:

pip install -r requirements.txt

**Comment by snake-345** [comment]
i done it

**Comment by xavifuefer** [comment]
same problem here on a OSX El Capitan

**Comment by snake-345** [comment]
I found this bug http://bugs.python.org/issue26498
Looks like problem with python 2.7.10, 2.7.11

**Comment by snake-345** [comment]
Ok. I resolve this problem. I complete "brew uninstall python". and install pip from https://pip.pypa.io/en/stable/installing/, than i complete pip install -r requirements.txt

**Comment by OranShuster** [comment]
using the bundled python on osx is dangerous and will prolly not work when packages are needed.
use brew and install a separate python/use virtualenv

**Comment by dnsBlah** [comment]
sudo -H pip install requests
Works fine for me on 10.11.5
