### ISSUE TITLE
[Suggestion] Define Alerts in config

### ISSUE THREAD

**Issue by jane0815** [AHAAAAAAA/PokemonGo-Map#3234]
It would be great if we could set the alerts in a config file. It is not easy to setup them in this small box. It is already hard on a big screen and gets even worse on a small phone screen.

**Comment by stekern** [comment]
I've done something similar in my setup, and it sends me notifications via Pushbullet because the default notifications did not work for Chrome on my phone. 

I added this to **config.ini**
```
ignore: [10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 27, 29, 32, 35, 39, 41, 42, 43, 44, 46, 48, 50, 52, 53, 54, 56, 60, 61, 63, 66, 69, 70, 72, 74, 75, 77, 79, 81, 82, 84, 86, 88, 90, 92, 93, 96, 98, 100, 101, 102, 104, 109, 111, 116, 118, 120, 138, 140]
notify: [3, 6, 9, 31, 34, 38, 59, 68, 130, 131, 132, 134, 135, 136, 143, 144, 145, 146, 149, 150, 151]
pushbullet-key: INSERTYOURKEY
```

I added this to **utils.py**
```
parser.add_argument('--ignore', action='append', help='Pokémon to ignore')
parser.add_argument('--notify', action='append', help='Pokémon to be notified about')
parser.add_argument('--pushbullet-key', help='Your Pushbullet API key', required=True)
```

I then use the ignore and notify lists, and the Pushbullet key, in **models.py** to filter out which Pokémon to include and which to send a Pushbullet notification about. You can easily access these arguments in **models.py** by doing something like
```
PB_KEY=args.pushbullet_key
IGNORE_LIST=[int(pokemon_id) for pokemon_id in args.ignore]
NOTIFY_LIST=[int(pokemon_id) for pokemon_id in args.notify]
```

I do all my filtering and notifying in the **parse_map** function.

**Comment by jane0815** [comment]
Wow that sounds really great! Would love to have this for my map too.

I just tryed to follow your steps but i get this error when starting the map:

```
python ./runserver.py
Traceback (most recent call last):
  File "./runserver.py", line 18, in <module>
    from pogom.app import Pogom
  File "/Users/JANE/PokemonGo-Map/pogom/app.py", line 12, in <module>
    from pogom.utils import get_args
  File "/Users/JANE/PokemonGo-Map/pogom/utils.py", line 112
    parser.add_argument('--ignore', action='append', help='Pokémon to ignore')
    ^
IndentationError: unexpected indent
```

Any idea what i did wrong?

**Comment by dev-masta** [comment]
my guess is that you should use spaces instead of tabs to indent rows
