### ISSUE TITLE
UnicodeDecodeError when app path contains 'é'

### ISSUE THREAD

**Issue by bakugo** [AHAAAAAAA/PokemonGo-Map#327]
### Environment info
Operating System: Windows 8.1
Installed version of Python: Python 2.7.12

### Steps to reproduce
1. Put app in a directory called "Pokémon Go Map"
2. Request something (example `http://localhost:5000/static/icons/1.png`)
3. Get an error

### Logs or other output that would be helpful
```
127.0.0.1 - - [19/Jul/2016 11:58:11] "GET /static/icons/1.png HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Program Files\Python2\lib\site-packages\flask\app.py", line 2000, in
__call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Python2\lib\site-packages\flask\app.py", line 1991, in
wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Program Files\Python2\lib\site-packages\flask\app.py", line 1567, in
handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python2\lib\site-packages\flask\app.py", line 1988, in
wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python2\lib\site-packages\flask\app.py", line 1641, in
full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python2\lib\site-packages\flask\app.py", line 1544, in
handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python2\lib\site-packages\flask\app.py", line 1639, in
full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python2\lib\site-packages\flask\app.py", line 1625, in
dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Python2\lib\site-packages\flask\helpers.py", line 892,
in send_static_file
    cache_timeout=cache_timeout)
  File "C:\Program Files\Python2\lib\site-packages\flask\helpers.py", line 633,
in send_from_directory
    filename = safe_join(directory, filename)
  File "C:\Program Files\Python2\lib\site-packages\flask\helpers.py", line 603,
in safe_join
    return os.path.join(directory, filename)
  File "C:\Program Files\Python2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 25: ordinal
 not in range(128)
```

**Comment by DerScreever** [comment]
already fixed.
try the latest version.

**Comment by bakugo** [comment]
I am on the latest version, still happening.

**Comment by nborrmann** [comment]
rename your directory. if youre using unicode in the path you're asking for problems.

**Comment by marauder37** [comment]
Yeah much as I love Unicode that bug looks like it's actually in Flask so not much we can do

**Comment by DerScreever** [comment]
the flask developer will merge our things if we need that

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
