### ISSUE TITLE
Dev build, exceed maximum connections

### ISSUE THREAD

**Issue by lota7** [AHAAAAAAA/PokemonGo-Map#3292]
## Expected Behavior

When running multiple workers on a location, on some I get 
Exceed Maximum Connections.
Log:
[2016-08-03 10:27:15,729] ERROR in app: Exception on /static/dist/js/stats.min.js [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_request
    rv = func()
  File "D:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "D:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "D:\Python27\lib\site-packages\playhouse\pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
2016-08-03 10:27:15,729 [       Thread-78][           app][   ERROR] Exception on /static/dist/js/stats.min.js [GET]
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_request
    rv = func()
  File "D:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "D:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "D:\Python27\lib\site-packages\playhouse\pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.

## Current Behavior

This causes those workers to die and only the ones who succeeded lives on for the rest of the run.

## Steps to Reproduce (for bugs)

1. Run Dev build
2. Multiple workers/accounts on a given location. I have 10.
3. -sd 10

## Your Environment

* Version used Dev
* Environment name Python 2.7:
* Win10, Desktop:

**Comment by danny6167** [comment]
I am also getting this on my non-scanning (Server only) instances.
MySQL DB

**Comment by aldarund** [comment]
Thats probably a mysql configuration

**Comment by Flumadiddle** [comment]
There is a new flag:
```--db-max_connections 1000```
Set that to be higher.

**Comment by lota7** [comment]
Thanks for the replies.
Flumadiddle, this to be inputted into config.ini?
