### ISSUE TITLE
[Problem] multiple access is causing error

### ISSUE THREAD

**Issue by vinsilsim** [AHAAAAAAA/PokemonGo-Map#3315]
Hello, today I came across this problem, my website have about 200 simultaneous accesses all the time, and is experiencing this problem. He did not search for only displays this error message.

2016-08-03 11:29:20,402 [     Thread-18][           app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.

**Comment by MrKetchumAll** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3292

**Comment by vinsilsim** [comment]
@MrKetchumAll thank you bro!
