### ISSUE TITLE
#012AttributeError: lat and lng required

### ISSUE THREAD

**Issue by osalivan** [AHAAAAAAA/PokemonGo-Map#332]
How fix this?

[2016-07-19 11:50:00,642] ERROR in app: Exception on / [GET]#012Traceback (most recent call last):#012 File "/home/bas/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app#012 response = self.full_dispatch_request()#012 File "/home/bas/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request#012 rv = self.handle_user_exception(e)#012 File "/home/bas/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception#012 reraise(exc_type, exc_value, tb)#012 File "/home/bas/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request#012 rv = self.dispatch_request()#012 File "/home/bas/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request#012 return self.view_functions[rule.endpoint](**req.view_args)#012 File "./example.py", line 799, in fullmap#012 'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)#012 File "./example.py", line 909, in get_map#012 zoom='15', )#012 File "/home/bas/.local/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 34, in __init__#012 self.build_markers(markers)#012 File "/home/bas/.local/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 58, in build_markers#012 self.add_marker(**marker)#012 File "/home/bas/.local/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 81, in add_marker#012 raise AttributeError('lat and lng required')#012AttributeError: lat and lng required
2016-07-19T14:50:15.384+03:00GET localhost:8080/ returned 500!
2016-07-19T14:50:15.384+03:00No application detected yet
2016-07-19T14:50:15.384+03:00[pid: 646|app: 0|req: 20/20] 127.0.0.1 () {36 vars in 420 bytes} [Tue Jul 19 11:50:00 2016] GET / => generated 291 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)

**Comment by bengalaviz** [comment]
Issue #284 should have fixed this issue. Try and pull an update to get it working.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
