### ISSUE TITLE
Can't start new thread with multiple scanners running

### ISSUE THREAD

**Issue by gdelazzari** [AHAAAAAAA/PokemonGo-Map#3326]
I'm running ~50/60 instances (just in scan mode, only one also has the web server enabled) on the same Linux machine but, instantly when starting the scanners or after some time they're up and running, they start complaining it's impossible for them to start new threads. I get errors like:

```
Traceback (most recent call last):
  File "PokemonGo-Map/runserver.py", line 113, in <module>
    app.run(threaded = True, use_reloader=False, debug=args.debug, host=args.host, port=args.port)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 607, in process_request
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

Yesterday they were also throwing a similar error but I'm not able to reproduce it. It was saying that it was impossible to start a new thread too. I think it was coming from the `peewee` module.

I'm launching all the scanners from a bash script, forking them in the background. The command is something like this:
```
python runserver.py [options] & > file.log &
```
The script is run as root, so all the python scripts are run as root.

Sometimes the launch script even throws:
```
./launchAll.sh: fork: Cannot allocate memory
```
when starting a script.

I already increased all the maximum threads, processes, stack size and number of open files limits I could find in the system. Through ulimit, sysctl, /etc/security/limits.conf etc...

The machine has 6 Xeon cores and 16GB of RAM, of which just 1.7GB are used with all the scanners running, so I think that CPU and RAM is not the problem here.
I can't understand what's going on, is there someone that could help me?

**Comment by Becold** [comment]
Try that : http://stackoverflow.com/questions/32283003/python-cant-start-new-thread-100-active-threads

**Comment by gdelazzari** [comment]
I already tried that but still the same issue
