### ISSUE TITLE
Developer build - NPM install error

### ISSUE THREAD

**Issue by rjdavid1218** [AHAAAAAAA/PokemonGo-Map#3344]
Hi all,

I'm trying to update to the current developer build, I was able to successfully install the version from last week but unable to do so with current.  When I enter in the npm install command, I get the following error.  Any help is appreciated!

C:\Users\Richard David\Downloads\PokemonGo-Map-develop x\PokemonGo-Map-develop>npm install
-
> pogomap@0.1.0 postinstall C:\Users\Richard David\Downloads\PokemonGo-Map-develop x\PokemonGo-Map-develop
> grunt build

module.js:327
    throw err;
    ^

Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Richard David\Downloads\PokemonGo-Map-develop x\PokemonGo-Map-develop\node_modules\grunt\lib\grunt.js:16:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! pogomap@0.1.0 postinstall: `grunt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogomap@0.1.0 postinstall script 'grunt build'.
npm ERR! This is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Richard David\Downloads\PokemonGo-Map-develop x\PokemonGo-Map-develop\npm-debug.log

**Comment by dirkpoetter** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3320

**Comment by BoGnY** [comment]
Which OS have you?

**Comment by MOE4HACKS** [comment]
1:Download develop files and install pip.
2:Download NodeJS (latest 6.3.1) here and install.
3:Open a Normal CMD (outside any folder,just search for it in start menu),and put this < npm install -g grunt > and < npm install -g grunt-cli >
4:Now go to your pokemon map folder, click on an empty space inside the folder ,hold shift and right click then choose <open  command window here>A new cmd will open.
5:Now add this comand : < npm install > (keep in mind that it wll take some time)
6:Launch your server and done.

Note: If you have antivirus running , open it and add allow access for npm services. i used to have the same problem then i disabled my antivirus and it worked fine for me.
Problem is that popular AV's secure unknown traffic between your pc and internet .
Hope this help and sry about my english.

**Comment by joshuabotes** [comment]
I have everything working fine right until the "npm install" step.
![image](https://cloud.githubusercontent.com/assets/20827004/17385839/93e92388-59e5-11e6-962c-17fa869e5b3e.png)
It looks like the grunt installed fine. then I try to run "npm install" and this happens
![image](https://cloud.githubusercontent.com/assets/20827004/17385863/ca5bd0be-59e5-11e6-9b1b-34784dbcf790.png)
