### ISSUE TITLE
Pip -r require not working, help needed

### ISSUE THREAD

**Issue by viktor999** [AHAAAAAAA/PokemonGo-Map#3412]
This would be the resort of the command (used git bashed as I followed the wiki guide)

"""""
$ pip install -r requirements.txt
Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 2))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 4))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r requirements.txt (line 5))
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 6))
  Using cached click-6.6.tar.gz
Collecting itsdangerous==0.24 (from -r requirements.txt (line 7))
c:\python27\lib\urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 271, in populate_link
    self.link = self._wheel_cache.cached_wheel(self.link, self.name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 68, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 148, in cached_wheel
    return pip.index.Link(path_to_url(path))
  File "c:\python27\lib\site-packages\pip\download.py", line 457, in path_to_url
    url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "c:\python27\lib\nturl2path.py", line 67, in pathname2url
    path = path + '/' + urllib.quote(comp)
  File "c:\python27\lib\urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe6'
""""

**Comment by thappy** [comment]
Have you installed python2.7-dev?

**Comment by KevinCollmer** [comment]
newest updates might have broken some things...

Got some problems running the service, too - on 2 different machines!

machine 1:
`
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c _proj.c -o build/temp.linux-x86_64-2.7/_proj.o
    _proj.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cs9WrA/pyproj/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FME5qC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-cs9WrA/pyproj/
`

machine 2:
`raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
`
`
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in /usr/local/lib/python2.7/dist-packages (from pgoapi->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from protobuf>=3.0.0a3->pgoapi->-r requirements.txt (line 18))
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.6
`
