### ISSUE TITLE
DecodeError: Unexpected end-group tag.

### ISSUE THREAD

**Issue by hugoerg56** [AHAAAAAAA/PokemonGo-Map#342]
`[-] looping: step 14 of 25
[+] Searching pokemons for location 10.5695956 -71.6423956}
Exception in thread search_thread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 598, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 630, in process_step
    profile_response))
  File "example.py", line 412, in get_heartbeat
    m5, )
  File "example.py", line 319, in get_profile
    return retrying_api_req(service, api, access_token, req, useauth=useauth)
  File "example.py", line 207, in retrying_api_req
    **kwargs)
  File "example.py", line 245, in api_req
    p_ret.ParseFromString(r.content)
  File "/Library/Python/2.7/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/python_message.py", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.`

**Comment by DerScreever** [comment]
have this sometimes too

**Comment by cprogrammer1994** [comment]
got the same issue

**Comment by rezz3x** [comment]
Got that too right now.

**Comment by hugoerg56** [comment]
@DerScreever yeah happen sometimes, actually working really awesome!!
https://www.dropbox.com/s/2vzgmu2l1gmupz1/Screenshot%202016-07-19%2008.51.58.png?dl=0

**Comment by Rominiust** [comment]
My console window is currently getting spammed with

```
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
```

It's constantly repeating, sometime during the retrying it gets to step 1 of 9 (-st 3), but doesn't get any further.

OS: Windows 10
Python Version: 2.7.12

Was working perfectly up until about 30 minutes to an hour ago.

**Comment by MikeDX** [comment]
I was getting this, however i was still getting intermittent correct packets, so as of 2 minutes ago, it is still working (but with that error line)

```
Completed: 30.612244898%
[-] looping: step 16 of 49
[+] Searching for Pokemon at location 51.6196341 -3.9093478
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
Completed: 32.6530612245%
```

**Comment by HenrySia** [comment]
Hi @sykhro, I agree that the server is down but the PokemonGo-Map doesn't recover from it even after the server is back up.

I'm not familiar with the PokemonGo-Map's codebase, but tejado has committed a fix for this issue here https://github.com/tejado/pgoapi/issues/31.

Can you perhaps take a look? Thanks a lot for the work.
