### ISSUE TITLE
Server location

### ISSUE THREAD

**Issue by hugoerg56** [AHAAAAAAA/PokemonGo-Map#348]
There is a way to sent the location on the url of the web server? I will like to serve that page to see it on a webview on my phone, and send every some time the gps location.

Example: http://localhost:8080?lat=10.5625879&long=-71.6392861

that way I can serve that page from my computer and use a webview on IOS to sent the current location

**Comment by Rominiust** [comment]
Using your example:

http://localhost:8080/next_loc?lat=10.5625879&long=-71.6392861

That will change the location after the current location is 100% scanned.

**Comment by hugoerg56** [comment]
`[-] Invalid next location: 10.5625879,
127.0.0.1 - - [19/Jul/2016 09:15:05] "GET /next_loc?lat=10.5625879&long=-71.6392861 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1731, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
`

**Comment by TiesdeKok** [comment]
The second argument is `lon` not `long`.

**Comment by hugoerg56** [comment]
works nice! thanks
