### ISSUE TITLE
Searching Error

### ISSUE THREAD

**Issue by randy86** [AHAAAAAAA/PokemonGo-Map#364]
[+] Searching pokemons for location -6.5850102 106.8821469}
Exception in thread search_thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 598, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 621, in process_step
    profile_response)
  File "example.py", line 412, in get_heartbeat
    m5, )
  File "example.py", line 319, in get_profile
    return retrying_api_req(service, api, access_token, req, useauth=useauth)
  File "example.py", line 207, in retrying_api_req
    **kwargs)
  File "example.py", line 245, in api_req
    p_ret.ParseFromString(r.content)
  File "/Library/Python/2.7/site-packages/protobuf-3.0.0b4-py2.7.egg/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/Library/Python/2.7/site-packages/protobuf-3.0.0b4-py2.7.egg/google/protobuf/internal/python_message.py", line 1085, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.

what's wrong ? the first test normally working, but in second test i've problem like this ?

thankyou

**Comment by Temetz** [comment]
See: 

https://github.com/AHAAAAAAA/PokemonGo-Map/issues/342
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/353

**Comment by guysoft** [comment]
Just started getting this too, looks like #353 , is this really a bug?

**Comment by randy86** [comment]
@guysoft  if server is down i can't login , 

`[+] Login successful
[+] Username: xxxxxxxxx
[+] You started playing Pokemon Go on: 2016-07-xx xx:xx:xx
[+] POKECOIN: 0
[+] STARDUST: 200
[-] looping: step 0 of 100
`
and i've already change Google API with my own. 


thankyou

**Comment by mkody** [comment]
> `[-] looping: step 0 of 100`

Wow, that's big. You should use a lower `-st` value there.

**Comment by MikeDX** [comment]
It might be useful to mention in the wiki that -st n is actually -st n²

**Comment by randy86** [comment]
@mkody @MikeDX  it's my code generate "sudo python example.py -a ptc -u ***** -p ***** -l "-6.585625 106.883751" -st 10"

-st = 10, but in looping always 0 - 100 ? what's wrong ? , but the first time all of this normally just not loaded the maps, after refresh browser and map loaded, i try to reset longlat and not worked,

`i use : OSX , python 2.7`

thankyou

**Comment by guysoft** [comment]
Back online, suggest adding a try/catch with a relevant error message

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team

**Comment by guysoft** [comment]
@DerScreever  Suggest you set develop as the default branch under the project "admin" page, so when people checkout they dont get master branch. Also pull requests should go to develop
