### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sceinR** [AHAAAAAAA/PokemonGo-Map#382]
Halp me plis. 
`Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "d:\pokemongo-map-master\example.py", line 395, in main
    api_endpoint = get_api_endpoint(access_token)
  File "d:\pokemongo-map-master\example.py", line 206, in get_api_endpoint
    profile_response = retrying_get_profile(access_token, api, None)
  File "d:\pokemongo-map-master\example.py", line 221, in retrying_get_profile
    profile_response = get_profile(access_token, api, useauth, *reqq)
  File "d:\pokemongo-map-master\example.py", line 259, in get_profile
    return retrying_api_req(api, access_token, req, useauth=useauth)
  File "d:\pokemongo-map-master\example.py", line 155, in retrying_api_req
    response = api_req(api_endpoint, access_token, *args, **kwargs)
  File "d:\pokemongo-map-master\example.py", line 191, in api_req
    p_ret.ParseFromString(r.content)
  File "c:\python27\lib\site-packages\google\protobuf\message.py", line 186, in
ParseFromString
    self.MergeFromString(serialized)
  File "c:\python27\lib\site-packages\google\protobuf\internal\python_message.py
", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.`

**Comment by obiebozza** [comment]
Same here, servers are up

**Comment by sykhro** [comment]
This happens when servers are unstable

**Comment by jabelone** [comment]
Can this be closed or is it still an issue?
