### ISSUE TITLE
DecodeError: Unexpected end-group tag.

### ISSUE THREAD

**Issue by nickpoulos** [AHAAAAAAA/PokemonGo-Map#401]
I keep getting the following after a step or two, trying to look into now, but its tough while im at work:

Exception in thread search_thread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 598, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 630, in process_step
    profile_response))
  File "example.py", line 412, in get_heartbeat
    m5, )
  File "example.py", line 319, in get_profile
    return retrying_api_req(service, api, access_token, req, useauth=useauth)
  File "example.py", line 207, in retrying_api_req
    **kwargs)
  File "example.py", line 245, in api_req
    p_ret.ParseFromString(r.content)
  File "/Library/Python/2.7/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/python_message.py", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.

**Comment by nickpoulos** [comment]
Nvm, just re-pulled. These exceptions seem to be caught and continued gracefully. Good work guys.

**Comment by rushingfitness** [comment]
Had the same issue: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/398
Anyone have an idea on what the issue here is?

**Comment by mkody** [comment]
Look at those issues who may reports the same thing: [label:"Not an issue: servers are down"](https://github.com/AHAAAAAAA/PokemonGo-Map/issues?utf8=%E2%9C%93&q=label%3A%22Not%20an%20issue%3A%20servers%20are%20down%22%20)

**Comment by JZ6** [comment]
fix

**Comment by nickpoulos** [comment]
re-pull the repo it is already fixed
