### ISSUE TITLE
 What am I doing wrong?

### ISSUE THREAD

**Issue by lex095** [AHAAAAAAA/PokemonGo-Map#431]
Help pls

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\PokemonGo-Map-master\example.py", line 793, in fullmap
    'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)
  File "C:\Users\User\Desktop\PokemonGo-Map-master\example.py", line 903, in get_map
    zoom='15', )
  File "C:\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 34, in __init__
    self.build_markers(markers)
  File "C:\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 58, in build_markers
    self.add_marker(**marker)
  File "C:\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 81, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng required

**Comment by vintagesucks** [comment]
- Did you get your own API Key?
- Try a different location

**Comment by h1pp0** [comment]
if your using coords for location, try it with and without a , between the point. This was fixed in a recent commit

**Comment by lex095** [comment]
Yes, I did my key
Tried different cities and countries
![image](https://cloud.githubusercontent.com/assets/9983215/16965313/41068536-4e08-11e6-92c8-fa6df956e07b.png)

**Comment by vingesus** [comment]
Try posting your syntax please :)

**Comment by lex095** [comment]
OMG! 
I'm stupid excuse....
I wrote "python example.py -a **authService** -u ...... -p ...... -l "Moscow" -st 5" 

There should be written Google?

**Comment by vingesus** [comment]
google or ptc yes :)

**Comment by CSCG** [comment]
Be wary - I noticed with some people trying to force --auto_refresh, they type something like -autorefresh and it trys to parse it as '%-a%%' which will result in this exact error.

However -- this looks like a GeoIP lookup error, try a more specific address like "Moscow, Russia". That looks like a geopy error to me

**Comment by lex095** [comment]
tnx for help

**Comment by adi182** [comment]
if you're logging in with google details is it just your google email address and password? I keep getting wrong username/password

**Comment by Powback** [comment]
@adi182 make sure you're not using the -p parameter multiple times. People seem to use -p to indicate port, when it's actually -P. 

python example.py -a google -u username@mail.com -p password **-P 5000**

**Comment by adi182** [comment]
I've got mine just like that but still no luck logging in. It might be the server tho as I can't login on my mobile at the moment either
