### ISSUE TITLE
Exception when installing using "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by yougotashovel** [AHAAAAAAA/PokemonGo-Map#441]
Install fails when using ```pip install -r requirements.txt```

Any idea what could be causing this?  I've included the log from the point it fails, installs most of the dependencies then get's caught.

Thanks

### Environment info
Operating System: OS X 10.11.5
Installed version of Python: 2.7

### Error Logs
```
Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: geopy, setuptools, protobuf, requests, itsdangerous, click, werkzeug, MarkupSafe, Jinja2, flask, flask-googlemaps, future, s2sphere, pycryptodomex, gpsoauth, coverage, docopt, coveralls
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/geopy'
```

**Comment by Znuff** [comment]
`OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/geopy'`

sudo.

**Comment by Powback** [comment]
^ sudo

**Comment by ph3l1x** [comment]
not a very good idea to run sudo pip install...

**Comment by yougotashovel** [comment]
What's the issue doing sudo pip install?

**Comment by ph3l1x** [comment]
easy for someone to put some malicious software to be installed.
