### ISSUE TITLE
Run under gunicorn

### ISSUE THREAD

**Issue by Savichev-Igor** [AHAAAAAAA/PokemonGo-Map#478]
Hello everyone =) !

I am enjoying to use your app, but have one question.

I had try to run it under gunicorn and after get request see this in console:
```
[2016-07-20 06:44:58,579] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/venv/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/venv/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/venv/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/venv/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/venv/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/example.py", line 825, in fullmap
    'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)
  File "/home/example.py", line 935, in get_map
    zoom='15', )
  File "/home/venv/local/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 34, in __init__
    self.build_markers(markers)
  File "/home/venv/local/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 58, in build_markers
    self.add_marker(**marker)
  File "/home/venv/local/lib/python2.7/site-packages/flask_googlemaps/__init__.py", line 81, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng required
```

How i can fix it)?

**Comment by alexpantyukhin** [comment]
Can you show how you config the unicorn?

**Comment by DerScreever** [comment]
pls post also the start command.

**Comment by Savichev-Igor** [comment]
@alexpantyukhin 
@DerScreever 

I did under venv:
```
pip install gunicorn
gunicorn example:app
```
And all args pass like default args into example.py

**Comment by alexpantyukhin** [comment]
I believe that gunicorn doesn't pass arguments such way.  Maybe it would help you http://stackoverflow.com/questions/8495367/using-additional-command-line-arguments-with-gunicorn

**Comment by Savichev-Igor** [comment]
@alexpantyukhin 

No, it doesn't :<

**Comment by alexpantyukhin** [comment]
@DerScreever 
Would it be useful then to support config file? And work in the same way. If application didn't find arguments from command line it reads arguments from the config file. I think that it would be useful to not pass such arguments all the time and store it in config. I could implent it if need.

**Comment by Savichev-Igor** [comment]
@alexpantyukhin 

Yes, it can useful, implement please.
