### ISSUE TITLE
After multiple users reach the site, it become unreachable

### ISSUE THREAD

**Issue by aabosh** [AHAAAAAAA/PokemonGo-Map#49]
I made a change to `example.py` and edited the last line to `app.run(host='0.0.0.0', debug=True)` so that myself and friends could access it anywhere. Unfortunately, after doing this I learned that when multiple people connect to the server, it becomes no longer reachable and throws this error:
`Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe`

Any help would be much appreciated.

**Comment by marauder37** [comment]
I have 3 tabs open all reloading the page every 30 seconds without seeing that problem. I'll keep looking

**Comment by aabosh** [comment]
It seems to only crash when different IP addresses connect, when it's only one, all seems to be good.

**Comment by marauder37** [comment]
I have 2 phones also accessing it now, still going like a champ

**Comment by marauder37** [comment]
You're using the latest code, right?

Could you check your console output and make sure only one background thread is running?  It looks like it could be a threadsafety problem but hard to replicate = hard to fix

**Comment by aabosh** [comment]
Yep I am. I'll check that now.
Is there a way I can get in real-time contact with you—Slack, Discord, Skype, Twitter, something?

**Comment by marauder37** [comment]
We have a Discord but I'm way too elderly to understand how all that works

**Comment by marauder37** [comment]
I was given this link: https://discord.gg/qbpVH6b

**Comment by robfrizzy** [comment]
I'm sorry, but if you don't mind me asking, how does this allow you to access this anywhere? I was looking for a way to do this.

**Comment by aabosh** [comment]
@marauder37 All good man! I just performed a clean install on the Ubuntu server I was working on and it still seems to crash. Is there a way I can verify only one background thread is running?

**Comment by aabosh** [comment]
@robfrizzy The line edit allows the page to be accessible anywhere, assuming you have port 5000 open.

**Comment by robfrizzy** [comment]
@aabosh Yeah, gotcha. I'm not familiar with Flask. Just looked it up and figured that part out. I set up port forwarding for port 5000 and was wondering why it wasn't working. I'll have to give it a shot again.

**Comment by marauder37** [comment]
@aabosh ps auxww|grep example.py will give you an idea of what's running on your machine, there should be two of them, one's Flask and the other's the background worker

Also the background worker puts its start/stop out to the console, you should see one start per search, then the search get to 100%, then another start

**Comment by marauder37** [comment]
@robfrizzy you also need to have the Flask server listening on 0.0.0.0 or an IP address with some connectivity i.e. not 127.0.0.1

**Comment by aabosh** [comment]
@marauder37 I see three processes, no idea what the last one is. 
![output](https://cloud.githubusercontent.com/assets/7517009/16907970/d0ae9382-4c95-11e6-8ee0-3223b74ab541.png)

**Comment by Octylpy** [comment]
I was also running into this problem when I refreshed quickly. This should be fixed by e8ab65a with the addition of Flask's threading option.

**Comment by aabosh** [comment]
@Octylpy Yep, just tried the new commit as well. Looks to be resolved!
