### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by 4BHIFGartner** [AHAAAAAAA/PokemonGo-Map#516]
Installed version of Python:
2.7

### Steps to reproduce
1. Started application
2. Waited to load more Pokemons
3. And at any step someties 70 sometimes more than 400 it stops with the errormassage below 

### What have you tried?
1. Finding Pokemon close to me

the error massage is from the browser 

`Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "c:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Felix\Downloads\PokemonGo-Map-master\example.py", line 696, in fullmap
    clear_stale_pokemons()
  File "C:\Users\Felix\Downloads\PokemonGo-Map-master\example.py", line 648, in clear_stale_pokemons
    print "[+] removing stale pokemon %s at %f, %f from list" % (pokemon['name'], pokemon['lat'], pokemon['lng'])
  File "c:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2640' in position 34: character maps to <undefined>`

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team

**Comment by 4BHIFGartner** [comment]
Ok, did anything changed by starting the application or do i need to run the same commands like in old version
