### ISSUE TITLE
How to make to scan around my coordinates, not in the city center?

### ISSUE THREAD

**Issue by vkbugs** [AHAAAAAAA/PokemonGo-Map#517]
How to make to scan around my coordinates, not in the city center?

```
C:\Users\celia\Desktop\PokemonGo-Map-master>example.py -u log -p pass -l "54.9246758, 9.73839283'" -st 50 -ar 5
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 926-885-240
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Jul/2016 14:14:02] "GET /data HTTP/1.1" 200 -
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\celia\Desktop\PokemonGo-Map-master\example.py", line 571, in main
    retrying_set_location(args.location)
  File "C:\Users\celia\Desktop\PokemonGo-Map-master\example.py", line 157, in retrying_set_location
    set_location(location_name)
  File "C:\Users\celia\Desktop\PokemonGo-Map-master\example.py", line 177, in set_location
    origin_lat, origin_lon = local_lat, local_lng = loc.latitude, loc.longitude
AttributeError: 'NoneType' object has no attribute 'latitude'
```

**Comment by vkbugs** [comment]
Sorry, I did not notice the extra character

**Comment by KevakaBuel** [comment]
no whitespace between the coords and it should work

**Comment by vkbugs** [comment]
It has been my error
"54.9246758, 9.73839283'"
' - has been unnecessary, I did not notice

**Comment by amartshah** [comment]
Can someone please post an example of how to put in coordinates. I can not get them to work
