### ISSUE TITLE
ImportError: No module named peewee

### ISSUE THREAD

**Issue by iTayGNR** [AHAAAAAAA/PokemonGo-Map#525]
My Input:
`python runserver.py -a google -u **********@gmail.com -p ********** -l "32.7979775,44.9759091" -st 5 -ar 10;`

(information censored)

My Output:

Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "C:\Users\iTay\Desktop\PokeMap\pogom\app.py", line 10, in <module>
    from .models import Pokemon, Gym, Pokestop
  File "C:\Users\iTay\Desktop\PokeMap\pogom\models.py", line 5, in <module>
    from peewee import Model, SqliteDatabase, InsertQuery, IntegerField,\
ImportError: No module named peewee

What's wrong?

**Comment by DerScreever** [comment]
you need to install the missing modules.

pip install --upgrade -r requirements.txt
