### ISSUE TITLE
Crashing / Failed to decode / Wrong login

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#53]
### Environment info
Operating System:
Windows Server 2012 r2

Installed version of Python:
2.7

### Steps to reproduce
1. just start it

### What have you tried?
1. cant do anything about it myself

### Logs or other output that would be helpful

http://pastebin.com/2BFxtsnn

Also keeps spamming that my login is wrong for some reasons.

When like 5-6 people open the site at the same time / browsing it the server dies with this message: http://pastebin.com/C2wUBcaM  + tons of [-] login_ptc: could not decode JSON from

Also does it auto reload the map after x amount of time or do i have to restart the server by hand? 

Still love this project and would like to donate if you keep working on it.

**Comment by robfrizzy** [comment]
From my experience, you don't have to restart the server, just refresh the webpage to refresh the map.

**Comment by denniskai1234** [comment]
I dont see any new pokemons / getting any removed so i dont think that is working?

Also to replicate the crashing issue, i binded the site on my server on port 80 so i can reach it from everywhere and did a http check from https://check-host.net/ some requests at the same time will crash it.

**Comment by denniskai1234** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe

Error message on a debian system.

**Comment by haagiboy88** [comment]
As of now, pokemons are not being removed from the map. But the team is working on it.

**Comment by denniskai1234** [comment]
Any eta when you will finish this? Its impossible to use the map on a phone while im around in town which sucks.
