### ISSUE TITLE
Cryptodome error

### ISSUE THREAD

**Issue by Amichi05** [AHAAAAAAA/PokemonGo-Map#566]
Hello Guys,

I'm getting an error

Traceback (most recent call last):
  File "runserver.py", line 12, in <module>
    from pogom.search import search_loop
  File "C:\PokemonGo-Map-develop\pogom\search.py", line 13, in <module>
    from pgoapi import PGoApi
  File "C:\PokemonGo-Map-develop\pogom\pgoapi\__init__.py", line 1, in <module>
    from pgoapi      import *
  File "C:\PokemonGo-Map-develop\pogom\pgoapi\pgoapi.py", line 34, in <module>
    from auth_google import AuthGoogle
  File "C:\PokemonGo-Map-develop\pogom\pgoapi\auth_google.py", line 29, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

### Environment info

Windows 10

Installed version of Python:

2.7.12

I've tried to reinstall the requirements and the pycrytodome

**Comment by MrLuigiConnor** [comment]
I have the same error on windows 8. Tried reinstalling but no luck so far.

**Comment by RedViper9** [comment]
Started getting this error when I uninstalled 32 bit Python 2.7 and installed 64 bit Python 2.7. I don't know if that is the issue yet. Will update.

**Comment by loretoparisi** [comment]
I'm not sure that this issue has been solved - see [here](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3070)

**Comment by RioryRikina** [comment]
I can confirm that 32 bit python works, i've had the same issue with python 64 bit. After reinstalling the 32 bit everything works like a charm!
