### ISSUE TITLE
No icons appear on the map

### ISSUE THREAD

**Issue by statkute** [AHAAAAAAA/PokemonGo-Map#568]
When running the script in cmd, i get this error:  

```
127.0.0.1 - - [20/Jul/2016 18:36:21] "GET /static/icons/118.png HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 13: ordinal not in range(128)
```

I suppose this is why I can not see any pokemons or gyms and etc. on the map, even though the data is loaded in http://localhost:5000/raw_data . 

Could You please help me to fix this?

**Comment by DerScreever** [comment]
what command you use to start?

**Comment by dv8withn8** [comment]
I get the same, using something like `python example.py -a google -u USERNAME -p PASSWORD -l "41.885378, -87.622569" -st 5` sometimes the browser will just be blank (no map) though i can see all the pokemon/locations scrolling by in the terminal.

**Comment by statkute** [comment]
`python example.py -a ptc -u USERNAME -p PASSWORD -l "55.91851464 21.05823429" -st 12`

**Comment by rishabhbanga** [comment]
@statkute @dv8withn8 After downloading the develop branch, try using this :

`runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l LOCATION -st STEP_LIMIT [-i IGNORE | -o ONLY] [-ar AUTO_REFRESH] [-dp Display Pokestops] [-dl Display only lured Pokestops] [-dg Display Gyms] [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-k GMAPS_KEY]`
