### ISSUE TITLE
Script requires Flask/Werkzeug to run in debug mode.

### ISSUE THREAD

**Issue by tuxkamen** [AHAAAAAAA/PokemonGo-Map#575]
I couldn't help but notice that the Flask instance is being passed in debug=True.  That doesn't seem to be a typical usage for something I would use, even at home.  A typical startup log looks like this:

```
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 123-456-789
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
...

```

Those debugger lines are coming from Werkzeug.  In the event of an application error, this would theoretically pop up an interactive debugger, which could potentially provide unwanted access.

All well and good--just disable it, right?  Except that, while this does turn off the debugger, it also breaks the script:

```
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2016-07-20 08:41:16,967] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "example.py", line 792, in fullmap
    'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)
  File "example.py", line 902, in get_map
    zoom='15', )
  File "C:\python27\lib\site-packages\flask_googlemaps\__init__.py", line 34, in __init__
    self.build_markers(markers)
  File "C:\python27\lib\site-packages\flask_googlemaps\__init__.py", line 58, in build_markers
    self.add_marker(**marker)
  File "C:\python27\lib\site-packages\flask_googlemaps\__init__.py", line 81, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng required
```

It seems like with debug set to false, the script isn't able to pass the necessary data on.

### Environment info
Operating System: Win10

Installed version of Python: 2.7.12

### Steps to reproduce
1. Change the Flask invocation in example.py:910 to launch with debug=False:

`app.run(debug=False, threaded=True, host=args.host, port=args.port)`

2. Run the script.
-- Expected output: Normal operation without debug messages
-- Actual output: 

### What have you tried?
1. FLASK_DEBUG=0 (debug stays on, as it would, since the invocation is in the script)
2. debug=False at line 910

**Comment by sykhro** [comment]
Switch to the development branch. Debug there is on for both the script and flask only when -d is passed

**Comment by tuxkamen** [comment]
Sure, let me give that a try.

**Comment by tuxkamen** [comment]
Everything looks good on develop.  Thanks for letting me know about it.  Will that implementation be superceding master soon so that the debugging goes away for end-users?
