### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/opt/pokemongo-dev/credentials.json'

### ISSUE THREAD

**Issue by mcmaxl** [AHAAAAAAA/PokemonGo-Map#606]
still the credentials.json path error. dev branch

```
root@BlackBox:/opt/pokemongo-dev# python ./runserver.py -u ****** -p ****** -l "******" -st 10 -H 0.0.0.0 -P 5010 -L de
2016-07-20 19:51:34,674 [  runserver] [   INFO] Parsed location is: ****/******/0.0000 (lat/lng/alt)
2016-07-20 19:51:34,674 [     search] [   INFO] Attempting login.
2016-07-20 19:51:34,677 [   auth_ptc] [   INFO] Login for: ******
Traceback (most recent call last):
  File "./runserver.py", line 65, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "/opt/pokemongo-dev/pogom/utils.py", line 87, in load_credentials
    with open(filepath+'/credentials.json') as file:
IOError: [Errno 2] No such file or directory: '/opt/pokemongo-dev/credentials.json'
root@BlackBox:/opt/pokemongo-dev#
```

**Comment by mcmaxl** [comment]
sorry. solved
