### ISSUE TITLE
Error when searching for Pokemon

### ISSUE THREAD

**Issue by Skullmonkey** [AHAAAAAAA/PokemonGo-Map#663]
### Environment info
Operating System:
W10
Installed version of Python:
2.7.12

Commit:
74b4609  Auto refresh #2 (#647)

### Steps to reproduce
1.Run server.py with command
`python runserver.py -a ptc -u *** -p *** -l "hell, i mean florida" -st 6 -H 0.0.0.0 -P 8800 -ar 3 -dg`

### What have you tried?
1. Deleting folder and starting fresh.

### Logs or other output that would be helpful
```
2016-07-20 17:09:54,267 [  runserver] [   INFO] Parsed location is: ***/***/0.0000 (lat/lng/alt)
2016-07-20 17:09:54,273 [     search] [   INFO] Attempting login.
2016-07-20 17:09:54,276 [   auth_ptc] [   INFO] Login for: ***
2016-07-20 17:09:54,292 [  _internal] [   INFO]  * Running on http://0.0.0.0:8800/ (Press CTRL+C to quit)
2016-07-20 17:09:55,661 [   auth_ptc] [   INFO] PTC Login successful
2016-07-20 17:09:58,081 [     search] [   INFO] Login successful.
2016-07-20 17:09:58,084 [     search] [   INFO] Scanning step 1 of 36.
2016-07-20 17:09:58,904 [     models] [   INFO] Upserting 1 pokemon
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\***\Desktop\PokemonGo-Map-develop\pogom\search.py", line 100, in search_loop
    search(args)
  File "C:\Users\***\Desktop\PokemonGo-Map-develop\pogom\search.py", line 89, in search
    parse_map(response_dict)
  File "C:\Users\***\Desktop\PokemonGo-Map-develop\pogom\models.py", line 137, in parse_map
    InsertQuery(Pokemon, rows=pokemons.values()).upsert().execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table pokemon has no column named detect_time

2016-07-20 17:10:01,335 [     models] [   INFO] Get Pokemons for stamp: 2016-07-20 17:09:48.023000
[2016-07-20 17:10:01,342] ERROR in app: Exception on /pokemons/1469048988023 [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\***\Desktop\PokemonGo-Map-develop\pogom\app.py", line 40, in pokemons
    return jsonify(self.get_raw_data(stamp)['pokemons'])
  File "C:\Users\***\Desktop\PokemonGo-Map-develop\pogom\app.py", line 33, in get_raw_data
    'pokemons': Pokemon.get_active(stamp)
  File "C:\Users\***\Desktop\PokemonGo-Map-develop\pogom\models.py", line 45, in get_active
    for p in query:
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.detect_time
```

**Comment by DerScreever** [comment]
remove your pogom.db file
then retry
