### ISSUE TITLE
Migrate pogom.db schema

### ISSUE THREAD

**Issue by jangrewe** [AHAAAAAAA/PokemonGo-Map#665]
### Environment info
Operating System: Debian jessie
Installed version of Python: 2.7

### Steps to reproduce
1. pull commit with changes to db schema
2. start runserver.py
3. ...
4. profit!

### Logs or other output that would be helpful
```
[2016-07-20 23:23:46,775] ERROR in app: Exception on /pokemons/1469049818590 [GET]
Traceback (most recent call last):
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pokemongo-map-dev/pogom/app.py", line 40, in pokemons
    return jsonify(self.get_raw_data(stamp)['pokemons'])
  File "/opt/pokemongo-map-dev/pogom/app.py", line 33, in get_raw_data
    'pokemons': Pokemon.get_active(stamp)
  File "/opt/pokemongo-map-dev/pogom/models.py", line 45, in get_active
    for p in query:
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.detect_time
```

I think the best idea would be to add a db version table/field somewhere, and provide schema migrations when the schema gets updated.

**Comment by DerScreever** [comment]
just delete this file at the moment. we will do later.

**Comment by jangrewe** [comment]
Yes, that's what i did, of course! This was rather mean a a feature request so you don't have to deal with users posting the same errors.
Maybe also just exiting with an error would be a good idea (i wouldn't dare to actually delete the file)
