### ISSUE TITLE
Need help starting the runserver

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#666]
I need help starting the runserver.py can someone helpme with that i was starting with the old one but the command line don't work for this one.

python runserver.py -a ptc -u USER -p PASS -l "LOCATION" -st 20 -H 00.00.00.00 -P 5000 -ar 5

Can someone help me like making the new command line for me with all steps

**Comment by dhirnitish** [comment]
Did you pip upgrade the requirements.txt?

**Comment by SkyBadPT** [comment]
@dhirnitish Yes i did and i got no erros

**Comment by dhirnitish** [comment]
What error are you getting with this command?

**Comment by SkyBadPT** [comment]
@dhirnitish is was the upgrade thanks!!

**Comment by SkyBadPT** [comment]
@dhirnitish got this error` python: can't open file 'runserver.py': [Errno 2] No such file or directory`

**Comment by dhirnitish** [comment]
@SkyBadPT Make sure you have this branch and not the master branch https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop

**Comment by Skullmonkey** [comment]
I am guessing you are still on the master branch. Switch to develop: https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop

Also, I wouldn't put any steps over 10. It can't scan fast enough to keep them updated.

**Comment by wohfab** [comment]
And make sure you run the `runserver.py` out of the downloaded directory.

**Comment by SkyBadPT** [comment]
@Skullmonkey , @dhirnitish , im using the DEV one im getting this error now:

```
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "/root/PokeSpotPT/pogom/app.py", line 10, in <module>
    from .models import Pokemon, Gym, Pokestop
  File "/root/PokeSpotPT/pogom/models.py", line 5, in <module>
    from peewee import Model, SqliteDatabase, InsertQuery, IntegerField,\
ImportError: No module named peewee

```

**Comment by SkyBadPT** [comment]
Also after executing this command:  `sudo pip install --upgrade -r requirements.txt`

and then the start command i got this big error:

`2016-07-20 23:42:26,224 [  runserver] [   INFO] Parsed location is: 38.7679/-9.0949/0.0000 (lat/lng/alt)
Traceback (most recent call last):
  File "runserver.py", line 65, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "/root/PokeSpotPT/pogom/utils.py", line 88, in load_credentials
    with open(filepath+'/credentials.json') as file:
IOError: [Errno 2] No such file or directory: '/root/PokeSpotPT/credentials.json'
2016-07-20 23:42:26,243 [     search] [   INFO] Attempting login.
root@vps269273:~/PokeSpotPT# clear
root@vps269273:~/PokeSpotPT# python runserver.py -a ptc -u PokeSpotPT -p fifa2008 -l "38.767948, -9.094914" -st 15 -H 00.00.00.00 -P 5000 -ar 5
2016-07-20 23:42:35,042 [  runserver] [   INFO] Parsed location is: 38.7679/-9.0949/0.0000 (lat/lng/alt)
Traceback (most recent call last):
  File "runserver.py", line 65, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "/root/PokeSpotPT/pogom/utils.py", line 88, in load_credentials
    with open(filepath+'/credentials.json') as file:
IOError: [Errno 2] No such file or directory: '/root/PokeSpotPT/credentials.json'
2016-07-20 23:42:35,067 [     search] [   INFO] Attempting login.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/PokeSpotPT/pogom/search.py", line 100, in search_loop
    search(args)
  File "/root/PokeSpotPT/pogom/search.py", line 75, in search
    login(args, position)
  File "/root/PokeSpotPT/pogom/search.py", line 56, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "/root/PokeSpotPT/pogom/pgoapi/pgoapi.py", line 136, in login
    self._auth_provider = AuthPtc()
  File "/root/PokeSpotPT/pogom/pgoapi/auth_ptc.py", line 44, in __init__
    self._session = requests.session()
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 689, in session
    return Session()
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 302, in __init__
    self.headers = default_headers()
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 601, in default_headers
    'Connection': 'keep-alive',
  File "/usr/local/lib/python2.7/dist-packages/requests/structures.py", line 48, in __init__
    self.update(data, **kwargs)
  File "/usr/lib/python2.7/_abcoll.py", line 559, in update
    if isinstance(other, Mapping):
  File "/usr/lib/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/usr/lib/python2.7/abc.py", line 156, in __subclasscheck__
    cls._abc_negative_cache = WeakSet()
  File "/usr/lib/python2.7/_weakrefset.py", line 38, in __init__
    def _remove(item, selfref=ref(self)):
TypeError: 'NoneType' object is not callable
`

**Comment by Stex** [comment]
As the error message states, the server is searching for a `credentials.json` file. 

You either have to rename/copy `credentials.example.json` to `credentials.json` or specify your Google API key using `-k API_KEY` when starting the server

**Comment by SkyBadPT** [comment]
@Stex It's working thanks. (Just a quick question how can i enable gyms? and pokestops?)

**Comment by Stex** [comment]
@SkyBadPT Those do not seem to be supported in the `develop`-version yet.

**Comment by SkyBadPT** [comment]
@Stex  Okay thanks.

**Comment by Jacopo1891** [comment]
Sorry, but -u USER -p PASS what i have to pass? The email of gmail that i play with or nickname?
Because logs are: 
`2016-07-21 00:18:09,082 [  runserver] [   INFO] Parsed location is: 43.7696/11.2558/0.0000 (lat/lng/alt)
2016-07-21 00:18:09,083 [     search] [   INFO] Attempting login.
2016-07-21 00:18:09,084 [   auth_ptc] [   INFO] Login for: Jac1891
2016-07-21 00:18:09,102 [  _internal] [   INFO]  * Running on http://00.00.00.00:5000/ (Press CTRL+C to quit)
2016-07-21 00:18:09,768 [   auth_ptc] [  ERROR] Could not retrieve token: Your username or password is incorrect. You have 4 attempts left before you will be locked out of your account for 15 minutes.
2016-07-21 00:18:09,769 [     search] [   INFO] Login failed. Trying again.
`
Why?

**Comment by Stex** [comment]
@Jacopo1891 depends on whether you log in with your google account or with a PTC (Pokémon Trainer Club, basically an account on pokemon.com).

**If you use PTC: ** Username and Password are the same as you'd use on pokemon.com
** If you use Google**: I didn't try it, but from the help section I'd say, use  `-a google -u your_mail@gmail.com`

**Comment by Jacopo1891** [comment]
@Stex Tnx! You are totally right! But, what about the server? 
`2016-07-21 00:30:00,979 [  _internal] [   INFO]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2016-07-21 00:30:02,473 [auth_google] [   INFO] Google Login successful.

2016-07-21 00:30:36,076 [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
`

Why?

**Comment by dhirnitish** [comment]
@Jacopo1891 The servers are down so you are getting this.

**Comment by Stex** [comment]
@Jacopo1891 That's a general problem with the Pokémon GO servers which are currently unstable around the world.

Take a look at http://ispokemongodownornot.com/ or http://cmmcd.com/PokemonGo/ for more information

**Comment by Jacopo1891** [comment]
Thank you very much! @Stex @dhirnitish

**Comment by bjodasso** [comment]
Im using the dev branch but getting this:

Traceback (most recent call last):
  File "runserver.py", line 9, in <module>
    from pogom import config
ImportError: cannot import name config

**Comment by bjodasso** [comment]
Nevermind I got it running. Just no pokemon =/
