### ISSUE TITLE
table pokemon has no column named detect_time

### ISSUE THREAD

**Issue by dbusbridge** [AHAAAAAAA/PokemonGo-Map#674]
"table pokemon has no column named detect_time" error in Pokemon searching.

### Environment info
Operating System: Arch Linux + KDE Plasma

Installed version of Python:
conda virtualenv with python 2.7 created from requirements.txt

### Steps to reproduce
python runserver.py -a google -u **** -l **** -st 200 -p****

### Logs or other output that would be helpful
(pokemon) [dan@cognos PokemonGo-Map]$ python runserver.py -a google -u **** -l **** -st 200 -p**** 
2016-07-20 22:47:33,666 [  runserver] [   INFO] Parsed location is:****
2016-07-20 22:47:33,667 [     search] [   INFO] Attempting login.
2016-07-20 22:47:33,672 [auth_google] [   INFO] Google login for: ****
2016-07-20 22:47:33,673 [  _internal] [   INFO]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2016-07-20 22:47:34,510 [auth_google] [   INFO] Google Login successful.
2016-07-20 22:47:43,672 [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
2016-07-20 22:47:43,675 [     search] [   INFO] Login failed. Trying again.
2016-07-20 22:47:44,676 [auth_google] [   INFO] Google login for: ****
2016-07-20 22:47:45,329 [auth_google] [   INFO] Google Login successful.
2016-07-20 22:47:45,573 [     search] [   INFO] Login successful.
2016-07-20 22:47:45,574 [     search] [   INFO] Scanning step 1 of 40000.
2016-07-20 22:47:57,419 [     models] [   INFO] Upserting 1 pokemon
Exception in thread search_thread:
Traceback (most recent call last):
  File "/home/dan/.conda/envs/pokemon/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/dan/.conda/envs/pokemon/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dan/PokemonGo/PokemonGo-Map/pogom/search.py", line 100, in search_loop
    search(args)
  File "/home/dan/PokemonGo/PokemonGo-Map/pogom/search.py", line 89, in search
    parse_map(response_dict)
  File "/home/dan/PokemonGo/PokemonGo-Map/pogom/models.py", line 137, in parse_map
    InsertQuery(Pokemon, rows=pokemons.values()).upsert().execute()
  File "/home/dan/.conda/envs/pokemon/lib/python2.7/site-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/home/dan/.conda/envs/pokemon/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/dan/.conda/envs/pokemon/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/dan/.conda/envs/pokemon/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/dan/.conda/envs/pokemon/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table pokemon has no column named detect_time

**Comment by Stex** [comment]
The latest updates contained a database change. To fix it, simply delete the file `pogom.db` in the same directory as the `runserver.py`.

Once you restart the server, a new database file with the updated schema will be created automatically.

**Comment by dbusbridge** [comment]
Great, that works - thanks!
