### ISSUE TITLE
Operation Error: Could not decode

### ISSUE THREAD

**Issue by dhirnitish** [AHAAAAAAA/PokemonGo-Map#684]
2016-07-20 18:47:49,125 [        app] [  ERROR] Exception on /pokemons [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developerscodex/public_html/PokemonGo-Map-develop/pogom/app.py", line 40, in pokemons
    return jsonify(self.get_raw_data()['pokemons'])
  File "/home/developerscodex/public_html/PokemonGo-Map-develop/pogom/app.py", line 33, in get_raw_data
    'pokemons': Pokemon.get_active()
  File "/home/developerscodex/public_html/PokemonGo-Map-develop/pogom/models.py", line 43, in get_active
    for p in query:
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: Could not decode to UTF-8 column 'spawnpoint_id' with text '��������������������d��������������������'

**Comment by Skullmonkey** [comment]
Delete pogom.db and retry.

**Comment by dhirnitish** [comment]
Everytime i start the command i delete the database. It seems like a locale problem because its not able to understand the text it receives. Its on cent os 6.7

**Comment by dhirnitish** [comment]
@DerScreever @Skullmonkey  I have tried this but didn't seem to work. Any updates?

**Comment by dhirnitish** [comment]
http://stackoverflow.com/questions/22751363/sqlite3-operationalerror-could-not-decode-to-utf-8-column

**Comment by dhirnitish** [comment]
@DerScreever  @Skullmonkey The data is received correct but the problem is while inserting the data.

**Comment by pr0head** [comment]
@dhirnitish I have same problem.
How to solve this problem?

**Comment by dhirnitish** [comment]
First try to remove python 2.7 http://unix.stackexchange.com/questions/190794/uninstall-python-installed-by-compiling-source

Then follow this just till the installing python part - https://dmngaya.com/2015/10/25/installing-python-2-7-on-centos-6-7/

**Comment by pr0head** [comment]
@dhirnitish Thanks you
