### ISSUE TITLE
 Local server don't load CSS JS [help]

### ISSUE THREAD

**Issue by daknet01001** [AHAAAAAAA/PokemonGo-Map#695]
Hello,
the local server correctly load html.
but no CSS JS or favico.

during GET i have this log in server side:

`[2016-07-21 02:26:52,472] ERROR in app: Exception on /static/appicons/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
`

I'm on linux my python library seems ok.
I have turned off my apache server.

any idea?
thanks

**Comment by FrostTheFox** [comment]
Try redownloading develop. A bad commit removed some CSS stuff, a redownload should fix this as we have reverted the commit.

**Comment by daknet01001** [comment]
i have done it i a see the other thread but it's not the same issue.
the css file are in path and i don't have 404 but 500. and no js the other guys had the js right.

**Comment by FrostTheFox** [comment]
500? Interesting. JS was deleted as well in that reverted commit. I'll mark this.
