### ISSUE TITLE
Exception with latest dev commit

### ISSUE THREAD

**Issue by vincesmits** [AHAAAAAAA/PokemonGo-Map#698]
2016-07-21 02:33:15,444 [     models] [   INFO] Upserting 1 gyms
Exception in thread search_thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/vincesmits/PokemonGo-Map/pogom/search.py", line 100, in search_loop
    search(args)
  File "/Users/vincesmits/PokemonGo-Map/pogom/search.py", line 89, in search
    parse_map(response_dict)
  File "/Users/vincesmits/PokemonGo-Map/pogom/models.py", line 147, in parse_map
    InsertQuery(Gym, rows=gyms.values()).upsert().execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table gym has no column named gym_points

**Comment by fhirner** [comment]
remove pogom.db

**Comment by vincesmits** [comment]
that fixed it thanks, appreciate al the work you guys are doing !

**Comment by Skullmonkey** [comment]
A good rule of thumb, always delete it before running the script.

**Comment by NgJason** [comment]
Leads to another exception:
![screenshot 2016-07-20 17 43 11](https://cloud.githubusercontent.com/assets/6984333/17007925/79e84814-4ea1-11e6-9806-ec9a64e22c26.png)

**Comment by MikeDX** [comment]
> A good rule of thumb, always delete it before running the script.

I hope this won't always be the case! I'd like to build up a database of pokestops, gyms and common pokemon spawn locations
