### ISSUE TITLE
--ignore is not optional

### ISSUE THREAD

**Issue by stanleykylee** [AHAAAAAAA/PokemonGo-Map#70]
Running example.py with no -i causes the following error:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 392, in main
    ignore = [i.lower() for i in args.ignore.split(',')]
AttributeError: 'NoneType' object has no attribute 'split'

I'm able to bypass this by inputting a dummy value for --ignore (such as -i SOMETHING).

**Comment by medghaim** [comment]
Can confirm :(

**Comment by sykhro** [comment]
Fixed with 4dcb4b0
