### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by bjodasso** [AHAAAAAAA/PokemonGo-Map#706]
I am getting this certificate error after running it. Server starts up but nothing shows.

Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\pogomap\PokemonGo-Map-develop\pogom\search.py", line 100, in search_loop
    search(args)
  File "C:\pogomap\PokemonGo-Map-develop\pogom\search.py", line 75, in search
    login(args, position)
  File "C:\pogomap\PokemonGo-Map-develop\pogom\search.py", line 56, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "C:\pogomap\PokemonGo-Map-develop\pogom\pgoapi\pgoapi.py", line 144, in login
    if not self._auth_provider.login(username, password):
  File "C:\pogomap\PokemonGo-Map-develop\pogom\pgoapi\auth_google.py", line 47, in login
    login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "C:\Python27\lib\site-packages\requests\api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 480, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

How would I go about fixing a certificate issue?

**Comment by Bakies** [comment]
I think I was having this issue and used 
$ pip install requests[security]
to fix it

**Comment by bjodasso** [comment]
That caused a new error:
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by bjodasso** [comment]
I seem to have more issues i've had to add 
--trusted-host pypi.python.org 
to all the pip install commands.

**Comment by patchido** [comment]
i get the same error.
im using my own api key

```
2016-07-21 16:49:00,167 [  runserver] [   INFO] Parsed location is: 25.6579/-100
.3708/0.0000 (lat/lng/alt)
2016-07-21 16:49:00,167 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 16:49:00,197 [   auth_ptc] [   INFO] PTC login for: Patollaguno
2016-07-21 16:49:00,237 [  _internal] [   INFO]  * Running on http://127.0.0.1:5
000/ (Press CTRL+C to quit)
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\pllaguno\Desktop\PokemonGo-Map-develop\pogom\search.py", line 9
4, in search_loop
    search(args)
  File "C:\Users\pllaguno\Desktop\PokemonGo-Map-develop\pogom\search.py", line 6
9, in search
    login(args, position)
  File "C:\Users\pllaguno\Desktop\PokemonGo-Map-develop\pogom\search.py", line 5
0, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "C:\Users\pllaguno\Desktop\PokemonGo-Map-develop\pogom\pgoapi\pgoapi.py",
 line 144, in login
    if not self._auth_provider.login(username, password):
  File "C:\Users\pllaguno\Desktop\PokemonGo-Map-develop\pogom\pgoapi\auth_ptc.py
", line 52, in login
    r = self._session.get(self.PTC_LOGIN_URL, headers=head)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate'
, 'certificate verify failed')],)",)
```
