### ISSUE TITLE
too many SQL variables

### ISSUE THREAD

**Issue by Biztactix-Ryan** [AHAAAAAAA/PokemonGo-Map#711]
### Environment info
Operating System: Server 2012 R2

Installed version of Python:
2.712

### Steps to reproduce
1. c:\python27\python.exe runserver.py -u <user> -p <Pass> -dp -dg -H <IP> -P 85 -l "400 Collins Street,Melbourne,Australia" -st 20 -k <Key>
2. Within a few scan steps i Get the below log

### What have you tried?
1. Deleting the PogoDB and let it rebuild
2. It's working fine at other locations... 

### Logs or other output that would be helpful
2016-07-21 11:13:19,476 [     search] [   INFO] Scanning step 12 of 2500.
2016-07-21 11:13:20,615 [     models] [   INFO] Upserting 1 pokemon
2016-07-21 11:13:20,618 [     models] [   INFO] Upserting 188 pokestops
Exception in thread search_thread:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\PokemonGo\pogom\search.py", line 100, in search_loop
    search(args)
  File "C:\PokemonGo\pogom\search.py", line 89, in search
    parse_map(response_dict)
  File "C:\PokemonGo\pogom\models.py", line 143, in parse_map
    InsertQuery(Pokestop, rows=pokestops.values()).upsert().execute()
  File "c:\python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "c:\python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "c:\python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "c:\python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "c:\python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: too many SQL variables

**Comment by NgJason** [comment]
duplicate: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/699

**Comment by kingeddard** [comment]
I have the same issue here, i rarely get to 6 steps anymore
