### ISSUE TITLE
Missing t1.gym_points Column resulting in no displays on map

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#720]
Consequence of this error is i show nothing popping up on the map.

GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: WIndows 10

Installed version of Python: Python 2.7 (latest)

### Steps to reproduce
1. Run Server in area with Gym

### What have you tried?
1. Redownload

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

2016-07-21 12:05:37,446 [        app] [  ERROR] Exception on /pokestops/1469066737120 [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Valareos\Desktop\PokemonGo-Map-develop\pogom\app.py", line 43, in pokestops
    return jsonify(self.get_raw_data(stamp)['pokestops'])
  File "C:\Users\Valareos\Desktop\PokemonGo-Map-develop\pogom\app.py", line 31, in get_raw_data
    'gyms': [g for g in Gym.select().dicts()],
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.gym_points

**Comment by invisiblek** [comment]
stop your service, delete your pogom.db and restart the service

we need to figure out a better way to handle database migrations, but right now things are in too heavy of development

any time you see "no such column", do the above and you should be fine

**Comment by Valareos** [comment]
@invisiblek thank you for your assistance with this.
