### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by cmorbaab** [AHAAAAAAA/PokemonGo-Map#745]
I ran the line:

python example.py -a ptc -u ****** -p ****** -l "Some Location" -st 10

And I got this error:

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    import flask
  File "/Users/name/Downloads/PokemonGo-Map-master/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Users/name/Downloads/PokemonGo-Map-master/werkzeug/__init__.py", line 20, in <module>
    from werkzeug._compat import iteritems
  File "/Users/name/Downloads/PokemonGo-Map-master/werkzeug/_compat.py", line 5, in <module>
    import operator
  File "/Users/name/Downloads/PokemonGo-Map-master/operator.py", line 110
    return a @ b
             ^

I was wondering if this was an error in my python version or a bug.

**Comment by NickRimmer** [comment]
Try version from develop branch

**Comment by medghaim** [comment]
Please use the `develop` branch. Support for `master` has been dropped.
