### ISSUE TITLE
Someone help me now plz

### ISSUE THREAD

**Issue by nmtvictor** [AHAAAAAAA/PokemonGo-Map#756]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Víc\Desktop\PokemonGo-Map-EasyWin-master\example.py", line 792, in fullmap
    'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), auto_refresh=auto_refresh)
  File "C:\Users\Víc\Desktop\PokemonGo-Map-EasyWin-master\example.py", line 902, in get_map
    zoom='15', )
  File "C:\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 34, in __init__
    self.build_markers(markers)
  File "C:\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 58, in build_markers
    self.add_marker(**marker)
  File "C:\Python27\lib\site-packages\flask_googlemaps\__init__.py", line 81, in add_marker
    raise AttributeError('lat and lng required')
AttributeError: lat and lng required
this is my problem, anyone tell me what is the problem and how to fix it? thanks

**Comment by Ayysir** [comment]
are you using ` -l Locale` parameter?

**Comment by DerScreever** [comment]
post you command pls. maybe you have a comma on your location.

**Comment by KeithPetro** [comment]
Please give us the command you are running if you wish for us to help. Past that, join the discord server and you can get help there. This is most likely not a bug

**Comment by MonkeyLeeT** [comment]
Please join discord server and discuss there. Let's keep issues more issue-ish :D
