### ISSUE TITLE
/pokestops failing on latest commit

### ISSUE THREAD

**Issue by MikeDX** [AHAAAAAAA/PokemonGo-Map#774]
1. git checkout develop
2. git pull
3. pip install -r requirements.txt
4. python ./runserver.py -a ptc -u nonono -p nonono -l "disneyland" -dg -dp -H 0.0.0.0 -P 5000 -st 5
5. point browser at appropriate webpage

results from git commit 1c26e54de8c3de722f0231989b2a905ce1c33f08 (current head)

```
2016-07-21 04:04:48,179 [        app] [  ERROR] Exception on /pokestops [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mike/PokemonGo-Map/pogom/app.py", line 45, in pokestops
    return jsonify(Pokestop.get())
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/home/mike/PokemonGo-Map/pogom/app.py", line 80, in default
    return list(iterable)
TypeError: 'ResultIterator' object is not iterable
```

from commit 1818f9b6158b1375552b70d165170d4fba1a1d5f 

(same problem)

from commit 1b147752e9dd3749cc5fc8aa14b93ac62f1d80a5

works fine.

**Comment by rushingfitness** [comment]
Confirmed on my end as well.

**Comment by UzEE** [comment]
I have the same problem. 1818f9b seems to be a bad commit.

**Comment by lparkermg** [comment]
Can confirm that I'm getting the same issue as well. Seems to work fine until it his a pokestop.

**Comment by rushingfitness** [comment]
I'm pushing a PR to fix now

**Comment by medghaim** [comment]
Yep, sorry about that guys. 4:00am testing best testing. Testing out #777, if it works, we'll merge, if not, then we'll revert this.

**Comment by MonkeyLeeT** [comment]
Sorry for the inconvenience guys. A fix is identified and will be on the way.
