### ISSUE TITLE
help with "UnicodeDecodeError"!

### ISSUE THREAD

**Issue by CarvenSi** [AHAAAAAAA/PokemonGo-Map#784]
### Environment info
Operating System: Windows 10
Installed version of Python: 2.7.1.2

### Logs or other output that would be helpful
127.0.0.1 - - [21/Jul/2016 11:36:13] "GET /static/icons/16.png HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd2 in position 7: ordinal not in range(128)

What I can do?

**Comment by MonkeyLeeT** [comment]
Please attach the run argument you used, masking off username/password.

**Comment by CarvenSi** [comment]
python example.py -a google -u ****** -p ***** -l "56.252409, 51.288020" -st 10 -ar 5

**Comment by toumaz** [comment]
Are you running the program out of a directory path containing non-ASCII characters (like å, ä, ö, ô, ó, and so on)? Flask doesn't handle this very gracefully.

You could try moving the whole folder to a root drive (like C: or D: or such) and run it again to eliminate any possibility of non-ASCII characters being present.

**Comment by CarvenSi** [comment]
Thank you toumaz !!! It's work! I have moved to D! :+1:
