### ISSUE TITLE
OperationalError: table gym has no column named gym_points

### ISSUE THREAD

**Issue by pogorelchuk** [AHAAAAAAA/PokemonGo-Map#785]
python runserver.py -a google -u user -l 50.0054249,36.2429289 -dg -dp -st 10 -H 127.0.0.1 -P 8080

2016-07-21 04:43:09,715 [auth_google] [   INFO] Google Login successful.
2016-07-21 04:43:09,948 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-21 04:43:09,948 [     search] [   INFO] Scanning step 1 of 100.
2016-07-21 04:43:10,227 [     models] [   INFO] Upserting 3 pokemon
2016-07-21 04:43:10,232 [     models] [   INFO] Upserting 127 pokestops
2016-07-21 04:43:10,248 [     models] [   INFO] Upserting 6 gyms
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/www/wp-srv.ga/htdocs/PokemonGo-Map/pogom/search.py", line 94, in search_loop
    search(args)
  File "/var/www/wp-srv.ga/htdocs/PokemonGo-Map/pogom/search.py", line 83, in search
    parse_map(response_dict)
  File "/var/www/wp-srv.ga/htdocs/PokemonGo-Map/pogom/models.py", line 196, in parse_map
    InsertQuery(Gym, rows=gyms.values()).upsert().execute()
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/usr/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table gym has no column named gym_points

**Comment by michi0987** [comment]
Delete pogom.db or delete everything and unpack again. Worked for me

**Comment by DerScreever** [comment]
just delete pogom.db that work.

**Comment by pogorelchuk** [comment]
Thanks! Work!
