### ISSUE TITLE
error starting server

### ISSUE THREAD

**Issue by cooltagus** [AHAAAAAAA/PokemonGo-Map#799]
### Environment info
Operating System:
Windows 10

Installed version of Python:
Python 2.7

### Steps to reproduce
i did everything as said, and with the master Branch ther server initiates but will a bunch of erros, and someone siad to use the develop. and with that give the erros that follows, when I try to start the server.

### Logs 

C:\Users\Francisco\Desktop\PokemonGo-Map-develop>python runserver.py -a ptc -u [**] -p [**] -l "[39.160439,-8.8260738]" -st 10

Traceback (most recent call last):
  File "runserver.py", line 44, in <module>
    position = get_pos_by_name(args.location)
  File "C:\Users\Francisco\Desktop\PokemonGo-Map-develop\pogom\pgoapi\utilities.py", line 60, in get_pos_by_name
    latitude, longitude, altitude = loc.latitude, loc.longitude, loc.altitude
AttributeError: 'NoneType' object has no attribute 'latitude'

**Comment by Sejadis** [comment]
remove the [ ] from the coordinates

**Comment by cooltagus** [comment]
**Thank you, but now it give me this error**

2016-07-21 10:20:50,085 [  runserver] [   INFO] Parsed location is: 39.1604/-8.8261/0.0000 (lat/lng/alt)
2016-07-21 10:20:50,086 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 10:20:50,088 [   auth_ptc] [   INFO] PTC login for: [XXXXXX]
Traceback (most recent call last):
  File "runserver.py", line 82, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "C:\Users\Francisco\Desktop\PokemonGo-Map-develop\pogom\utils.py", line 114, in load_credentials
    with open(filepath+os.path.sep+'credentials.json') as file:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Francisco\\Desktop\\PokemonGo-Map-develop\\credentials.json'

**I only have a credentials.example.json on the directory, so I try to copy that and rename it to credentials.json, and it gave me this error instead.**


C:\Users\Francisco\Desktop\PokemonGo-Map-develop>python runserver.py -a ptc -u [cooltest081087] -p [$ines14072010] -l "39.160439,-8.8260738" -st 10
2016-07-21 10:22:27,345 [  runserver] [   INFO] Parsed location is: 39.1604/-8.8261/0.0000 (lat/lng/alt)
2016-07-21 10:22:27,348 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 10:22:27,351 [   auth_ptc] [   INFO] PTC login for: [XXXXXXXXXX]
Traceback (most recent call last):
  File "runserver.py", line 82, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "C:\Users\Francisco\Desktop\PokemonGo-Map-develop\pogom\utils.py", line 118, in load_credentials
    'No Google Maps Javascript API key entered. Please take a look at the wiki for instructions on how to generate this key.')
pogom.exceptions.APIKeyException: No Google Maps Javascript API key entered. Please take a look at the wiki for instructions on how to generate this key.

**Comment by Sejadis** [comment]
well that error clearly tells you what to do
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

**Comment by MikeDX** [comment]
The error message isn't just there for fun :)

No Google Maps Javascript API key entered. Please take a look at the wiki for instructions on how to generate this key.

You'll get there

This is definitely a support question that really should be elsewhere though, not a bug in the program at all.

**Comment by medghaim** [comment]
Aww, I thought I made the error message clear enough :(

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

That should help you out :)

**Comment by cooltagus** [comment]
**thank you so much it worked but i dint chage the -st 10 and in my zone I need more, now when I try to start the server again with -st 1000 it give me this error**

C:\Users\Francisco\Desktop\PokemonGo-Map-develop>python runserver.py -a ptc -u [XXXXX] -p [XXXXX] -l "39.160439,-8.8260738" -st 1000
2016-07-21 10:37:51,153 [  runserver] [   INFO] Parsed location is: 39.1604/-8.8261/0.0000 (lat/lng/alt)
2016-07-21 10:37:51,155 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 10:37:51,158 [   auth_ptc] [   INFO] PTC login for: [XXXXXX]
2016-07-21 10:37:51,165 [  _internal] [   INFO]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2016-07-21 10:37:52,075 [   auth_ptc] [  ERROR] Could not retrieve token: As a security measure, your account has been disabled for 15 minutes because you have failed to log in correctly too many times. Please come back and try again in 15 minutes.

can I do anything or just wait?

**Comment by Sejadis** [comment]
sounds like you mistyped your login data  
but you wont have fun with -st 1000 
it scans one area after the other so first off once an area has been scanned it will not be updatet until the whole scan finished and it starts from the beginning
so you will not see most of the spawns and most of your map will be empty because the scan will take much longer than the despawn time of the pkmn

**Comment by MikeDX** [comment]
-st 1000 will be a million steps per loop!

**Comment by godot12** [comment]
I don't have a crendentials.json file under config.
