### ISSUE TITLE
Too many SQL variables

### ISSUE THREAD

**Issue by lnmtriet93** [AHAAAAAAA/PokemonGo-Map#807]
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\PokemonGo-Map\pogom\search.py", line 94, in search_loop
    search(args)
  File "D:\Downloads\PokemonGo-Map\pogom\search.py", line 83, in search
    parse_map(response_dict)
  File "D:\Downloads\PokemonGo-Map\pogom\models.py", line 192, in parse_map
    InsertQuery(Pokestop, rows=pokestops.values()).upsert().execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: too many SQL variables

I faced this error on my last command. 
Here's the command:
runserver.py -u [USERNAME] -p [PASSWORD] -l [LOCATION] -st 10 -i Pidgey,Zubat,Rattata,Weedle,Spearow,Caterpie -ar 90 -dg

**Comment by medghaim** [comment]
#771, #699
