### ISSUE TITLE
problem after the log command

### ISSUE THREAD

**Issue by Korskyn** [AHAAAAAAA/PokemonGo-Map#813]
### Environment info
Operating System: windows 7

Installed version of Python:

### Steps to reproduce
after i run this command : C:\Python27\python example.py -a ptc -u xxxxxx -p xxxxx -l "31.592734 -34.764501" -st 10

its start well then it says :

2 erros
cannot load native moudle '%s' " % name
cannot load native moudle "cryptodome.cliper._raw_ecb

### What have you tried?
1.nothing i have no idea how i can fix it

### Logs or other output that would be helpful

C:\PokemonGo-Map-master>C:\Python27\python example.py -a ptc -u xxxxx -p xxxxx
1 -l "31.592734 -34.764501" -st 10
Traceback (most recent call last):
  File "example.py", line 32, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>

    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in
<module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <modu
le>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <modu
le>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, i
n <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46,
in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in
 load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

C:\PokemonGo-Map-master>

**Comment by mherceg** [comment]
You didn't install the required libraries
run this first:
pip install -r requirements.txt

**Comment by Korskyn** [comment]
nothing happen after i put pip install -r requiements.txt

**Comment by mherceg** [comment]
What do you mean by nothing happened? The pip install didn't run? It finished but you still get the same problem? Can you provide output of pip install please?

**Comment by Korskyn** [comment]
it just copy the previous command i type (cd C:\PokemonGo-Map-master)

**Comment by Korskyn** [comment]
oki i just install it now i putted (C:\Python27\python) in place of pip but still same problem later

**Comment by Korskyn** [comment]
Traceback (most recent call last):
  File "example.py", line 32, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>

    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in
<module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <modu
le>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <modu
le>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, i
n <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46,
in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in
 load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

that still what i get somebody help please?

**Comment by stinkybottomq** [comment]
I have followed all of the steps and I am receiving the same error as sykhro. My only difference is I have Windows 10. I have installed and uninstalled everything three times.

**Comment by dosin** [comment]
Got this problem as well. I'm trying to fix it. If done, I will share my experience here.

**Comment by dosin** [comment]
## Problem solved.
The old master is dropped. See [here](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki#project-refactor)
Reintall python and delete current PokemonGo-Map-master
Go through [wiki](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki) Again
## New usage:
```
python runserver.py -a google -u [username] -p [password] -k [gooleapikey] -l "[location]" -st 20
```
