### ISSUE TITLE
Exception in thread search_thread since commit 10461d32d46ba631e0c48af4ac6c1f350a7cf84c

### ISSUE THREAD

**Issue by kevdotcom** [AHAAAAAAA/PokemonGo-Map#831]
### Environment info
Operating System: Windows 7

Installed version of Python: 2.7

### Steps to reproduce
1. Download commit 10461d32d46ba631e0c48af4ac6c1f350a7cf84c or newer.
2. Start.
3. Watch Error.

### What have you tried?
1. Using an older version instead

### Logs or other output that would be helpful

Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\kevinschrader\Documents\GitHub\new\pogom\search.py", line 94, i
n search_loop
    search(args)
  File "C:\Users\kevinschrader\Documents\GitHub\new\pogom\search.py", line 83, i
n search
    parse_map(response_dict)
  File "C:\Users\kevinschrader\Documents\GitHub\new\pogom\models.py", line 196,
in parse_map
    InsertQuery(Gym, rows=gyms.values()).upsert().execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table gym has no column named gym_points

**Comment by adispen** [comment]
This happens because the schema was changed.  Simply remove the pogom.db file and restart the app.
