### ISSUE TITLE
Not able to see pokemon on map

### ISSUE THREAD

**Issue by sunny19** [AHAAAAAAA/PokemonGo-Map#840]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu

Installed version of Python: 7.2

### Steps to reproduce
1.python runserver.py -a ptc -u *** -p *** -l "12.9287660,77.6155150" -st 10

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sunny/projects/PokemonGo-Map/pogom/search.py", line 94, in search_loop
    search(args)
  File "/home/sunny/projects/PokemonGo-Map/pogom/search.py", line 83, in search
    parse_map(response_dict)
  File "/home/sunny/projects/PokemonGo-Map/pogom/models.py", line 136, in parse_map
    bulk_upsert(Pokestop, pokestops)
  File "/home/sunny/projects/PokemonGo-Map/pogom/models.py", line 149, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table pokestop has no column named active_pokemon_id

**Comment by DerScreever** [comment]
delete pogom.db
then restart.
