### ISSUE TITLE
IntegrityError: NOT NULL constraint failed: pokemon.detect_time

### ISSUE THREAD

**Issue by lnmtriet93** [AHAAAAAAA/PokemonGo-Map#843]
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\PokemonGo-Map\pogom\search.py", line 94, in search_loop
    search(args)
  File "D:\Downloads\PokemonGo-Map\pogom\search.py", line 83, in search
    parse_map(response_dict)
  File "D:\Downloads\PokemonGo-Map\pogom\models.py", line 132, in parse_map
    bulk_upsert(Pokemon, pokemons)
  File "D:\Downloads\PokemonGo-Map\pogom\models.py", line 149, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: pokemon.detect_time

After pull the most recent commit, I face this Error.
My command: runserver.py -u *** -p *** -l *** -st 10

**Comment by vaurdan** [comment]
Happening the same thing on the latest development branch (1f651228c00a96b86f5c38d1a2d53b32e5d9862)

**Comment by DerScreever** [comment]
tryed to remove the pogom.db?

**Comment by lnmtriet93** [comment]
Worked! After remove the pogom.db it worked correctly. Thank @DerScreever

**Comment by vaurdan** [comment]
Worked 👍
