### ISSUE TITLE
IntegrityError: NOT NULL constraint failed: pokemon.detect_time

### ISSUE THREAD

**Issue by rollin** [AHAAAAAAA/PokemonGo-Map#855]
I'm running the latest dev build and I keep getting this error. What might be the cause? Logs are included.

I'm on the c9.io workspace.

2016-07-21 16:04:09,174 [     search] [   INFO] Scanning step 1 of 49.
2016-07-21 16:04:09,176 [connectionpool] [   INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-07-21 16:04:09,468 [connectionpool] [  DEBUG] "POST /plfe/107/rpc HTTP/1.1" 200 None
2016-07-21 16:04:09,490 [     models] [   INFO] Upserting 3 pokemon
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/workspace/PokemonGo-Map/pogom/search.py", line 94, in search_loop
    search(args)
  File "/home/ubuntu/workspace/PokemonGo-Map/pogom/search.py", line 83, in search
    parse_map(response_dict)
  File "/home/ubuntu/workspace/PokemonGo-Map/pogom/models.py", line 132, in parse_map
    bulk_upsert(Pokemon, pokemons)
  File "/home/ubuntu/workspace/PokemonGo-Map/pogom/models.py", line 149, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: pokemon.detect_time

**Comment by DerScreever** [comment]
remove pogom.db
