### ISSUE TITLE
[Dev] [Bug] Invalid authentication provider Error when AR is active

### ISSUE THREAD

**Issue by IQNeoXen** [AHAAAAAAA/PokemonGo-Map#887]
Getting this error: 
`root@vps:/PokemonMapDev/PokemonGo-Map# python runserver.py -a google -u "username" -p "password" -l "**** Str 66" -st 5 -L de -H 0.0.0.0 -ar          2016-07-21 10:42:18,184 [  runserver] [   INFO] Parsed location is: 48.******/11.****/0.0000 (lat/lng/alt)
2016-07-21 10:42:18,185 [     search] [   INFO] Attempting login to Pokemon Go.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/PokemonMapDev/PokemonGo-Map/pogom/search.py", line 94, in search_loop
    search(args)
  File "/PokemonMapDev/PokemonGo-Map/pogom/search.py", line 69, in search
    login(args, position)
  File "/PokemonMapDev/PokemonGo-Map/pogom/search.py", line 50, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "/PokemonMapDev/PokemonGo-Map/pogom/pgoapi/pgoapi.py", line 140, in login
    raise AuthException("Invalid authentication provider - only ptc/google available.")
AuthException: Invalid authentication provider - only ptc/google available.

2016-07-21 10:42:18,193 [  _internal] [   INFO]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
`

This only happenes if `-ar` is active.

**Comment by JKapitein** [comment]
-ar seems to have been taken out of the argument list, meaning it will now probably match the -a switch and try to set the authentication method to 'r'.

You can check the available arguments at https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/utils.py

**Comment by IQNeoXen** [comment]
@JKapitein oh okay, didn't check it, sorry :D Is autorefresh going to be implemented?

**Comment by JKapitein** [comment]
It updates every 5 minutes at the moment, no setting for it yet.
