### ISSUE TITLE
Exception in thread search_thread

### ISSUE THREAD

**Issue by darkcloud784** [AHAAAAAAA/PokemonGo-Map#891]
I receive the following with running the script using the arguments -a PTC -u **** -p **** -l "11.1111, 11.111" -st 9

2016-07-21 10:02:15,336 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 10:02:15,340 [   auth_ptc] [   INFO] PTC login for: gutika113
2016-07-21 10:02:15,348 [  _internal] [   INFO]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2016-07-21 10:02:16,017 [   auth_ptc] [   INFO] PTC Login successful
2016-07-21 10:02:16,272 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-21 10:02:16,273 [     search] [   INFO] Scanning step 1 of 81.
2016-07-21 10:02:16,541 [     models] [   INFO] Upserting 2 pokemon
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/darkcloud/PokemonGo-Map/pogom/search.py", line 94, in search_loop
    search(args)
  File "/home/darkcloud/PokemonGo-Map/pogom/search.py", line 83, in search
    parse_map(response_dict)
  File "/home/darkcloud/PokemonGo-Map/pogom/models.py", line 132, in parse_map
    bulk_upsert(Pokemon, pokemons)
  File "/home/darkcloud/PokemonGo-Map/pogom/models.py", line 149, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: pokemon.detect_time

**Comment by JKapitein** [comment]
Remove pogom.db and restart the server.

**Comment by darkcloud784** [comment]
I did, but try to run more than one server at a time so I can get updates from multiple locations. Is this not possible anymore?
