### ISSUE TITLE
Throws error about unicode

### ISSUE THREAD

**Issue by PhantomKidding** [AHAAAAAAA/PokemonGo-Map#908]
[-] looping: step 18 of 25
[+] Searching for Pokemon at location 41.970636 -87.64987
Exception in thread search_thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 575, in main
    pokemonsJSON, ignore, only)
  File "main.py", line 675, in process_step
    notifier.pokemon_found(pokemon_obj)
  File "/Users/cchen/Programs/PokemonGo-Finder/notifier.py", line 31, in pokemon_found
    pokename = _str(pokemon["name"]).lower()
  File "/Users/cchen/Programs/PokemonGo-Finder/notifier.py", line 26, in _str
    return s.decode('utf-8').strip()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2642' in position 7: ordinal not in range(128)

**Comment by sykhro** [comment]
Are you using the latest commit?

**Comment by PhantomKidding** [comment]
Just download it from github 30min ago.

**Comment by PhantomKidding** [comment]
Maybe caused by the name of Nidoran♂?

**Comment by fettlaus** [comment]
See also #779
