### ISSUE TITLE
runserver.py: error: argument -p/--password: expected one argument

### ISSUE THREAD

**Issue by tripout** [AHAAAAAAA/PokemonGo-Map#917]
### Environment info
Operating System: Ubuntu 14.04

Installed version of Python:
2.7.6

### Steps to reproduce
1. Install latest develop branch
2. Run server
3. ???
4. Profit? 

### What have you tried?
1. Double checking my arguments

### Logs or other output that would be helpful
:~/PokemonGo-Map-develop$ python runserver.py -u ****** -p ********* -l "My location" -st 10 -ar 30 -dp -dg -H my.server.ip.here -P 8080 -k "mykeyhere"
usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
                    LOCATION -st STEP_LIMIT [-H HOST] [-P PORT] [-L LOCALE]
                    [-c] [-d] [-m] [-k GMAPS_KEY]
runserver.py: error: argument -p/--password: expected one argument

**Comment by k0mat** [comment]
remove -dp and -dg arguments

**Comment by sykhro** [comment]
`ar 30 -dp -dg ` are no longer needed. don't pass those arguments and it will work

**Comment by tripout** [comment]
The server runs but now I get this following error:

2016-07-21 09:04:12,258 [     models] [   INFO] Upserting 1 pokemon
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cmerrett/PokemonGo-Map-develop/pogom/search.py", line 94, in search_loop
    search(args)
  File "/home/cmerrett/PokemonGo-Map-develop/pogom/search.py", line 83, in search
    parse_map(response_dict)
  File "/home/cmerrett/PokemonGo-Map-develop/pogom/models.py", line 132, in parse_map
    bulk_upsert(Pokemon, pokemons)
  File "/home/cmerrett/PokemonGo-Map-develop/pogom/models.py", line 149, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: pokemon.detect_time


Should I create a new issue for this?

**Comment by sykhro** [comment]
delete the pogom.db file

**Comment by tripout** [comment]
Awesome! Thank you!
