### ISSUE TITLE
Cant see pokemons on map 

### ISSUE THREAD

**Issue by assor17** [AHAAAAAAA/PokemonGo-Map#927]
after installation 
 run by C:\Python27\python runserver.py -a ptc -u XXX -p XXX-l "XXX" -st 1

the output is : 

2016-07-21 19:19:12,697 [  _internal] [   INFO] 127.0.0.1 - - [21/Jul/2016 19:19
:12] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 200 -
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\oshera\Downloads\PokemonGo-Map-develop\pogom\search.py", line 9
4, in search_loop
    search(args)
  File "C:\Users\oshera\Downloads\PokemonGo-Map-develop\pogom\search.py", line 6
9, in search
    login(args, position)
  File "C:\Users\oshera\Downloads\PokemonGo-Map-develop\pogom\search.py", line 5
0, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "C:\Users\oshera\Downloads\PokemonGo-Map-develop\pogom\pgoapi\pgoapi.py",
 line 144, in login
    if not self._auth_provider.login(username, password):
  File "C:\Users\oshera\Downloads\PokemonGo-Map-develop\pogom\pgoapi\auth_ptc.py
", line 52, in login
    r = self._session.get(self.PTC_LOGIN_URL, headers=head)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='sso.pokemon.com', port=443): Max retr
ies exceeded with url: /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2F
oauth2.0%2FcallbackAuthorize (Caused by NewConnectionError('<requests.packages.u
rllib3.connection.VerifiedHTTPSConnection object at 0x03F331D0>: Failed to estab
lish a new connection: [Errno 10060] A connection attempt failed because the con
nected party did not properly respond after a period of time, or established con
nection failed because connected host has failed to respond',))

**Comment by DeviaVir** [comment]
It's literally in your error:

```
HTTPSConnectionPool(host='sso.pokemon.com', port=443)
```

> Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established con
nection failed because connected host has failed to respond',))

**Comment by assor17** [comment]
but i have a connection , when  I tried to browse and login its succeed
