### ISSUE TITLE
OperationalError: table pokestop has no column named active_pokemon_id

### ISSUE THREAD

**Issue by djderan** [AHAAAAAAA/PokemonGo-Map#948]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Windows 10
Installed version of Python:
2.7

### Steps to reproduce
1. Running standard parms latest version of dev

### What have you tried?
1. I posted on here before and had my issue closed for the same issue for gyms but answer was not resolved the previous issue suggested deleting pogom.db file, however that file does not exist in my project.  Any suggestions are appreciated!

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
2016-07-21 13:01:31,533 [   auth_ptc] [   INFO] PTC Login successful
2016-07-21 13:01:31,859 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-21 13:01:31,859 [     search] [   INFO] Scanning step 1 of 100.
2016-07-21 13:01:32,154 [     models] [   INFO] Upserting 2 pokestops
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\David\Desktop\PokemonGo-Map\pogom\search.py", line 94, in search_loop
    search(args)
  File "C:\Users\David\Desktop\PokemonGo-Map\pogom\search.py", line 83, in search
    parse_map(response_dict)
  File "C:\Users\David\Desktop\PokemonGo-Map\pogom\models.py", line 136, in parse_map
    bulk_upsert(Pokestop, pokestops)
  File "C:\Users\David\Desktop\PokemonGo-Map\pogom\models.py", line 149, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "C:\python27\lib\site-packages\peewee.py", line 3237, in execute
    return self._insert_with_loop()
  File "C:\python27\lib\site-packages\peewee.py", line 3220, in _insert_with_loop
    .upsert(self._upsert)
  File "C:\python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table pokestop has no column named active_pokemon_id

**Comment by sykhro** [comment]
Delete pogom.db

**Comment by djderan** [comment]
that file does not exist in my project

**Comment by fettlaus** [comment]
Don't feel insulted, but look again. The file has to be there somewhere. It will be recreated upon starting.

**Comment by djderan** [comment]
lol Im not insulted I appreciate the help, i did a full text search for the file in that folder and got no results. Is that file cached somewhere?

**Comment by fettlaus** [comment]
It should be right there. Is your folder maybe write protected?

**Comment by djderan** [comment]
Ok I found it, it was dumped in my user folder and its recreating there as well that seems odd

**Comment by fettlaus** [comment]
Great. So this issue can be closed.
