### ISSUE TITLE
Flask not installing properly

### ISSUE THREAD

**Issue by Pakalaka60** [AHAAAAAAA/PokemonGo-Map#957]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 10

Installed version of Python: 2.7.12

### Steps to reproduce
1.
2.
3.

### What have you tried?
1. Uninstalled Flask and Reinstalled

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "C:\Pokemon Go\pogom\app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template, request
ImportError: No module named flask                  I tried uninstalling flask but it said it wasnt there

**Comment by Pakalaka60** [comment]
I checked my requirements.txt and this was in it Flask==0.11.1
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.10
argparse==1.2.1
click==6.6
itsdangerous==0.24
peewee==2.8.1
wsgiref==0.1.2
geopy==1.11.0
protobuf==2.6.1
requests==2.10.0
s2sphere==0.2.4
gpsoauth==0.3.0
protobuf-to-dict==0.1.0
