### ISSUE TITLE
OSX pip install -r requirements.txt ERROR

### ISSUE THREAD

**Issue by NeoVilsonWong** [AHAAAAAAA/PokemonGo-Map#959]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:OSX

Installed version of Python:2.7

Here The Error::

pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): flask-googlemaps==0.2.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Collecting flask==0.11.1 (from -r requirements.txt (line 6))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): coveralls==1.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from protobuf==2.6.1->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python2.7/site-packages (from s2sphere==0.2.4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in /usr/local/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /usr/local/lib/python2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): docopt>=0.6.1 in /usr/local/lib/python2.7/site-packages (from coveralls==1.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.6 in /usr/local/lib/python2.7/site-packages (from coveralls==1.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 6))
Installing collected packages: flask
  Found existing installation: Flask 0.10.1
    Uninstalling Flask-0.10.1:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg-info/dependency_links.txt'

**Comment by NeoVilsonWong** [comment]
Solve Run With Sudo thanks
