### ISSUE TITLE
Wrong order of 'auth_ticket' params in function 'set_ticket'

### ISSUE THREAD

**Issue by HanSolo80** [AHAAAAAAA/PokemonGo-Map#965]
**Prerequisites: I am running the map on Heroku using PTC as auth method.**

When the api restarts the step loop the following error appears:

```
2016-07-21T17:23:50.140290+00:00 app[web.1]: Exception in thread search_thread:
2016-07-21T17:23:50.140292+00:00 app[web.1]: Traceback (most recent call last):
2016-07-21T17:23:50.140293+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2016-07-21T17:23:50.140294+00:00 app[web.1]:     self.run()
2016-07-21T17:23:50.140295+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 754, in run
2016-07-21T17:23:50.140295+00:00 app[web.1]:     self.__target(*self.__args, **self.__kwargs)
2016-07-21T17:23:50.140296+00:00 app[web.1]:   File "/app/pogom/search.py", line 101, in search_loop
2016-07-21T17:23:50.140297+00:00 app[web.1]:     search(args)
2016-07-21T17:23:50.140297+00:00 app[web.1]:   File "/app/pogom/search.py", line 66, in search
2016-07-21T17:23:50.140298+00:00 app[web.1]:     remaining_time = api._auth_provider._ticket_expire/1000 - time.time()
2016-07-21T17:23:50.140299+00:00 app[web.1]: TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

This is due to the fact that the _params_ in the following method in _auth.py_ were reversed:

```
def set_ticket(self, params):
        self._ticket_expire, self._ticket_start, self._ticket_end = params
```

I logged the _params_ parameter in this function and got this output. As you can see the _ticket_expire_ variable is at position 1 in the array. But, the _set_ticket_ function expects this to be at position 0 in the array. 

```
2016-07-21T17:22:56.229425+00:00 app[web.1]: 2016-07-21 19:22:56,229 [       auth] [   INFO] ['GZUGG9wKaKPak92xRQ/pY2Wrdo4wHyDJbsW/9YUamMweTHF8pTUmdwKmUBNIzrcEEVltjb64zT2H\n9JSKr+YsjQ==\n', 1469123576174L, 'O93I07svexSdgzLYKHL9Ig==\n']
```

Unfortunately I couldn't reproduce this behavior consistently as when running locally the order of the parameters were always correct, when running on Heroku the order most of the time was wrong. But, sometimes the order is correct when running on Heroku as well.

**Comment by HanSolo80** [comment]
Why did you close the ticket without a comment? Is it solved? I can't find any commit which is relevant. I invested some time to discover the source of the bug and now I feel it was in vain.

**Comment by statuswoe** [comment]
I agree, what was the resolution?
