### ISSUE TITLE
Python Tracebacks on dev branch

### ISSUE THREAD

**Issue by ekbfh** [AHAAAAAAA/PokemonGo-Map#979]
Startin with python runserver.py -a ptc -u $user -p $pass -l "$LOCATION" -st 5 -H $IP -P 5000

### Environment info
win10x64, Python 2.7.12

### Steps to reproduce
1. Start the command
2. Get trace
3. Profit

C:\Python27\PokemonGo-Map-master>python runserver.py etc..etc..etc...
2016-07-21 21:10:50,506 [  runserver] [   INFO] Parsed location is: $location/0.0000 (lat/lng/alt)
2016-07-21 21:10:50,506 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 21:10:50,509 [   auth_ptc] [   INFO] PTC login for: $user
2016-07-21 21:10:50,522 [  _internal] [   INFO]  * Running on http://$IP:5000 (Press CTRL+C to quit)
2016-07-21 21:10:51,663 [   auth_ptc] [   INFO] PTC Login successful
2016-07-21 21:10:51,974 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-21 21:10:51,976 [     search] [   INFO] Scanning step 1 of 25.
2016-07-21 21:10:52,285 [     models] [   INFO] Upserting 2 pokemon
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\PokemonGo-Map-master\pogom\search.py", line 94, in search_loop
    search(args)
  File "C:\Python27\PokemonGo-Map-master\pogom\search.py", line 83, in search
    parse_map(response_dict)
  File "C:\Python27\PokemonGo-Map-master\pogom\models.py", line 132, in parse_map
    bulk_upsert(Pokemon, pokemons)
  File "C:\Python27\PokemonGo-Map-master\pogom\models.py", line 149, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute
    cursor = self._execute()
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: pokemon.detect_time

And then there are no pokemons on map and etc. Is this caused by server connection or what? We can try/catch this, maybe. (i'm not a python programmer)

**Comment by ekbfh** [comment]
also very often is "OperationalError: no such column: t1.active_pokemon_id"

**Comment by Sejadis** [comment]
yeah getting both of them too

**Comment by Relf-PP** [comment]
I seem to have the same kind of problem. I tried to upgrade the requirements (`pip install -r requirements.txt --upgrade`) but it didn't change anything.

```
2016-07-21 20:50:22,942 [  runserver] [   INFO] Parsed location is: 43.6043/1.3648/0.0000 (lat/lng/alt)
2016-07-21 20:50:22,942 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 20:50:22,943 [   auth_ptc] [   INFO] PTC login for: xxxxxxxxx
2016-07-21 20:50:22,955 [  _internal] [   INFO]  * Running on http://localhost:2305/ (Press CTRL+C to quit)
2016-07-21 20:50:24,646 [   auth_ptc] [   INFO] PTC Login successful
[2016-07-21 20:50:25,166] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/my_user/code/PokemonGo-Map/pogom/app.py", line 33, in raw_data
    d['pokestops'] = Pokestop.get_all()
  File "/home/my_user/code/PokemonGo-Map/pogom/models.py", line 24, in get_all
    return [m for m in cls.select().dicts()]
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.active_pokemon_id
2016-07-21 20:50:25,166 [        app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/my_user/code/PokemonGo-Map/pogom/app.py", line 33, in raw_data
    d['pokestops'] = Pokestop.get_all()
  File "/home/my_user/code/PokemonGo-Map/pogom/models.py", line 24, in get_all
    return [m for m in cls.select().dicts()]
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.active_pokemon_id
2016-07-21 20:50:25,168 [  _internal] [   INFO] 127.0.0.1 - - [21/Jul/2016 20:50:25] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 500 -
2016-07-21 20:50:25,526 [     search] [   INFO] Login to Pokemon Go successful.
2016-07-21 20:50:25,527 [     search] [   INFO] Scanning step 1 of 100.
2016-07-21 20:50:26,678 [     models] [   INFO] Upserting 2 pokemon
2016-07-21 20:50:26,688 [     models] [   INFO] Upserting 4 pokestops
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/my_user/code/PokemonGo-Map/pogom/search.py", line 94, in search_loop
    search(args)
  File "/home/my_user/code/PokemonGo-Map/pogom/search.py", line 83, in search
    parse_map(response_dict)
  File "/home/my_user/code/PokemonGo-Map/pogom/models.py", line 136, in parse_map
    bulk_upsert(Pokestop, pokestops)
  File "/home/my_user/code/PokemonGo-Map/pogom/models.py", line 149, in bulk_upsert
    InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().execute()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3244, in execute
    cursor = self._execute()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: table pokestop has no column named active_pokemon_id

[2016-07-21 20:50:30,170] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/my_user/code/PokemonGo-Map/pogom/app.py", line 33, in raw_data
    d['pokestops'] = Pokestop.get_all()
  File "/home/my_user/code/PokemonGo-Map/pogom/models.py", line 24, in get_all
    return [m for m in cls.select().dicts()]
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.active_pokemon_id
2016-07-21 20:50:30,170 [        app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/my_user/code/PokemonGo-Map/pogom/app.py", line 33, in raw_data
    d['pokestops'] = Pokestop.get_all()
  File "/home/my_user/code/PokemonGo-Map/pogom/models.py", line 24, in get_all
    return [m for m in cls.select().dicts()]
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.active_pokemon_id
2016-07-21 20:50:30,171 [  _internal] [   INFO] 127.0.0.1 - - [21/Jul/2016 20:50:30] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 500 -
[2016-07-21 20:50:35,164] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/my_user/code/PokemonGo-Map/pogom/app.py", line 33, in raw_data
    d['pokestops'] = Pokestop.get_all()
  File "/home/my_user/code/PokemonGo-Map/pogom/models.py", line 24, in get_all
    return [m for m in cls.select().dicts()]
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.active_pokemon_id
2016-07-21 20:50:35,164 [        app] [  ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/my_user/code/PokemonGo-Map/pogom/app.py", line 33, in raw_data
    d['pokestops'] = Pokestop.get_all()
  File "/home/my_user/code/PokemonGo-Map/pogom/models.py", line 24, in get_all
    return [m for m in cls.select().dicts()]
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/my_user/.virtualenvs/pokemap/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.active_pokemon_id
2016-07-21 20:50:35,165 [  _internal] [   INFO] 127.0.0.1 - - [21/Jul/2016 20:50:35] "GET /raw_data?pokemon=true&pokestops=true&gyms=true HTTP/1.1" 500 -

```

**Comment by Relf-PP** [comment]
Indeed, the deletion of pogom.db file seems to repair the problem.

**Comment by ekbfh** [comment]
Yes, i deleted .db file and everything is ok.

**Comment by darcycartwright** [comment]
Is it meant to restore the .db file on its own? 

Or do I need to manually copy a new one back in?

**Comment by Sejadis** [comment]
it will create a new one as soon as you run the script
